NebulaSEM: ASYNC_COMM< T > Class Template Reference
ASYNC_COMM< T > Class Template Reference
#include <field.h>
Public Member Functions
ASYNC_COMM (T *p)
void send ()
void recv ()
Detailed Description
template<class T>
class ASYNC_COMM< T >
Class for asynchronous communication using MPI
Definition at line 2211 of file field.h.
Constructor & Destructor Documentation
ASYNC_COMM()
template<class T > ASYNC_COMM< T >::ASYNC_COMM (T * p) inline
Definition at line 2219 of file field.h.
Member Function Documentation
recv()
template<class T > void ASYNC_COMM< T >::recv () inline
Definition at line 2256 of file field.h.
References Mesh::interBoundary::buffer_index, Mesh::interBoundary::f, Mesh::FN, forEach, Mesh::gInterMesh, DG::NPF, and MP::waitall().
Referenced by applyExplicitBCs(), fillBCs(), getRHS(), Mesh::initGeomMeshFields(), mul(), and mult().
send()
template<class T > void ASYNC_COMM< T >::send () inline
Definition at line 2222 of file field.h.
References Mesh::interBoundary::buffer_index, Mesh::interBoundary::f, MP::FIELD_BLK, Mesh::FO, forEach, Mesh::gInterMesh, MP::irecieve(), MP::isend(), DG::NPF, and Mesh::interBoundary::to.
Referenced by applyExplicitBCs(), fillBCs(), getRHS(), Mesh::initGeomMeshFields(), mul(), and mult().
The documentation for this class was generated from the following file:
/home/daniel/storage/NebulaSEM/src/field/field.h