NebulaSEM: MeshField< type, entity > Class Template Reference
MeshField< type, entity > Class Template Reference
#include <field.h>
Public Types
typedef std::list< MeshField< type, VERTEX > > vertexFieldsType
Public Member Functions
MeshField (const char *str="", ACCESS a=NO, bool recycle=true)
MeshField (const MeshField &p)
MeshField (const type &p)
MeshField (const bool)
void allocate (bool recycle=true)
void allocate (std::vector< type > &q)
void deallocate (bool recycle=true)
void construct (const char *str="", ACCESS a=NO, bool recycle=true)
~MeshField ()
FORCEINLINE Int size () const
FORCEINLINE type & operator[] (Int i) const
Op (=) SOp(
Int readInternal (std::istream &is, Int offset=0) override
void readBoundary (std::istream &is) override
void writeInternal (std::ostream &os, IntVector *cMap) override
void writeBoundary (std::ostream &os) override
void read (std::istream &os) override
void write (std::ostream &os, IntVector *cMap) override
Int readInternal (Util::ifstream_bin &is, Int offset=0) override
void readBoundary (Util::ifstream_bin &is) override
void writeInternal (Util::ofstream_bin &os, IntVector *cMap) override
void writeBoundary (Util::ofstream_bin &os) override
void read (Util::ifstream_bin &os) override
void write (Util::ofstream_bin &os, IntVector *cMap) override
void norm (BaseField *pnorm)
void initStore (Int nstore_, const MeshField &vF)
void updateStore (const MeshField &vF)
Typedef common matrix types
void refineField (Int, const IntVector &, const IntVector &, const IntVector &, const Int, const ScalarVector &, const VectorVector &, const VectorVector &)
Public Member Functions inherited from BaseField
virtual ~BaseField ()
Static Public Member Functions
static void readAll (Int step)
static void writeAll (Int step)
static void removeAll ()
static int count_writable ()
static void writeVtkCellAll (std::ostream &os)
static void writeVtkVertexAll (std::ostream &os)
static void interpolateVertexAll ()
static void initTimeSeries ()
static void updateTimeSeries (int i)
static void printUsage ()
Static Public Member Functions inherited from BaseField
static void destroyFields ()
static BaseField * findField (const std::string &name)
Public Attributes
ACCESS access
Int fIndex
MeshField * tstore
Int nstore
Int nstored
Public Attributes inherited from BaseField
std::string fName
Static Public Attributes
static constexpr Int TYPE_SIZE = sizeof(type) / sizeof(Scalar)
Static variables of MeshField
static std::list< MeshField * > fields_
static std::list< type * > mem_pool
static Int n_alloc
static Int n_alloc_max
static vertexFieldsType * vf_fields_
static std::vector< std::ofstream * > tseries
static std::vector< MeshField * > tavgs
static std::vector< MeshField * > tstds
Static Public Attributes inherited from BaseField
static std::list< BaseField * > allFields
static std::vector< std::string > fieldNames
Friends
template<typename Ts >
Ts & operator<< (Ts &os, MeshField &p)
template<typename Ts >
Ts & operator>> (Ts &is, MeshField &p)
Expression template operators
void read (Int step)
void write (Int step, IntVector *=0)
Detailed Description
template<class type, ENTITY entity>
class MeshField< type, entity >
Template field class for field of type (scalar,vector,tensor) defined on entity (vertex,face or cell)
Definition at line 743 of file field.h.
Member Typedef Documentation
vertexFieldsType
template<class type , ENTITY entity> typedef std::list< MeshField<type,VERTEX> > MeshField< type, entity >::vertexFieldsType
Definition at line 1054 of file field.h.
Constructor & Destructor Documentation
MeshField() [1/4]
template<class type , ENTITY entity> MeshField< type, entity >::MeshField (const char * str = "", ACCESS a = NO, bool recycle = true) inline
Definition at line 781 of file field.h.
MeshField() [2/4]
template<class type , ENTITY entity> MeshField< type, entity >::MeshField (const MeshField< type, entity > & p) inline
Definition at line 787 of file field.h.
References forEach.
MeshField() [3/4]
template<class type , ENTITY entity> MeshField< type, entity >::MeshField (const type & p) inline
Definition at line 794 of file field.h.
References forEach.
MeshField() [4/4]
template<class type , ENTITY entity> MeshField< type, entity >::MeshField (const bool) inline explicit
Definition at line 801 of file field.h.
~MeshField()
template<class type , ENTITY entity> MeshField< type, entity >::~MeshField () inline
Definition at line 862 of file field.h.
References MP::Terminated.
Member Function Documentation
allocate() [1/2]
template<class type , ENTITY entity> void MeshField< type, entity >::allocate (bool recycle = true) inline
Definition at line 806 of file field.h.
References CELL, CELLMAT, FACET, Mesh::gCells, Mesh::gFacets, Mesh::gVertices, DG::NP, DG::NPF, DG::NPMAT, and VERTEX.
Referenced by Mesh::initGeomMeshFields(), and SolveT().
allocate() [2/2]
template<class type , ENTITY entity> void MeshField< type, entity >::allocate (std::vector< type > & q) inline
Definition at line 829 of file field.h.
construct()
template<class type , ENTITY entity> void MeshField< type, entity >::construct (const char * str = "", ACCESS a = NO, bool recycle = true) inline
Definition at line 850 of file field.h.
References BasicBCondition::fIndex, Mesh::gCells, and Util::hash_function().
Referenced by DG::init_geom(), and Mesh::initGeomMeshFields().
count_writable()
template<class type , ENTITY entity> static int MeshField< type, entity >::count_writable () inline static
Definition at line 1019 of file field.h.
References forEachIt, and WRITE.
Referenced by Vtk::write_vtk().
deallocate()
template<class type , ENTITY entity> void MeshField< type, entity >::deallocate (bool recycle = true) inline virtual
Implements BaseField.
Definition at line 834 of file field.h.
References BasicBCondition::fIndex.
Referenced by DG::init_geom(), and Mesh::initGeomMeshFields().
initStore()
template<class type , ENTITY entity> void MeshField< type, entity >::initStore (Int nstore_, const MeshField< type, entity > & vF) inline
Definition at line 1071 of file field.h.
References STOREPREV.
Referenced by addTemporal().
initTimeSeries()
template<class type , ENTITY entity> static void MeshField< type, entity >::initTimeSeries () inline static
Definition at line 1090 of file field.h.
References MeshField< type, entity >::access, BaseField::fName, forEachIt, Mesh::probeCells, READWRITE, Controls::save_average, and WRITE.
interpolateVertexAll()
template<class type , ENTITY entity> static void MeshField< type, entity >::interpolateVertexAll () inline static
Definition at line 1056 of file field.h.
References cds(), forEachIt, and WRITE.
norm()
template<class type , ENTITY entity> void MeshField< type, entity >::norm (BaseField * pnorm) inline virtual
Implements BaseField.
Definition at line 996 of file field.h.
References mag().
Op()
template<class type , ENTITY entity> MeshField< type, entity >::Op ()
References forEach.
operator[]()
template<class type , ENTITY entity> FORCEINLINE type& MeshField< type, entity >::operator[] (Int i) const inline
Definition at line 870 of file field.h.
printUsage()
template<class type , ENTITY entity> static void MeshField< type, entity >::printUsage () inline static
Definition at line 1149 of file field.h.
read() [1/3]
template<class T , ENTITY E> void MeshField< T, E >::read (Int step) virtual
Implements BaseField.
Definition at line 1535 of file field.h.
References System::exists(), and MP::printOn.
read() [2/3]
template<class type , ENTITY entity> void MeshField< type, entity >::read (std::istream & os) inline override virtual
Implements BaseField.
Definition at line 983 of file field.h.
read() [3/3]
template<class type , ENTITY entity> void MeshField< type, entity >::read (Util::ifstream_bin & os) inline override virtual
Implements BaseField.
Definition at line 990 of file field.h.
readAll()
template<class type , ENTITY entity> static void MeshField< type, entity >::readAll (Int step) inline static
Definition at line 1000 of file field.h.
References forEachIt, and READ.
readBoundary() [1/2]
template<class type , ENTITY entity> void MeshField< type, entity >::readBoundary (std::istream & is) inline override virtual
Implements BaseField.
Definition at line 980 of file field.h.
readBoundary() [2/2]
template<class type , ENTITY entity> void MeshField< type, entity >::readBoundary (Util::ifstream_bin & is) inline override virtual
Implements BaseField.
Definition at line 987 of file field.h.
readInternal() [1/2]
template<class type , ENTITY entity> Int MeshField< type, entity >::readInternal (std::istream & is, Int offset = 0) inline override virtual
Implements BaseField.
Definition at line 979 of file field.h.
readInternal() [2/2]
template<class type , ENTITY entity> Int MeshField< type, entity >::readInternal (Util::ifstream_bin & is, Int offset = 0) inline override virtual
Implements BaseField.
Definition at line 986 of file field.h.
refineField()
template<class type , ENTITY entity> void MeshField< type, entity >::refineField (Int step, const IntVector & refineMap, const IntVector & coarseMap, const IntVector & cellMap, const Int nCells, const ScalarVector & oldCV, const VectorVector & oldCC, const VectorVector & newCC) virtual
Implements BaseField.
Definition at line 1818 of file field.h.
References Mesh::cC, dot(), forEach, forEachLgl, Mesh::gBCSfield, Mesh::gCV, INDEX4, mag(), Constants::MAX_INT, DG::NP, DG::NPMAT, DG::NPX, DG::NPY, DG::NPZ, DG::psiCor, DG::psiRef, Scalar, sdiv(), DG::wgl, and WRITE.
removeAll()
template<class type , ENTITY entity> static void MeshField< type, entity >::removeAll () inline static
Definition at line 1012 of file field.h.
References forEachIt.
size()
template<class type , ENTITY entity> FORCEINLINE Int MeshField< type, entity >::size () const inline
Definition at line 867 of file field.h.
Referenced by Mesh::calc_courant(), DG::expand(), and MeshField< type, entity >::writeVtkVertexAll().
updateStore()
template<class type , ENTITY entity> void MeshField< type, entity >::updateStore (const MeshField< type, entity > & vF) inline
Definition at line 1079 of file field.h.
Referenced by addTemporal().
updateTimeSeries()
template<class type , ENTITY entity> static void MeshField< type, entity >::updateTimeSeries (int i) inline static
Definition at line 1112 of file field.h.
References MeshField< type, entity >::access, forEach, forEachIt, Mesh::probeCells, Controls::save_average, and WRITE.
write() [1/3]
template<class T , ENTITY E> void MeshField< T, E >::write (Int step, IntVector * cMap = 0) virtual
Implements BaseField.
Definition at line 1621 of file field.h.
References Controls::TEXT, and Controls::write_format.
write() [2/3]
template<class type , ENTITY entity> void MeshField< type, entity >::write (std::ostream & os, IntVector * cMap) inline override virtual
Implements BaseField.
Definition at line 984 of file field.h.
write() [3/3]
template<class type , ENTITY entity> void MeshField< type, entity >::write (Util::ofstream_bin & os, IntVector * cMap) inline override virtual
Implements BaseField.
Definition at line 991 of file field.h.
writeAll()
template<class type , ENTITY entity> static void MeshField< type, entity >::writeAll (Int step) inline static
Definition at line 1006 of file field.h.
References forEachIt, and WRITE.
writeBoundary() [1/2]
template<class type , ENTITY entity> void MeshField< type, entity >::writeBoundary (std::ostream & os) inline override virtual
Implements BaseField.
Definition at line 982 of file field.h.
writeBoundary() [2/2]
template<class type , ENTITY entity> void MeshField< type, entity >::writeBoundary (Util::ofstream_bin & os) inline override virtual
Implements BaseField.
Definition at line 989 of file field.h.
writeInternal() [1/2]
template<class type , ENTITY entity> void MeshField< type, entity >::writeInternal (std::ostream & os, IntVector * cMap) inline override virtual
Implements BaseField.
Definition at line 981 of file field.h.
writeInternal() [2/2]
template<class type , ENTITY entity> void MeshField< type, entity >::writeInternal (Util::ofstream_bin & os, IntVector * cMap) inline override virtual
Implements BaseField.
Definition at line 988 of file field.h.
writeVtkCellAll()
template<class type , ENTITY entity> static void MeshField< type, entity >::writeVtkCellAll (std::ostream & os) inline static
Definition at line 1027 of file field.h.
References MeshField< type, entity >::access, BaseField::fName, forEachIt, Mesh::gBCSfield, and WRITE.
writeVtkVertexAll()
template<class type , ENTITY entity> static void MeshField< type, entity >::writeVtkVertexAll (std::ostream & os) inline static
Definition at line 1040 of file field.h.
References cds(), forEach, forEachIt, MeshField< type, entity >::size(), and WRITE.
Friends And Related Function Documentation
operator<<
template<class type , ENTITY entity> template<typename Ts > Ts& operator<< (Ts & os, MeshField< type, entity > & p) friend
Definition at line 1139 of file field.h.
operator>>
template<class type , ENTITY entity> template<typename Ts > Ts& operator>> (Ts & is, MeshField< type, entity > & p) friend
Definition at line 1144 of file field.h.
Member Data Documentation
access
template<class type , ENTITY entity> ACCESS MeshField< type, entity >::access
Definition at line 771 of file field.h.
Referenced by addTemporal(), MeshField< type, entity >::initTimeSeries(), MeshField< type, entity >::updateTimeSeries(), and MeshField< type, entity >::writeVtkCellAll().
fields_
template<class T , ENTITY E> std::list< MeshField< T, E > * > MeshField< T, E >::fields_ static
Definition at line 776 of file field.h.
fIndex
template<class type , ENTITY entity> Int MeshField< type, entity >::fIndex
Definition at line 772 of file field.h.
Referenced by applyExplicitBCs(), applyImplicitBCs(), Mesh::fixedBCs(), EddyViscosity_Model::FixNearWallValues(), gradf(), Mesh::scaleBCs(), and EddyViscosity_Model::setWallEddyMu().
mem_pool
template<class T , ENTITY E> std::list< T * > MeshField< T, E >::mem_pool static
Definition at line 777 of file field.h.
n_alloc
template<class T , ENTITY E> Int MeshField< T, E >::n_alloc static
Definition at line 778 of file field.h.
n_alloc_max
template<class T , ENTITY E> Int MeshField< T, E >::n_alloc_max static
Definition at line 778 of file field.h.
nstore
template<class type , ENTITY entity> Int MeshField< type, entity >::nstore
Definition at line 1069 of file field.h.
nstored
template<class type , ENTITY entity> Int MeshField< type, entity >::nstored
Definition at line 1070 of file field.h.
Referenced by addTemporal(), ddt(), and ddt2().
tavgs
template<class T , ENTITY E> std::vector< MeshField< T, E > * > MeshField< T, E >::tavgs static
Definition at line 1087 of file field.h.
tseries
template<class T , ENTITY E> std::vector< std::ofstream * > MeshField< T, E >::tseries static
Definition at line 1086 of file field.h.
tstds
template<class T , ENTITY E> std::vector< MeshField< T, E > * > MeshField< T, E >::tstds static
Definition at line 1088 of file field.h.
tstore
template<class type , ENTITY entity> MeshField* MeshField< type, entity >::tstore
Definition at line 1068 of file field.h.
TYPE_SIZE
template<class type , ENTITY entity> constexpr Int MeshField< type, entity >::TYPE_SIZE = sizeof(type) / sizeof(Scalar) static constexpr
Definition at line 775 of file field.h.
vf_fields_
template<class T , ENTITY E> MeshField< T, E >::vertexFieldsType * MeshField< T, E >::vf_fields_ static
Definition at line 1055 of file field.h.
The documentation for this class was generated from the following file:
/home/daniel/storage/NebulaSEM/src/field/field.h