NebulaSEM: Iteration Class Reference
Iteration Class Reference
#include <iteration.h>
Public Member Functions
Iteration (int step)
bool start ()
bool end ()
void next ()
~Iteration ()
Int get_step ()
Detailed Description
Iteration object that does common book keeping stuff for all solvers.
Definition at line 8 of file iteration.h.
Constructor & Destructor Documentation
Iteration()
Iteration::Iteration (int step) inline
Definition at line 18 of file iteration.h.
References Controls::amr_step, Controls::current_step, Controls::end_step, Constants::EqualEpsilon, forEachCellField, Mesh::getProbeCells(), Controls::n_deferred, MP::printH(), MP::printOn, Mesh::probeCells, Mesh::read_fields(), and Controls::write_interval.
~Iteration()
Iteration::~Iteration () inline
Definition at line 85 of file iteration.h.
Member Function Documentation
end()
bool Iteration::end () inline
Definition at line 44 of file iteration.h.
References Controls::dt, MP::printH(), MP::printOn, Controls::state, Controls::STEADY, and Mesh::write_fields().
get_step()
Int Iteration::get_step () inline
Definition at line 87 of file iteration.h.
next()
void Iteration::next () inline
Definition at line 62 of file iteration.h.
References Controls::current_step, Controls::end_step, forEachCellField, MP::hasElapsed(), MP::host_id, Controls::print_time, MP::printOn, Mesh::write_fields(), and Controls::write_interval.
start()
bool Iteration::start () inline
Definition at line 41 of file iteration.h.
The documentation for this class was generated from the following file:
/home/daniel/storage/NebulaSEM/src/solvers/iteration.h