NebulaSEM: BaseField Class Reference
BaseField Class Reference abstract
#include <field.h>
Public Member Functions
virtual void deallocate (bool)=0
virtual void refineField (Int, const IntVector &, const IntVector &, const IntVector &, const Int, const ScalarVector &, const VectorVector &, const VectorVector &)=0
virtual void writeInternal (std::ostream &, IntVector *)=0
virtual Int readInternal (std::istream &, Int=0)=0
virtual void writeBoundary (std::ostream &)=0
virtual void readBoundary (std::istream &)=0
virtual void read (std::istream &)=0
virtual void write (std::ostream &, IntVector *=0)=0
virtual void writeInternal (Util::ofstream_bin &, IntVector *)=0
virtual Int readInternal (Util::ifstream_bin &, Int=0)=0
virtual void writeBoundary (Util::ofstream_bin &)=0
virtual void readBoundary (Util::ifstream_bin &)=0
virtual void read (Util::ifstream_bin &)=0
virtual void write (Util::ofstream_bin &, IntVector *=0)=0
virtual void read (Int)=0
virtual void write (Int, IntVector *=0)=0
virtual void norm (BaseField *)=0
virtual ~BaseField ()
Static Public Member Functions
static void destroyFields ()
static BaseField * findField (const std::string &name)
Public Attributes
std::string fName
Static Public Attributes
static std::list< BaseField * > allFields
static std::vector< std::string > fieldNames
Detailed Description
Base field class
Definition at line 426 of file field.h.
Constructor & Destructor Documentation
~BaseField()
virtual BaseField::~BaseField () inline virtual
Definition at line 452 of file field.h.
Member Function Documentation
deallocate()
virtual void BaseField::deallocate (bool) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
destroyFields()
static void BaseField::destroyFields () inline static
Definition at line 456 of file field.h.
References copyColl, and forEachIt.
Referenced by Prepare::createFields(), and Prepare::decomposeMesh().
findField()
static BaseField* BaseField::findField (const std::string & name) inline static
Definition at line 462 of file field.h.
References Util::compare(), and forEachIt.
Referenced by Prepare::calcQOI(), and Prepare::decomposeMesh().
norm()
virtual void BaseField::norm (BaseField *) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
Referenced by Prepare::calcQOI().
read() [1/3]
virtual void BaseField::read (Int) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
read() [2/3]
virtual void BaseField::read (std::istream &) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
read() [3/3]
virtual void BaseField::read (Util::ifstream_bin &) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
readBoundary() [1/2]
virtual void BaseField::readBoundary (std::istream &) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
readBoundary() [2/2]
virtual void BaseField::readBoundary (Util::ifstream_bin &) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
readInternal() [1/2]
virtual Int BaseField::readInternal (std::istream & , Int = 0) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
readInternal() [2/2]
virtual Int BaseField::readInternal (Util::ifstream_bin & , Int = 0) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
refineField()
virtual void BaseField::refineField (Int , const IntVector & , const IntVector & , const IntVector & , const Int, const ScalarVector & , const VectorVector & , const VectorVector &) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
write() [1/3]
virtual void BaseField::write (Int , IntVector * = 0) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
write() [2/3]
virtual void BaseField::write (std::ostream & , IntVector * = 0) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
Referenced by Prepare::decomposeMesh().
write() [3/3]
virtual void BaseField::write (Util::ofstream_bin & , IntVector * = 0) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
writeBoundary() [1/2]
virtual void BaseField::writeBoundary (std::ostream &) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
writeBoundary() [2/2]
virtual void BaseField::writeBoundary (Util::ofstream_bin &) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
writeInternal() [1/2]
virtual void BaseField::writeInternal (std::ostream & , IntVector *) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
writeInternal() [2/2]
virtual void BaseField::writeInternal (Util::ofstream_bin & , IntVector *) pure virtual
Implemented in MeshField< type, entity >, MeshField< T1, CELL >, MeshField< Scalar, FACET >, MeshField< Scalar, CELL >, MeshField< T, CELL >, and MeshField< Scalar, CELLMAT >.
Member Data Documentation
allFields
std::list< BaseField * > BaseField::allFields static
Definition at line 454 of file field.h.
Referenced by Mesh::remove_fields().
fieldNames
std::vector< std::string > BaseField::fieldNames static
Definition at line 455 of file field.h.
Referenced by Prepare::decomposeMesh(), Prepare::mergeFields(), and Prepare::refineMesh().
fName
std::string BaseField::fName
Field name
Definition at line 428 of file field.h.
Referenced by Prepare::createFields(), Mesh::fixedBCs(), Mesh::initGeomMeshFields(), MeshField< type, entity >::initTimeSeries(), Mesh::scaleBCs(), Mesh::setNeumannBCs(), and MeshField< type, entity >::writeVtkCellAll().
The documentation for this class was generated from the following files:
/home/daniel/storage/NebulaSEM/src/field/field.h
/home/daniel/storage/NebulaSEM/src/field/field.cpp