NebulaSEM: AmrIteration Class Reference
AmrIteration Class Reference
#include <iteration.h>
Public Member Functions
AmrIteration ()
bool start ()
bool end ()
void next ()
~AmrIteration ()
int get_step ()
Detailed Description
Iterator for AMR
Definition at line 94 of file iteration.h.
Constructor & Destructor Documentation
AmrIteration()
AmrIteration::AmrIteration () inline
Definition at line 101 of file iteration.h.
References Controls::amr_step, Prepare::decomposeMesh(), Controls::end_step, Mesh::LoadMesh(), MP::n_hosts, Controls::start_step, and Controls::write_interval.
~AmrIteration()
AmrIteration::~AmrIteration () inline
Definition at line 141 of file iteration.h.
Member Function Documentation
end()
bool AmrIteration::end () inline
Definition at line 118 of file iteration.h.
get_step()
int AmrIteration::get_step () inline
Definition at line 143 of file iteration.h.
next()
void AmrIteration::next () inline
Definition at line 123 of file iteration.h.
References Controls::amr_step, System::cd(), Prepare::decomposeMesh(), MP::host_id, Mesh::LoadMesh(), Prepare::mergeFields(), MP::n_hosts, Prepare::refineMesh(), and MP::workingDir.
start()
bool AmrIteration::start () inline
Definition at line 115 of file iteration.h.
The documentation for this class was generated from the following file:
/home/daniel/storage/NebulaSEM/src/solvers/iteration.h