NebulaSEM: MP Class Reference
MP Class Reference
#include <mp.h>
Public Types
enum { FIELD , END , FIELD_BLK }
enum { OP_MAX , OP_MIN , OP_SUM , OP_PROD }
typedef MPI_Request REQUEST
Public Member Functions
MP (int argc, char *argv[])
~MP ()
Static Public Member Functions
static void cleanup ()
static void loop ()
static void barrier ()
static int iprobe (int &, int &, int)
static void send (int, int)
static void recieve (int, int)
static void printH (const char *format,...)
static void print (const char *format,...)
static bool hasElapsed (const Int)
template<class type >
static void recieve (type *buffer, int size, int source, int message_id)
template<class type >
static void send (type *buffer, int size, int source, int message_id)
template<class type >
static void allreduce (type *sendbuf, type *recvbuf, int size, Int op)
template<class type >
static void reduce (type *sendbuf, type *recvbuf, int size, Int op)
template<class type >
static void irecieve (type *buffer, int size, int source, int message_id, void *request)
template<class type >
static void isend (type *buffer, int size, int source, int message_id, void *request)
static void waitall (int count, void *request)
Static Public Attributes
static int n_hosts
static int host_id
static int name_len
static char host_name [MY_PATH_MAX+1]
static int _start_time = 0
static bool Terminated = false
static bool printOn = true
static char workingDir [MY_PATH_MAX+1]
Detailed Description
Class for multi-processor support via MPI
Definition at line 18 of file mp.h.
Member Typedef Documentation
REQUEST
typedef MPI_Request MP::REQUEST
Definition at line 37 of file mp.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Message types
Enumerator
FIELD
Field data marker
END
END of communicatins marker
FIELD_BLK
Field data marker when not in iteration
Definition at line 21 of file mp.h.
anonymous enum
anonymous enum
Global reduction types
Enumerator
OP_MAX
Global maximum
OP_MIN
Global minimum
OP_SUM
Global sum
OP_PROD
Global product
Definition at line 27 of file mp.h.
Constructor & Destructor Documentation
MP()
MP::MP (int argc, char * argv[])
Initialize MPI
Definition at line 17 of file mp.cpp.
References _start_time, System::get_pid(), System::get_time(), host_id, host_name, MY_PATH_MAX, n_hosts, name_len, System::pwd(), and workingDir.
~MP()
MP::~MP ()
Finalize MPI
Definition at line 33 of file mp.cpp.
Member Function Documentation
allreduce()
template<class type > static void MP::allreduce (type * sendbuf, type * recvbuf, int size, Int op) inline static
Definition at line 70 of file mp.h.
References MPI_SCALAR, OP_MAX, OP_MIN, OP_PROD, and OP_SUM.
Referenced by Mesh::calc_courant(), and getResidual().
barrier()
void MP::barrier () static
Barrier
Definition at line 48 of file mp.cpp.
Referenced by Prepare::decomposeMesh().
cleanup()
void MP::cleanup () static
Exit point
Definition at line 82 of file mp.cpp.
References _start_time, System::get_time(), host_id, n_hosts, and Terminated.
hasElapsed()
bool MP::hasElapsed (const Int delta) static
Check if certain amout of time is elapsed
Definition at line 90 of file mp.cpp.
References System::get_time().
Referenced by Iteration::next().
iprobe()
int MP::iprobe (int & source, int & message_id, int tag) static
Asynchronous probe for messages
Definition at line 53 of file mp.cpp.
Referenced by SolveT().
irecieve()
template<class type > static void MP::irecieve (type * buffer, int size, int source, int message_id, void * request) inline static
Definition at line 98 of file mp.h.
References MPI_SCALAR.
Referenced by ASYNC_COMM< T >::send().
isend()
template<class type > static void MP::isend (type * buffer, int size, int source, int message_id, void * request) inline static
Definition at line 105 of file mp.h.
References MPI_SCALAR.
Referenced by ASYNC_COMM< T >::send().
loop()
static void MP::loop () static
print()
void MP::print (const char * format, ...) static
Print without hearder
Definition at line 74 of file mp.cpp.
Referenced by SolveTexplicit().
printH()
void MP::printH (const char * format, ...) static
Print with hearder
Definition at line 65 of file mp.cpp.
References _start_time, System::get_time(), and host_id.
Referenced by Iteration::end(), Iteration::Iteration(), SolveT(), and SolveTexplicit().
recieve() [1/2]
void MP::recieve (int source, int message_id) static
Synchronous recieve
Definition at line 43 of file mp.cpp.
Referenced by SolveT().
recieve() [2/2]
template<class type > static void MP::recieve (type * buffer, int size, int source, int message_id) inline static
Definition at line 56 of file mp.h.
References MPI_SCALAR.
reduce()
template<class type > static void MP::reduce (type * sendbuf, type * recvbuf, int size, Int op) inline static
Definition at line 84 of file mp.h.
References MPI_SCALAR, OP_MAX, OP_MIN, OP_PROD, and OP_SUM.
send() [1/2]
void MP::send (int source, int message_id) static
Synchronous seend
Definition at line 38 of file mp.cpp.
Referenced by SolveT().
send() [2/2]
template<class type > static void MP::send (type * buffer, int size, int source, int message_id) inline static
Definition at line 63 of file mp.h.
References MPI_SCALAR.
waitall()
static void MP::waitall (int count, void * request) inline static
Definition at line 111 of file mp.h.
Referenced by ASYNC_COMM< T >::recv().
Member Data Documentation
_start_time
int MP::_start_time = 0 static
Definition at line 41 of file mp.h.
Referenced by cleanup(), MP(), and printH().
host_id
int MP::host_id static
Definition at line 39 of file mp.h.
Referenced by cleanup(), Prepare::decomposeMesh(), MP(), Iteration::next(), AmrIteration::next(), and printH().
host_name
char MP::host_name static
Definition at line 40 of file mp.h.
Referenced by MP().
n_hosts
int MP::n_hosts static
Definition at line 39 of file mp.h.
Referenced by AmrIteration::AmrIteration(), Mesh::calc_courant(), cleanup(), Prepare::decomposeMesh(), Prepare::mergeFields(), MP(), and AmrIteration::next().
name_len
int MP::name_len static
Definition at line 39 of file mp.h.
Referenced by MP().
printOn
bool MP::printOn = true static
Definition at line 43 of file mp.h.
Referenced by Iteration::end(), Iteration::Iteration(), Iteration::next(), MeshField< type, entity >::read(), SolveT(), and SolveTexplicit().
Terminated
bool MP::Terminated = false static
Definition at line 42 of file mp.h.
Referenced by cleanup(), and MeshField< type, entity >::~MeshField().
workingDir
char MP::workingDir static
Definition at line 44 of file mp.h.
Referenced by MP(), and AmrIteration::next().
The documentation for this class was generated from the following files:
/home/daniel/storage/NebulaSEM/src/mp/mp.h
/home/daniel/storage/NebulaSEM/src/mp/mp.cpp