NebulaSEM: /home/daniel/storage/NebulaSEM/src/field/field.h File Reference
field.h File Reference
#include "mesh.h"
#include "mp.h"
#include "system.h"
#include "dg.h"
Classes
struct RefineParams
struct DecomposeParams
struct LawOfWall
struct BasicBCondition
struct BCondition< type >
class BaseField
class MeshField< type, entity >
struct MeshMatrix< T1, T2, T3 >
class ASYNC_COMM< T >
Namespaces
Mesh
Controls
DG
Prepare
Macros
#define Op()
#define SOp()
#define Op()
#define MUL()
#define MUL()
#define MUL()
#define GRADD(im, jm, km)
#define DIVD(im, jm, km)
#define DIVD(im, jm, km)
#define H(in, jn, kn)
#define LAPD(im, jm, km)
Unary operations
#define DEFINE_UNARY_TOP_PART1_A(DApOpp, func, type, rtype)
#define DEFINE_UNARY_TOP_PART1_B(DApOpp, , type, rtype)
#define DEFINE_UNARY_TOP_PART2(DApOpp, func, type, rtype)
#define DEFINE_UNARY_OP(x, func, type)
#define DEFINE_UNARY_OP2(x, , func, type)
#define DEFINE_UNARY_SOP(x, func, type, rtype)
Binary operations
#define DEFINE_BINARY_TOP_PART1_A(DApOpp, , func, type1, type2, rtype)
#define DEFINE_BINARY_TOP_PART1_B(DApOpp, , func, type1, type2, rtype)
#define DEFINE_BINARY_TOP_PART2(DApOpp, , func, type1, type2, rtype)
#define DEFINE_BINARY_OP(x, , func, type)
#define DEFINE_BINARY_OP2(x, func, type)
#define DEFINE_BINARY_OP_A(x, , func, type, rtype)
#define DEFINE_BINARY_OP2_A(x, func, type, rtype)
Binary operations with Scalar
#define DEFINE_BINARY_TSOP_PART2_I(DApOpp, , func, type, type2)
#define DEFINE_BINARY_TSOP_PART2_II(DApOpp, , func, type, type2)
#define DEFINE_BINARY_SOP(x, , func, type, type2)
#define DEFINE_BINARY_SOP2(x, func, type, type2)
Binary operations of mixed tensor types
#define DEFINE_BINARY_TOP_PART1_C(DApOpp, , func, type1, type2, rtype)
#define DEFINE_BINARY_TOP_PART1_D(DApOpp, , func, type1, type2, rtype)
#define DEFINE_BINARY_TOP_PART3(DApOpp, , func, type1, type2, rtype)
#define DEFINE_BINARY_OP_O(x, , func, type1, type2, rtype)
#define DEFINE_BINARY_OP2_O(x, func, type1, type2, rtype)
#define forEachCellField(X)
#define forEachFacetField(X)
#define forEachVertexField(X)
#define forEachCellMatField(X)
Typedefs
Typedef common mesh field types
typedef MeshField< Int, CELL > IntCellField
typedef MeshField< Int, FACET > IntFacetField
typedef MeshField< Int, VERTEX > IntVertexField
typedef MeshField< Scalar, CELL > ScalarCellField
typedef MeshField< Scalar, FACET > ScalarFacetField
typedef MeshField< Scalar, VERTEX > ScalarVertexField
typedef MeshField< Vector, CELL > VectorCellField
typedef MeshField< Vector, FACET > VectorFacetField
typedef MeshField< Vector, VERTEX > VectorVertexField
typedef MeshField< Tensor, CELL > TensorCellField
typedef MeshField< Tensor, FACET > TensorFacetField
typedef MeshField< Tensor, VERTEX > TensorVertexField
typedef MeshField< STensor, CELL > STensorCellField
typedef MeshField< STensor, FACET > STensorFacetField
typedef MeshField< STensor, VERTEX > STensorVertexField
typedef MeshField< Scalar, CELLMAT > ScalarCellMatField
Enumerations
enum ENTITY { CELL , FACET , VERTEX , CELLMAT }
enum Controls::FILE_FORMAT { Controls::TEXT = 0 , Controls::BINARY = 1 }
enum Controls::Scheme {
Controls::CDS , Controls::UDS , Controls::BLENDED , Controls::HYBRID ,
Controls::RUSANOV , Controls::LUD , Controls::CDSS , Controls::MUSCL ,
Controls::QUICK , Controls::VANLEER , Controls::VANALBADA , Controls::MINMOD ,
Controls::SUPERBEE , Controls::SWEBY , Controls::QUICKL , Controls::UMIST ,
Controls::DDS , Controls::FROMM
}
enum Controls::NonOrthoScheme { Controls::NONE , Controls::MINIMUM , Controls::ORTHOGONAL , Controls::OVER_RELAXED }
enum Controls::TimeScheme {
Controls::BDF1 , Controls::BDF2 , Controls::BDF3 , Controls::BDF4 ,
Controls::BDF5 , Controls::BDF6 , Controls::AM1 , Controls::AM2 ,
Controls::AM3 , Controls::AM4 , Controls::AM5 , Controls::AB1 ,
Controls::AB2 , Controls::AB3 , Controls::AB4 , Controls::AB5 ,
Controls::RK1 , Controls::RK2 , Controls::RK3 , Controls::RK4
}
enum Controls::Solvers { Controls::JACOBI , Controls::SOR , Controls::PCG }
enum Controls::Preconditioners { Controls::NOPR , Controls::DIAG , Controls::SSOR , Controls::DILU }
enum Controls::CommMethod { Controls::BLOCKED , Controls::ASYNCHRONOUS }
enum Controls::State { Controls::STEADY , Controls::TRANSIENT }
enum ACCESS {
NO = 0 , READ = 1 , WRITE = 2 , READWRITE = 3 ,
STOREPREV = 4
}
Functions
void Mesh::enroll (Util::ParamList &params)
void Controls::enrollRefine (Util::ParamList &params)
void Controls::enrollDecompose (Util::ParamList &params)
void Mesh::clearBC ()
bool Mesh::LoadMesh (Int=0, bool=true, bool extrude=true)
void Mesh::initGeomMeshFields (bool)
void Mesh::write_fields (Int)
void Mesh::read_fields (Int)
void Mesh::remove_fields ()
Int Mesh::findNearestCell (const Vector &v)
Int Mesh::findNearestFace (const Vector &v)
void Mesh::getProbeCells (IntVector &)
void Mesh::getProbeFaces (IntVector &)
Vector Mesh::calc_courant (const VectorCellField &U, Scalar dt)
void Prepare::createFields (std::vector< std::string > &fields, Int step)
void Prepare::readFields (std::vector< std::string > &fields, Int step)
void Prepare::refineMesh (Int step)
void Prepare::calcQOI (ScalarCellField &)
int Prepare::decomposeMesh (Int)
int Prepare::mergeFields (Int)
int Prepare::writeCoords (Int)
Variables
constexpr bool form_strong = false
const Int Mesh::DIRICHLET = Util::hash_function("DIRICHLET")
const Int Mesh::NEUMANN = Util::hash_function("NEUMANN")
const Int Mesh::ROBIN = Util::hash_function("ROBIN")
const Int Mesh::SYMMETRY = Util::hash_function("SYMMETRY")
const Int Mesh::CYCLIC = Util::hash_function("CYCLIC")
const Int Mesh::GHOST = Util::hash_function("GHOST")
const Int Mesh::POWER = Util::hash_function("POWER")
const Int Mesh::LOG = Util::hash_function("LOG")
const Int Mesh::PARABOLIC = Util::hash_function("PARABOLIC")
const Int Mesh::INVERSE = Util::hash_function("INVERSE")
const Int Mesh::ROUGHWALL = Util::hash_function("ROUGHWALL")
const Int Mesh::CALC_DIRICHLET = Util::hash_function("CALC_DIRICHLET")
const Int Mesh::CALC_NEUMANN = Util::hash_function("CALC_NEUMANN")
Expression template operators
#define ScaMul(T,)
operator*,Scalar, Scalar, Scalar)
DEFINE_UNARY_OP (oacos, acos, type)
DEFINE_UNARY_OP (oasin, asin, type)
DEFINE_UNARY_OP (oatan, atan, type)
DEFINE_UNARY_OP (oceil, ceil, type)
DEFINE_UNARY_OP (ocos, cos, type)
DEFINE_UNARY_OP (ocosh, cosh, type)
DEFINE_UNARY_OP (oexp, exp, type)
DEFINE_UNARY_OP (ofabs, fabs, type)
DEFINE_UNARY_OP (ofloor, floor, type)
DEFINE_UNARY_OP (olog, log, type)
DEFINE_UNARY_OP (olog10, log10, type)
DEFINE_UNARY_OP (osin, sin, type)
DEFINE_UNARY_OP (osinh, sinh, type)
DEFINE_UNARY_OP (osqrt, sqrt, type)
DEFINE_UNARY_OP (otan, tan, type)
DEFINE_UNARY_OP (otanh, tanh, type)
DEFINE_UNARY_OP (otrn, trn, Tensor)
DEFINE_UNARY_OP (oskw, skw, Tensor)
DEFINE_UNARY_OP (ounit, unit, type)
DEFINE_UNARY_OP2 (oneg,-, operator-,type)
DEFINE_UNARY_SOP (omag, mag, type, Scalar)
DEFINE_UNARY_SOP (omagSq, magSq, type, Scalar)
DEFINE_BINARY_OP (oadd,+, operator+,type)
DEFINE_BINARY_OP (osub,-, operator-,type)
DEFINE_BINARY_OP (omul, *, operator*,type)
DEFINE_BINARY_OP (odiv,/, operator/,type)
DEFINE_BINARY_OP2 (oatan2, atan2, type)
DEFINE_BINARY_OP2 (omin, min, type)
DEFINE_BINARY_OP2 (omax, max, type)
DEFINE_BINARY_OP2 (ossdiv, sdiv, type)
DEFINE_BINARY_SOP (osadd,+, operator+,type, Scalar)
DEFINE_BINARY_SOP (ossub,-, operator-,type, Scalar)
DEFINE_BINARY_SOP (osmul, *, operator*,type, Scalar)
DEFINE_BINARY_SOP (osdiv,/, operator/,type, Scalar)
DEFINE_BINARY_SOP2 (opow, pow, type, Scalar)
DEFINE_BINARY_SOP2 (odev, dev, type, Scalar)
DEFINE_BINARY_SOP2 (ohyd, hyd, type, Scalar)
DEFINE_BINARY_SOP2 (omins, min, type, type)
DEFINE_BINARY_SOP2 (omaxs, max, type, type)
ScaMul (Vector, 1) ScaMul(Tensor
ScaMul (STensor, 3) DEFINE_BINARY_OP_O(omula
DEFINE_BINARY_OP_O (omulb, *, operator*,Vector, Vector, Vector)
DEFINE_BINARY_OP_O (omulc, *, operator*,Tensor, Tensor, Tensor)
DEFINE_BINARY_OP_O (omuld, *, operator*,STensor, STensor, STensor)
template<typename T , ENTITY E>
auto eval_expr (const MeshField< T, E > &f)
Typedef common matrix types
#define TensorProduct_(Q, P, tr,)
#define TensorProduct(Q, P) TensorProduct_(Q,P,false,-=)
#define TensorProductT(Q, P) TensorProduct_(Q,P,true,-=)
#define TensorProductM(Q, P) TensorProduct_(Q,P,false,+=)
#define srci(x) (x)
#define PREV(k) (M.cF->tstore[k])
#define cFR(k) (rho0 ? ((*M.cF) * (*rho0)) : (*M.cF))
typedef MeshMatrix< Scalar > ScalarCellMatrix
typedef MeshMatrix< Vector > VectorCellMatrix
typedef MeshMatrix< Tensor > TensorCellMatrix
typedef MeshMatrix< STensor > STensorCellMatrix
template<class type >
void Mesh::scaleBCs (const MeshField< type, CELL > &, MeshField< type, CELL > &, Scalar)
template<class type >
void Mesh::fixedBCs (const MeshField< type, CELL > &, MeshField< type, CELL > &)
template<class type >
void Mesh::setNeumannBCs (MeshField< type, CELL > &)
template<class type >
void gather_non_conforming (const MeshField< type, FACET > &fF, MeshField< type, FACET > &fFO, MeshField< type, FACET > &fFN)
template<class type >
void scatter_non_conforming (const MeshField< type, CELL > &cF, MeshField< type, FACET > &fFO, MeshField< type, FACET > &fFN)
template<class T1 , class T2 , class T3 >
auto mul (const MeshMatrix< T1, T2, T3 > &p, const MeshField< T1, CELL > &q, const bool sync=false)
template<class T1 , class T2 , class T3 >
auto mult (const MeshMatrix< T1, T2, T3 > &p, const MeshField< T1, CELL > &q, const bool sync=false)
template<class T1 , class T2 , class T3 >
auto getRHS (const MeshMatrix< T1, T2, T3 > &p, const MeshField< T1, CELL > &q, const bool sync=false)
template<class T1 , class T2 , class T3 >
void applyImplicitBCs (const MeshMatrix< T1, T2, T3 > &M)
template<class T , ENTITY E>
void applyExplicitBCs (const MeshField< T, E > &cF, bool update_ghost=false)
template<class T >
void fillBCs (MeshField< T, CELL > &cF, Int bind=0, bool sync=false)
template<class type >
auto cds (const MeshField< type, CELL > &cF)
template<class type , class T3 >
auto uds (const MeshField< type, CELL > &cF, const MeshField< T3, FACET > &flux)
template<typename T1 , typename T2 >
auto rusanov (const MeshField< T1, CELL > &F, const MeshField< T2, CELL > &q, const ScalarFacetField &lambdaMax)
template<class type >
auto cds (const MeshField< type, FACET > &fF)
template<class type >
auto sum (const MeshField< type, FACET > &fF)
template<bool strong = form_strong, class type , class type2 >
auto sum_flux (const MeshField< type, CELL > &p, const MeshField< type, FACET > &fF, const MeshField< type2, FACET > &flux)
template<bool strong = form_strong, class type >
auto grad_flux (const MeshField< type, CELL > &p, const MeshField< type, FACET > &fF)
template<bool strong = form_strong, class type >
auto div_flux (const MeshField< type, CELL > &p, const MeshField< type, FACET > &fF)
template<bool strong = form_strong, class T1 , class T2 , class T3 , class T4 , class T5 >
void div_flux_implicit (MeshMatrix< T1, T2, T3 > &m, const MeshField< T5, CELL > &p, const VectorCellField &fluxc, const MeshField< T4, FACET > &flux, const ScalarFacetField *lambdaMax=0, const MeshField< T4, CELL > *muc=0)
template<bool strong = form_strong, typename T1 >
auto gradf (const MeshField< T1, CELL > &p, bool perunit_volume=false)
template<typename T >
auto flxc (const MeshField< T, CELL > &p)
template<typename type >
auto flx (const MeshField< type, CELL > &p)
template<bool strong = form_strong, typename T1 , typename T2 >
auto divf (const MeshField< T1, CELL > &p, bool perunit_volume=false, const ScalarFacetField *flux=0, const MeshField< T2, CELL > *q=0, const ScalarFacetField *lambdaMax=0)
template<bool strong = form_strong, class type >
auto div (MeshField< type, CELL > &cF, const VectorCellField &fluxc, const ScalarFacetField &flux, const ScalarFacetField *lambdaMax=0, const ScalarCellField *muc=0)
template<bool strong = form_strong, class type >
auto lap (MeshField< type, CELL > &cF, const ScalarCellField &muc, const bool penalty=false)
template<class T1 , class T2 , class T3 >
auto src (MeshField< T1, CELL > &cF, const MeshField< T3, CELL > &Su, const MeshField< T2, CELL > &Sp)
template<class type >
auto srcf (const MeshField< type, CELL > &Su)
template<class type >
auto ddt (MeshMatrix< type > &M, const MeshField< type, CELL > &rhs, ScalarCellField *rho, ScalarCellField *rho0)
template<class type >
auto ddt2 (MeshMatrix< type > &M, const MeshField< type, CELL > &rhs, ScalarCellField *rho, ScalarCellField *rho0)
template<int order, class type >
void addTemporal (MeshMatrix< type > &M, Scalar cF_UR, ScalarCellField *rho=0, ScalarCellField *rho0=0)
template<class type >
auto diffusion (MeshField< type, CELL > &cF, const ScalarCellField &mu, Scalar cF_UR, ScalarCellField *rho=0, ScalarCellField *rho0=0)
template<class type >
auto diffusion (MeshField< type, CELL > &cF, const ScalarCellField &mu, Scalar cF_UR, const MeshField< type, CELL > &Su, const ScalarCellField &Sp, ScalarCellField *rho=0, ScalarCellField *rho0=0)
template<class type >
auto convection (MeshField< type, CELL > &cF, const VectorCellField &Fc, const ScalarFacetField &F, Scalar cF_UR, const ScalarFacetField *lambdaMax=0, ScalarCellField *rho=0, ScalarCellField *rho0=0)
template<class type >
auto convection (MeshField< type, CELL > &cF, const VectorCellField &Fc, const ScalarFacetField &F, Scalar cF_UR, const MeshField< type, CELL > &Su, const ScalarCellField &Sp, const ScalarFacetField *lambdaMax=0, ScalarCellField *rho=0, ScalarCellField *rho0=0)
template<class type >
auto transport (MeshField< type, CELL > &cF, const VectorCellField &Fc, const ScalarFacetField &F, const ScalarCellField &mu, Scalar cF_UR, const ScalarFacetField *lambdaMax=0, ScalarCellField *rho=0, ScalarCellField *rho0=0)
template<class type >
auto transport (MeshField< type, CELL > &cF, const VectorCellField &Fc, const ScalarFacetField &F, const ScalarCellField &mu, Scalar cF_UR, const MeshField< type, CELL > &Su, const ScalarCellField &Sp, const ScalarFacetField *lambdaMax=0, ScalarCellField *rho=0, ScalarCellField *rho0=0)
Macro Definition Documentation
cFR
#define cFR (k) (rho0 ? ((*M.cF) * (*rho0)) : (*M.cF))
Definition at line 3685 of file field.h.
DEFINE_BINARY_OP
#define DEFINE_BINARY_OP (x, func, type)
Value:
    DEFINE_BINARY_TOP_PART1_A(x,$,func,type,type,type)                          \
    DEFINE_BINARY_TOP_PART2(x<type>,$,func,type,type,type)
Definition at line 554 of file field.h.
DEFINE_BINARY_OP2
#define DEFINE_BINARY_OP2 (x, func, type)
Value:
    DEFINE_BINARY_TOP_PART1_B(x,$,func,type,type,type)                          \
    DEFINE_BINARY_TOP_PART2(x<type>,$,func,type,type,type)
Definition at line 558 of file field.h.
DEFINE_BINARY_OP2_A
#define DEFINE_BINARY_OP2_A (x, func, type, rtype)
Value:
    DEFINE_BINARY_TOP_PART1_B(x,$,func,type,type,rtype)                         \
    DEFINE_BINARY_TOP_PART2(x<type>,$,func,type,type,rtype)
Definition at line 566 of file field.h.
DEFINE_BINARY_OP2_O
#define DEFINE_BINARY_OP2_O (x, func, type1, type2, rtype)
Value:
    DEFINE_BINARY_TOP_PART1_D(x,$,func,type1,type2,rtype)                       \
    DEFINE_BINARY_TOP_PART3(x,$,func,type1,type2,rtype)
Definition at line 659 of file field.h.
DEFINE_BINARY_OP_A
#define DEFINE_BINARY_OP_A (x, func, type, rtype)
Value:
    DEFINE_BINARY_TOP_PART1_A(x,$,func,type,type,rtype)                         \
    DEFINE_BINARY_TOP_PART2(x<type>,$,func,type,type,rtype)
Definition at line 562 of file field.h.
DEFINE_BINARY_OP_O
#define DEFINE_BINARY_OP_O (x, func, type1, type2, rtype)
Value:
    DEFINE_BINARY_TOP_PART1_C(x,$,func,type1,type2,rtype)                       \
    DEFINE_BINARY_TOP_PART3(x,$,func,type1,type2,rtype)
Definition at line 655 of file field.h.
DEFINE_BINARY_SOP
#define DEFINE_BINARY_SOP (x, func, type, type2)
Value:
    DEFINE_BINARY_TOP_PART1_A(x,$,func,type,type2,type)                         \
    DEFINE_BINARY_TSOP_PART2_I(x<type>,$,func,type,type2)                       \
    DEFINE_BINARY_TOP_PART1_A(x##Inv,$,func,type2,type,type)                    \
    DEFINE_BINARY_TSOP_PART2_II(x##Inv<type>,$,func,type,type2)
Definition at line 609 of file field.h.
DEFINE_BINARY_SOP2
#define DEFINE_BINARY_SOP2 (x, func, type, type2)
Value:
    DEFINE_BINARY_TOP_PART1_B(x,$,func,type,type2,type)                         \
    DEFINE_BINARY_TSOP_PART2_I(x<type>,$,func,type,type2)                       \
    DEFINE_BINARY_TOP_PART1_B(x##Inv,$,func,type2,type,type)                    \
    DEFINE_BINARY_TSOP_PART2_II(x##Inv<type>,$,func,type,type2)
Definition at line 615 of file field.h.
DEFINE_BINARY_TOP_PART1_A
#define DEFINE_BINARY_TOP_PART1_A (DApOpp, func, type1, type2, rtype)
Value:
    template<class type>                                                        \
    struct DApOpp {                                                             \
        static FORCEINLINE rtype apply(type1 a, type2 b)                        \
        { return (a $ b); }                                                     \
    };
Definition at line 521 of file field.h.
DEFINE_BINARY_TOP_PART1_B
#define DEFINE_BINARY_TOP_PART1_B (DApOpp, func, type1, type2, rtype)
Value:
    template<class type>                                                        \
    struct DApOpp {                                                             \
        static FORCEINLINE rtype apply(type1 a, type2 b)                        \
        { return func(a, b); }                                                  \
    };
Definition at line 527 of file field.h.
DEFINE_BINARY_TOP_PART1_C
#define DEFINE_BINARY_TOP_PART1_C (DApOpp, func, type1, type2, rtype)
Value:
    struct DApOpp {                                                             \
        static FORCEINLINE rtype apply(type1 a, type2 b)                        \
        { return (a $ b); }                                                     \
    };
Definition at line 624 of file field.h.
DEFINE_BINARY_TOP_PART1_D
#define DEFINE_BINARY_TOP_PART1_D (DApOpp, func, type1, type2, rtype)
Value:
    struct DApOpp {                                                             \
        static FORCEINLINE rtype apply(type1 a, type2 b)                        \
        { return func(a, b); }                                                  \
    };
Definition at line 629 of file field.h.
DEFINE_BINARY_TOP_PART2
#define DEFINE_BINARY_TOP_PART2 (DApOpp, func, type1, type2, rtype)
Value:
    template<class type, ENTITY A, ENTITY B>                                    \
    auto func(const MeshField<type1,A>& a, const MeshField<type2,B>& b) {       \
        MeshField<rtype,A> r;                                                   \
        _Pragma("omp parallel for")                                             \
        _Pragma("acc parallel loop copyin(a,b)")                                \
        forEach(r,i)                                                            \
            r[i] = DApOpp::apply(a[i], b[i]);                                   \
        return r;                                                               \
    }
Definition at line 542 of file field.h.
DEFINE_BINARY_TOP_PART3
#define DEFINE_BINARY_TOP_PART3 (DApOpp, func, type1, type2, rtype)
Value:
    template<ENTITY A, ENTITY B>                                                \
    auto func(const MeshField<type1,A>& a, const MeshField<type2,B>& b) {       \
        MeshField<rtype,A> r;                                                   \
        _Pragma("omp parallel for")                                             \
        _Pragma("acc parallel loop copyin(a,b)")                                \
        forEach(r,i)                                                            \
            r[i] = DApOpp::apply(a[i], b[i]);                                   \
        return r;                                                               \
    }
Definition at line 643 of file field.h.
DEFINE_BINARY_TSOP_PART2_I
#define DEFINE_BINARY_TSOP_PART2_I (DApOpp, func, type, type2)
Value:
    template<class type,ENTITY A>                                               \
    auto func(const MeshField<type,A>& a, const type2& b) {                     \
        MeshField<type,A> r;                                                    \
        _Pragma("omp parallel for")                                             \
        _Pragma("acc parallel loop copyin(a)")                                  \
        forEach(r,i)                                                            \
            r[i] = DApOpp::apply(a[i], b);                                      \
        return r;                                                               \
    }
Definition at line 587 of file field.h.
DEFINE_BINARY_TSOP_PART2_II
#define DEFINE_BINARY_TSOP_PART2_II (DApOpp, func, type, type2)
Value:
    template<class type,ENTITY A>                                               \
    auto func(const type2& a, const MeshField<type,A>& b) {                     \
        MeshField<type,A> r;                                                    \
        _Pragma("omp parallel for")                                             \
        _Pragma("acc parallel loop copyin(b)")                                  \
        forEach(r,i)                                                            \
            r[i] = DApOpp::apply(a, b[i]);                                      \
        return r;                                                               \
    }
Definition at line 597 of file field.h.
DEFINE_UNARY_OP
#define DEFINE_UNARY_OP (x, func, type)
Value:
    DEFINE_UNARY_TOP_PART1_A(x,func,type,type)                                  \
    DEFINE_UNARY_TOP_PART2(x<type>,func,type,type)
Definition at line 506 of file field.h.
DEFINE_UNARY_OP2
#define DEFINE_UNARY_OP2 (x, func, type)
Value:
    DEFINE_UNARY_TOP_PART1_B(x,$,type,type)                                     \
    DEFINE_UNARY_TOP_PART2(x<type>,func,type,type)
Definition at line 510 of file field.h.
DEFINE_UNARY_SOP
#define DEFINE_UNARY_SOP (x, func, type, rtype)
Value:
    DEFINE_UNARY_TOP_PART1_A(x,func,type,rtype)                                 \
    DEFINE_UNARY_TOP_PART2(x<type>,func,type,rtype)
Definition at line 514 of file field.h.
DEFINE_UNARY_TOP_PART1_A
#define DEFINE_UNARY_TOP_PART1_A (DApOpp, func, type, rtype)
Value:
    template<class type>                                                        \
    struct DApOpp {                                                             \
        static FORCEINLINE rtype apply(type a)                                  \
        { return func(a); }                                                     \
    };
Definition at line 473 of file field.h.
DEFINE_UNARY_TOP_PART1_B
#define DEFINE_UNARY_TOP_PART1_B (DApOpp, type, rtype)
Value:
    template<class type>                                                        \
    struct DApOpp {                                                             \
        static FORCEINLINE rtype apply(type a)                                  \
        { return ($ a); }                                                       \
    };
Definition at line 479 of file field.h.
DEFINE_UNARY_TOP_PART2
#define DEFINE_UNARY_TOP_PART2 (DApOpp, func, type, rtype)
Value:
    template<class type, ENTITY A>                                              \
    auto func(const MeshField<type,A>& a) {                                     \
        MeshField<rtype,A> r;                                                   \
        _Pragma("omp parallel for")                                             \
        _Pragma("acc parallel loop copyin(a)")                                  \
        forEach(r,i)                                                            \
            r[i] = DApOpp::apply(a[i]);                                         \
        return r;                                                               \
    }
Definition at line 494 of file field.h.
DIVD [1/2]
#define DIVD (im, jm, km)
Value:
    {                            \
    Int index1 = INDEX4(ci,im,jm,km);               \
    Vector dpsi_ij;                                 \
    DPSI(dpsi_ij,im,jm,km);                         \
    dpsi_ij = dot(Jin,dpsi_ij);                     \
    if(strong)                                      \
        r[index] += dot(p[index1],dpsi_ij);         \
    else                                            \
        r[index1] -= dot(p[index],dpsi_ij);         \
}
DIVD [2/2]
#define DIVD (im, jm, km)
Value:
    {                                    \
    Int index1 = INDEX4(ci,im,jm,km);                       \
    Vector dpsi_ij;                                         \
    DPSI(dpsi_ij,im,jm,km);                                 \
    dpsi_ij = dot(Jin,dpsi_ij);                             \
    Scalar val;                                             \
    if(strong)                                              \
        val = +dot(fluxc[index1],dpsi_ij);                  \
    else                                                    \
        val = -dot(fluxc[index],dpsi_ij);                   \
    if(index == index1) {                                   \
        m.ap[index] = -val;                                 \
    } else {                                                \
        m.adg[indexm] = val;                                \
    }                                                       \
}
forEachCellField
#define forEachCellField (X)
Value:
    {      \
    ScalarCellField::X;             \
    VectorCellField::X;             \
    STensorCellField::X;            \
    TensorCellField::X;             \
}
Definition at line 1160 of file field.h.
forEachCellMatField
#define forEachCellMatField (X)
Value:
    { \
    ScalarCellMatField::X;          \
}
Definition at line 1178 of file field.h.
forEachFacetField
#define forEachFacetField (X)
Value:
    {  \
    ScalarFacetField::X;            \
    VectorFacetField::X;            \
    STensorFacetField::X;           \
    TensorFacetField::X;            \
}
Definition at line 1166 of file field.h.
forEachVertexField
#define forEachVertexField (X)
Value:
    {  \
    ScalarVertexField::X;           \
    VectorVertexField::X;           \
    STensorVertexField::X;          \
    TensorVertexField::X;           \
}
Definition at line 1172 of file field.h.
GRADD
#define GRADD (im, jm, km)
Value:
    {                           \
    Int index1 = INDEX4(ci,im,jm,km);               \
    Vector dpsi_ij;                                 \
    DPSI(dpsi_ij,im,jm,km);                         \
    dpsi_ij = dot(Jin,dpsi_ij);                     \
    if(strong)                                      \
        r[index] += mul(dpsi_ij,p[index1]);         \
    else                                            \
        r[index1] -= mul(dpsi_ij,p[index]);         \
}
H
#define H (in, jn, kn)
Value:
    {                               \
    Int index2 = INDEX4(ci,in,jn,kn);               \
    Vector dpsi_jk;                                 \
    DPSI(dpsi_jk,in,jn,kn);                         \
    dpsi_jk = dot(Jin,dpsi_jk);                     \
    Scalar val;                                     \
    if(strong)                                      \
        val  = dot(dpsi_ik,dpsi_jk);                \
    else                                            \
        val  = -dot(dpsi_ik,dpsi_jk);               \
    if(index1 == index2) {                          \
        m.ap[index1] += -val;                       \
    } else {                                        \
        m.adg[indexm]  += val;                      \
        m.adg[indexmt] += val;                      \
    }                                               \
}
LAPD
#define LAPD (im, jm, km)
Value:
    {                                    \
    Int index1 = INDEX4(ci,im,jm,km);                       \
    Vector dpsi_ik,dp1;                                     \
    DPSI(dpsi_ik,im,jm,km);                                 \
    dpsi_ik = dot(Jin,dpsi_ik) * cV[index] * muc[index];    \
    forEachLglX(i2) if(i2 >= im) {                          \
        Int indexm  = ci * NPMAT + INDEX_TX(im,jm,km,i2);   \
        Int indexmt = ci * NPMAT + INDEX_X(im,jm,km,i2);    \
        H(i2,jm,km);                                        \
    }                                                       \
    forEachLglY(j2) if(j2 > jm) {                           \
        Int indexm  = ci * NPMAT + INDEX_TY(im,jm,km,j2);   \
        Int indexmt = ci * NPMAT + INDEX_Y(im,jm,km,j2);    \
        H(im,j2,km);                                        \
    }                                                       \
    forEachLglZ(k2) if(k2 > km) {                           \
        Int indexm  = ci * NPMAT + INDEX_TZ(im,jm,km,k2);   \
        Int indexmt = ci * NPMAT + INDEX_Z(im,jm,km,k2);    \
        H(im,jm,k2);                                        \
    }                                                       \
}
MUL [1/3]
#define MUL ()
Value:
    {                                                     \
    for(Int f = faceIndices[0][i]; f < faceIndices[1][i]; f++) {    \
        for(Int n = 0; n < DG::NPF; n++) {                          \
            Int k = allFaces[f] * DG::NPF + n;                      \
            Int c1 = FO[k];                                         \
            Int c2 = FN[k];                                         \
            if(c1 >= i * DG::NP && c1 < (i + 1) * DG::NP)           \
                r[c1] -= q[c2] * p.ann[k];                          \
            else if(c2 < gALLfield)                                 \
                r[c2] -= q[c1] * p.ano[k];                          \
        }                                                           \
    }                                                               \
}
MUL [2/3]
#define MUL ()
Value:
    {                                                     \
    for(Int f = faceIndices[0][i]; f < faceIndices[1][i]; f++) {    \
        for(Int n = 0; n < DG::NPF; n++) {                          \
            Int k = allFaces[f] * DG::NPF + n;                      \
            Int c1 = FO[k];                                         \
            Int c2 = FN[k];                                         \
            if(c1 >= i * DG::NP && c1 < (i + 1) * DG::NP)           \
                r[c1] -= q[c2] * p.ano[k];                          \
            else if(c2 < gALLfield)                                 \
                r[c2] -= q[c1] * p.ann[k];                          \
        }                                                           \
    }                                                               \
}
MUL [3/3]
#define MUL ()
Value:
    {                                                     \
    for(Int f = faceIndices[0][i]; f < faceIndices[1][i]; f++) {    \
        for(Int n = 0; n < DG::NPF; n++) {                          \
            Int k = allFaces[f] * DG::NPF + n;                      \
            Int c1 = FO[k];                                         \
            Int c2 = FN[k];                                         \
            if(c1 >= i * DG::NP && c1 < (i + 1) * DG::NP)           \
                r[c1] += q[c2] * p.ann[k];                          \
            else if(c2 < gALLfield)                                 \
                r[c2] += q[c1] * p.ano[k];                          \
        }                                                           \
    }                                                               \
}
Op [1/2]
#define Op ()
Value:
        MeshField& operator $(const MeshField& q) {                     \
            _Pragma("omp parallel for")                                 \
            _Pragma("acc parallel loop copyin(q)")                      \
            forEach(*this,i)                                            \
                P[i] $ q[i];                                            \
            return *this;                                               \
        }
Definition at line 875 of file field.h.
Op [2/2]
#define Op ()
Value:
        template <ENTITY E>                                             \
        MeshField& operator $(const MeshField<type,E>& q) {             \
            _Pragma("omp parallel for")                                 \
            _Pragma("acc parallel loop copyin(q)")                      \
            forEach(*this,i)                                            \
                P[i] $ q[i];                                            \
            return *this;                                               \
        }
Definition at line 875 of file field.h.
PREV
#define PREV (k) (M.cF->tstore[k])
Definition at line 3684 of file field.h.
ScaMul
#define ScaMul (T)
Value:
    DEFINE_BINARY_OP_O(omul1##$,*,operator *,T,Scalar,T)     \
    DEFINE_BINARY_OP_O(omul2##$,*,operator *,Scalar,T,T)     \
    DEFINE_BINARY_OP_O(odiv1##$,/,operator /,T,Scalar,T)     \
    DEFINE_BINARY_OP_O(odiv2##$,/,operator /,Scalar,T,T)
Definition at line 1282 of file field.h.
SOp
#define SOp ()
Value:
        MeshField& operator $(const Scalar& q) {                        \
            _Pragma("omp parallel for")                                 \
            _Pragma("acc parallel loop")                                \
            forEach(*this,i)                                            \
                P[i] $ q;                                               \
            return *this;                                               \
        }
Definition at line 883 of file field.h.
srci
#define srci (x) (x)
Definition at line 3679 of file field.h.
TensorProduct
#define TensorProduct (Q, P) TensorProduct_(Q,P,false,-=)
Definition at line 2315 of file field.h.
TensorProduct_
#define TensorProduct_ (Q, P, tr)
Definition at line 2283 of file field.h.
TensorProductM
#define TensorProductM (Q, P) TensorProduct_(Q,P,false,+=)
Definition at line 2317 of file field.h.
TensorProductT
#define TensorProductT (Q, P) TensorProduct_(Q,P,true,-=)
Definition at line 2316 of file field.h.
Typedef Documentation
IntCellField
typedef MeshField<Int,CELL> IntCellField
Definition at line 1183 of file field.h.
IntFacetField
typedef MeshField<Int,FACET> IntFacetField
Definition at line 1184 of file field.h.
IntVertexField
typedef MeshField<Int,VERTEX> IntVertexField
Definition at line 1185 of file field.h.
ScalarCellField
typedef MeshField<Scalar,CELL> ScalarCellField
Definition at line 1186 of file field.h.
ScalarCellMatField
typedef MeshField<Scalar,CELLMAT> ScalarCellMatField
Definition at line 1198 of file field.h.
ScalarCellMatrix
typedef MeshMatrix<Scalar> ScalarCellMatrix
Definition at line 1806 of file field.h.
ScalarFacetField
typedef MeshField<Scalar,FACET> ScalarFacetField
Definition at line 1187 of file field.h.
ScalarVertexField
typedef MeshField<Scalar,VERTEX> ScalarVertexField
Definition at line 1188 of file field.h.
STensorCellField
typedef MeshField<STensor,CELL> STensorCellField
Definition at line 1195 of file field.h.
STensorCellMatrix
typedef MeshMatrix<STensor> STensorCellMatrix
Definition at line 1809 of file field.h.
STensorFacetField
typedef MeshField<STensor,FACET> STensorFacetField
Definition at line 1196 of file field.h.
STensorVertexField
typedef MeshField<STensor,VERTEX> STensorVertexField
Definition at line 1197 of file field.h.
TensorCellField
typedef MeshField<Tensor,CELL> TensorCellField
Definition at line 1192 of file field.h.
TensorCellMatrix
typedef MeshMatrix<Tensor> TensorCellMatrix
Definition at line 1808 of file field.h.
TensorFacetField
typedef MeshField<Tensor,FACET> TensorFacetField
Definition at line 1193 of file field.h.
TensorVertexField
typedef MeshField<Tensor,VERTEX> TensorVertexField
Definition at line 1194 of file field.h.
VectorCellField
typedef MeshField<Vector,CELL> VectorCellField
Definition at line 1189 of file field.h.
VectorCellMatrix
typedef MeshMatrix<Vector> VectorCellMatrix
Definition at line 1807 of file field.h.
VectorFacetField
typedef MeshField<Vector,FACET> VectorFacetField
Definition at line 1190 of file field.h.
VectorVertexField
typedef MeshField<Vector,VERTEX> VectorVertexField
Definition at line 1191 of file field.h.
Enumeration Type Documentation
ACCESS
enum ACCESS
Read/Write access for field
Enumerator
NO
No access allowed
READ
Read only access
WRITE
Write only access
READWRITE
Read write access
STOREPREV
Store previous iteration value
Definition at line 399 of file field.h.
ENTITY
enum ENTITY
Basic building blocks (entities) over which fields are defined
Enumerator
CELL
A cell (volume), each LGL node gets one cell in DG.
FACET
A polygonal face.
VERTEX
A node.
CELLMAT
An NXN matrix for each element.
Definition at line 9 of file field.h.
Function Documentation
addTemporal()
template<int order, class type > void addTemporal (MeshMatrix< type > & M, Scalar cF_UR, ScalarCellField * rho = 0, ScalarCellField * rho0 = 0)
Time stepper
Definition at line 3823 of file field.h.
References Controls::AB1, Controls::AB5, MeshField< type, entity >::access, Controls::AM1, Controls::AM5, Controls::BDF1, Controls::BDF6, MeshMatrix< T1, T2, T3 >::cF, cFR, Controls::current_step, ddt(), ddt2(), MeshField< type, entity >::initStore(), mul(), MeshField< type, entity >::nstored, Controls::state, Controls::STEADY, STOREPREV, MeshMatrix< T1, T2, T3 >::Su, Controls::time_scheme, and MeshField< type, entity >::updateStore().
applyExplicitBCs()
template<class T , ENTITY E> void applyExplicitBCs (const MeshField< T, E > & cF, bool update_ghost = false)
Apply explicit boundary conditions
Definition at line 2541 of file field.h.
References Mesh::AllBConditions, BasicBCondition::bdry, Mesh::CALC_DIRICHLET, Mesh::cC, BasicBCondition::cIndex, Mesh::CYCLIC, BCondition< type >::dir, Mesh::DIRICHLET, equal(), BasicBCondition::fIndex, MeshField< type, entity >::fIndex, BCondition< type >::first, BCondition< type >::fixed, Mesh::fN, Mesh::FN, Mesh::FO, forEach, Mesh::gALLfield, Mesh::gBoundaries, Mesh::gFacets, Mesh::GHOST, Mesh::gInterMesh, Mesh::INVERSE, Mesh::LOG, mag(), BasicBCondition::neighbor, Mesh::NEUMANN, DG::NPF, Mesh::PARABOLIC, Mesh::POWER, ASYNC_COMM< T >::recv(), Mesh::ROBIN, Mesh::ROUGHWALL, Scalar, ASYNC_COMM< T >::send(), BCondition< type >::shape, sym(), Mesh::SYMMETRY, BCondition< type >::tshape, BCondition< type >::tvalue, BCondition< type >::value, Mesh::vC, BCondition< type >::zMax, and BCondition< type >::zMin.
Referenced by Mesh::initGeomMeshFields().
applyImplicitBCs()
template<class T1 , class T2 , class T3 > void applyImplicitBCs (const MeshMatrix< T1, T2, T3 > & M)
Apply implicit boundary conditions
Definition at line 2497 of file field.h.
References Mesh::AllBConditions, MeshMatrix< T1, T2, T3 >::ann, MeshMatrix< T1, T2, T3 >::ap, BasicBCondition::bdry, MeshMatrix< T1, T2, T3 >::cF, BasicBCondition::cIndex, Mesh::CYCLIC, BasicBCondition::fIndex, MeshField< type, entity >::fIndex, Mesh::FN, Mesh::FO, forEach, Mesh::gALLfield, Mesh::GHOST, Mesh::NEUMANN, DG::NPF, Mesh::ROBIN, BCondition< type >::shape, and MeshMatrix< T1, T2, T3 >::Su.
cds() [1/2]
template<class type > auto cds (const MeshField< type, CELL > & cF)
central difference scheme
Definition at line 2836 of file field.h.
References Mesh::fI, forEach, and scatter_non_conforming().
Referenced by div_flux_implicit(), divf(), flx(), gradf(), Mesh::initGeomMeshFields(), MeshField< type, entity >::interpolateVertexAll(), lap(), rusanov(), and MeshField< type, entity >::writeVtkVertexAll().
cds() [2/2]
template<class type > auto cds (const MeshField< type, FACET > & fF)
interpolate facet data to vertex data
Definition at line 2902 of file field.h.
References Mesh::fC, Mesh::FN, forEach, Mesh::gALLfield, Mesh::gBCSfield, Mesh::gFacets, Mesh::gVertices, Constants::MachineEpsilon, mag(), DG::NP, and Scalar.
convection() [1/2]
template<class type > auto convection (MeshField< type, CELL > & cF, const VectorCellField & Fc, const ScalarFacetField & F, Scalar cF_UR, const MeshField< type, CELL > & Su, const ScalarCellField & Sp, const ScalarFacetField * lambdaMax = 0, ScalarCellField * rho = 0, ScalarCellField * rho0 = 0)
Definition at line 3902 of file field.h.
References div(), and src().
convection() [2/2]
template<class type > auto convection (MeshField< type, CELL > & cF, const VectorCellField & Fc, const ScalarFacetField & F, Scalar cF_UR, const ScalarFacetField * lambdaMax = 0, ScalarCellField * rho = 0, ScalarCellField * rho0 = 0)
Definition at line 3892 of file field.h.
References div().
ddt()
template<class type > auto ddt (MeshMatrix< type > & M, const MeshField< type, CELL > & rhs, ScalarCellField * rho, ScalarCellField * rho0)
First derivative with respect to time
Definition at line 3689 of file field.h.
References Controls::AB1, Controls::AB2, Controls::AB3, Controls::AB4, Controls::AB5, MeshMatrix< T1, T2, T3 >::adg, Controls::AM1, Controls::AM2, Controls::AM3, Controls::AM4, Controls::AM5, MeshMatrix< T1, T2, T3 >::ann, MeshMatrix< T1, T2, T3 >::ano, MeshMatrix< T1, T2, T3 >::ap, Controls::BDF1, Controls::BDF2, Controls::BDF3, Controls::BDF4, Controls::BDF5, Controls::BDF6, MeshMatrix< T1, T2, T3 >::cF, cFR, Mesh::cV, MeshMatrix< T1, T2, T3 >::DIAGONAL, Controls::dt, MeshMatrix< T1, T2, T3 >::flags, mul(), MeshField< type, entity >::nstored, PREV, Controls::RK1, Controls::RK2, Controls::RK3, Controls::RK4, Scalar, MeshMatrix< T1, T2, T3 >::Su, MeshMatrix< T1, T2, T3 >::SYMMETRIC, and Controls::time_scheme.
Referenced by addTemporal().
ddt2()
template<class type > auto ddt2 (MeshMatrix< type > & M, const MeshField< type, CELL > & rhs, ScalarCellField * rho, ScalarCellField * rho0)
Second derivative with respect to time
Definition at line 3793 of file field.h.
References MeshMatrix< T1, T2, T3 >::adg, MeshMatrix< T1, T2, T3 >::ann, MeshMatrix< T1, T2, T3 >::ano, MeshMatrix< T1, T2, T3 >::ap, Controls::BDF2, Controls::BDF3, Controls::BDF6, MeshMatrix< T1, T2, T3 >::cF, Mesh::cV, MeshMatrix< T1, T2, T3 >::DIAGONAL, Controls::dt, MeshMatrix< T1, T2, T3 >::flags, MeshField< type, entity >::nstored, PREV, Scalar, MeshMatrix< T1, T2, T3 >::Su, MeshMatrix< T1, T2, T3 >::SYMMETRIC, and Controls::time_scheme.
Referenced by addTemporal().
DEFINE_BINARY_OP() [1/4]
DEFINE_BINARY_OP (oadd , + , operator+ , type)
DEFINE_BINARY_OP() [2/4]
DEFINE_BINARY_OP (odiv , / , operator/ , type)
DEFINE_BINARY_OP() [3/4]
DEFINE_BINARY_OP (omul , * , operator* , type)
DEFINE_BINARY_OP() [4/4]
DEFINE_BINARY_OP (osub , - , operator- , type)
DEFINE_BINARY_OP2() [1/4]
DEFINE_BINARY_OP2 (oatan2 , atan2 , type)
DEFINE_BINARY_OP2() [2/4]
DEFINE_BINARY_OP2 (omax , max , type)
DEFINE_BINARY_OP2() [3/4]
DEFINE_BINARY_OP2 (omin , min , type)
DEFINE_BINARY_OP2() [4/4]
DEFINE_BINARY_OP2 (ossdiv , sdiv , type)
DEFINE_BINARY_OP_O() [1/3]
DEFINE_BINARY_OP_O (omulb , * , operator* , Vector , Vector , Vector)
DEFINE_BINARY_OP_O() [2/3]
DEFINE_BINARY_OP_O (omulc , * , operator* , Tensor , Tensor , Tensor)
DEFINE_BINARY_OP_O() [3/3]
DEFINE_BINARY_OP_O (omuld , * , operator* , STensor , STensor , STensor)
DEFINE_BINARY_SOP() [1/4]
DEFINE_BINARY_SOP (osadd , + , operator+ , type , Scalar)
DEFINE_BINARY_SOP() [2/4]
DEFINE_BINARY_SOP (osdiv , / , operator/ , type , Scalar)
DEFINE_BINARY_SOP() [3/4]
DEFINE_BINARY_SOP (osmul , * , operator* , type , Scalar)
DEFINE_BINARY_SOP() [4/4]
DEFINE_BINARY_SOP (ossub , - , operator- , type , Scalar)
DEFINE_BINARY_SOP2() [1/5]
DEFINE_BINARY_SOP2 (odev , dev , type , Scalar)
DEFINE_BINARY_SOP2() [2/5]
DEFINE_BINARY_SOP2 (ohyd , hyd , type , Scalar)
DEFINE_BINARY_SOP2() [3/5]
DEFINE_BINARY_SOP2 (omaxs , max , type , type)
DEFINE_BINARY_SOP2() [4/5]
DEFINE_BINARY_SOP2 (omins , min , type , type)
DEFINE_BINARY_SOP2() [5/5]
DEFINE_BINARY_SOP2 (opow , pow , type , Scalar)
DEFINE_UNARY_OP() [1/19]
DEFINE_UNARY_OP (oacos , acos , type)
DEFINE_UNARY_OP() [2/19]
DEFINE_UNARY_OP (oasin , asin , type)
DEFINE_UNARY_OP() [3/19]
DEFINE_UNARY_OP (oatan , atan , type)
DEFINE_UNARY_OP() [4/19]
DEFINE_UNARY_OP (oceil , ceil , type)
DEFINE_UNARY_OP() [5/19]
DEFINE_UNARY_OP (ocos , cos , type)
DEFINE_UNARY_OP() [6/19]
DEFINE_UNARY_OP (ocosh , cosh , type)
DEFINE_UNARY_OP() [7/19]
DEFINE_UNARY_OP (oexp , exp , type)
DEFINE_UNARY_OP() [8/19]
DEFINE_UNARY_OP (ofabs , fabs , type)
DEFINE_UNARY_OP() [9/19]
DEFINE_UNARY_OP (ofloor , floor , type)
DEFINE_UNARY_OP() [10/19]
DEFINE_UNARY_OP (olog , log , type)
DEFINE_UNARY_OP() [11/19]
DEFINE_UNARY_OP (olog10 , log10 , type)
DEFINE_UNARY_OP() [12/19]
DEFINE_UNARY_OP (osin , sin , type)
DEFINE_UNARY_OP() [13/19]
DEFINE_UNARY_OP (osinh , sinh , type)
DEFINE_UNARY_OP() [14/19]
DEFINE_UNARY_OP (oskw , skw , Tensor)
DEFINE_UNARY_OP() [15/19]
DEFINE_UNARY_OP (osqrt , sqrt , type)
DEFINE_UNARY_OP() [16/19]
DEFINE_UNARY_OP (otan , tan , type)
DEFINE_UNARY_OP() [17/19]
DEFINE_UNARY_OP (otanh , tanh , type)
DEFINE_UNARY_OP() [18/19]
DEFINE_UNARY_OP (otrn , trn , Tensor)
DEFINE_UNARY_OP() [19/19]
DEFINE_UNARY_OP (ounit , unit , type)
DEFINE_UNARY_OP2()
DEFINE_UNARY_OP2 (oneg , - , operator- , type)
DEFINE_UNARY_SOP() [1/2]
DEFINE_UNARY_SOP (omag , mag , type , Scalar)
DEFINE_UNARY_SOP() [2/2]
DEFINE_UNARY_SOP (omagSq , magSq , type , Scalar)
diffusion() [1/2]
template<class type > auto diffusion (MeshField< type, CELL > & cF, const ScalarCellField & mu, Scalar cF_UR, const MeshField< type, CELL > & Su, const ScalarCellField & Sp, ScalarCellField * rho = 0, ScalarCellField * rho0 = 0)
Definition at line 3882 of file field.h.
References MeshMatrix< T1, T2, T3 >::cF, lap(), and src().
diffusion() [2/2]
template<class type > auto diffusion (MeshField< type, CELL > & cF, const ScalarCellField & mu, Scalar cF_UR, ScalarCellField * rho = 0, ScalarCellField * rho0 = 0)
Definition at line 3873 of file field.h.
References MeshMatrix< T1, T2, T3 >::cF, and lap().
div()
template<bool strong = form_strong, class type > auto div (MeshField< type, CELL > & cF, const VectorCellField & fluxc, const ScalarFacetField & flux, const ScalarFacetField * lambdaMax = 0, const ScalarCellField * muc = 0)
Implicit divergence operator
Definition at line 3436 of file field.h.
References MeshMatrix< T1, T2, T3 >::adg, MeshMatrix< T1, T2, T3 >::ap, MeshMatrix< T1, T2, T3 >::cF, Mesh::cV, DIVD, eval_expr(), MeshMatrix< T1, T2, T3 >::flags, forEachLgl, forEachLglX, forEachLglY, forEachLglZ, Mesh::gBCS, INDEX4, INDEX_TX, INDEX_TY, INDEX_TZ, INDEX_X, INDEX_Y, INDEX_Z, DG::Jinv, mul(), DG::NPMAT, Scalar, and MeshMatrix< T1, T2, T3 >::Su.
Referenced by convection(), and transport().
div_flux()
template<bool strong = form_strong, class type > auto div_flux (const MeshField< type, CELL > & p, const MeshField< type, FACET > & fF)
Definition at line 3041 of file field.h.
References Mesh::allFaces, dot(), eval_expr(), Mesh::faceIndices, Mesh::fN, Mesh::FN, Mesh::FO, Mesh::gALLfield, gather_non_conforming(), Mesh::gNCells, DG::NP, and DG::NPF.
div_flux_implicit()
template<bool strong = form_strong, class T1 , class T2 , class T3 , class T4 , class T5 > void div_flux_implicit (MeshMatrix< T1, T2, T3 > & m, const MeshField< T5, CELL > & p, const VectorCellField & fluxc, const MeshField< T4, FACET > & flux, const ScalarFacetField * lambdaMax = 0, const MeshField< T4, CELL > * muc = 0)
TVD schemes ~~~~~~~~~~~ Reference: M.S Darwish and F Moukalled "TVD schemes for unstructured grids" Versteeg and Malaskara Description: phi = phiU + psi(r) * [(phiD - phiC) * (1 - fi)] Schemes psi(r) = 0 =>UDS psi(r) = 1 =>CDS R is calculated as ratio of upwind and downwind gradient r = phiDC / phiCU Further modification to unstructured grid to better fit LUD scheme r = (phiDC / phiCU) * (fi / (1 - fi))
Definition at line 3087 of file field.h.
References Mesh::allFaces, MeshMatrix< T1, T2, T3 >::ann, MeshMatrix< T1, T2, T3 >::ano, MeshMatrix< T1, T2, T3 >::ap, Controls::blend_factor, Controls::BLENDED, Mesh::cC, Controls::CDS, cds(), Controls::CDSS, MeshMatrix< T1, T2, T3 >::cF, Controls::convection_scheme, Controls::DDS, dot(), equal(), Mesh::faceIndices, Mesh::fC, Mesh::fD, Mesh::fI, Mesh::FN, Mesh::FO, forEach, Controls::FROMM, Mesh::gALLfield, Mesh::gNCells, Mesh::gNFacets, gradf(), Controls::HYBRID, Controls::LUD, max(), min(), Controls::MINMOD, Controls::MUSCL, DG::NP, DG::NPF, DG::NPMAT, Controls::QUICK, Controls::QUICKL, Controls::RUSANOV, rusanov(), Scalar, MeshMatrix< T1, T2, T3 >::Su, Controls::SUPERBEE, Controls::SWEBY, Controls::TVDbruner, uds(), Controls::UMIST, Controls::VANALBADA, and Controls::VANLEER.
divf()
template<bool strong = form_strong, typename T1 , typename T2 > auto divf (const MeshField< T1, CELL > & p, bool perunit_volume = false, const ScalarFacetField * flux = 0, const MeshField< T2, CELL > * q = 0, const ScalarFacetField * lambdaMax = 0)
Explicit divergence operator
Definition at line 3363 of file field.h.
References Controls::blend_factor, Controls::BLENDED, Controls::CDS, cds(), Controls::convection_scheme, Mesh::cV, DIVD, fillBCs(), forEachLgl, forEachLglX, forEachLglY, forEachLglZ, Mesh::gBCS, INDEX4, DG::Jinv, DG::NPMAT, Controls::RUSANOV, rusanov(), and uds().
Referenced by Turbulence_Model::getExplicitStresses(), and EddyViscosity_Model::getExplicitStresses().
eval_expr()
template<typename T , ENTITY E> auto eval_expr (const MeshField< T, E > & f)
Definition at line 1315 of file field.h.
Referenced by div(), div_flux(), and grad_flux().
fillBCs()
template<class T > void fillBCs (MeshField< T, CELL > & cF, Int bind = 0, bool sync = false)
Fill boundary values from internals
Definition at line 2686 of file field.h.
References Mesh::AllBConditions, Mesh::allFaces, BasicBCondition::bdry, BasicBCondition::cIndex, Mesh::faceIndices, BasicBCondition::fIndex, Mesh::FN, Mesh::FO, forEach, Mesh::gALLfield, Mesh::gBCS, Mesh::gInterMesh, Mesh::gNCells, Mesh::NEUMANN, DG::NPF, ASYNC_COMM< T >::recv(), ASYNC_COMM< T >::send(), Mesh::SYMMETRY, and BCondition< type >::value.
Referenced by divf(), EddyViscosity_Model::getExplicitStresses(), and gradf().
flx()
template<typename type > auto flx (const MeshField< type, CELL > & p)
Definition at line 3343 of file field.h.
References cds(), dot(), and Mesh::fN.
flxc()
template<typename T > auto flxc (const MeshField< T, CELL > & p) inline
Definition at line 3338 of file field.h.
gather_non_conforming()
template<class type > void gather_non_conforming (const MeshField< type, FACET > & fF, MeshField< type, FACET > & fFO, MeshField< type, FACET > & fFN)
gather non-conforming face values
Definition at line 1974 of file field.h.
References Mesh::cC, dot(), forEach, forEachLglXY, forEachLglXZ, forEachLglYZ, Mesh::gCells, Mesh::gFaceID, Mesh::gFC, Mesh::gFMC, Mesh::gFNC, Mesh::gFOC, Mesh::gNFacets, INDEX4, DG::NPF, DG::NPMAT, DG::NPX, DG::NPY, DG::NPZ, DG::psiCor, Scalar, and sum().
Referenced by div_flux(), grad_flux(), sum(), and sum_flux().
getRHS()
template<class T1 , class T2 , class T3 > auto getRHS (const MeshMatrix< T1, T2, T3 > & p, const MeshField< T1, CELL > & q, const bool sync = false)
calculate right-hand-side sum = b - (L + U) * x
Definition at line 2439 of file field.h.
References MeshMatrix< T1, T2, T3 >::DIAGONAL, MeshMatrix< T1, T2, T3 >::flags, Mesh::gBCS, Mesh::gHasBoundary, MUL, DG::NPMAT, ASYNC_COMM< T >::recv(), ASYNC_COMM< T >::send(), MeshMatrix< T1, T2, T3 >::Su, and TensorProductM.
grad_flux()
template<bool strong = form_strong, class type > auto grad_flux (const MeshField< type, CELL > & p, const MeshField< type, FACET > & fF)
Definition at line 3006 of file field.h.
References Mesh::allFaces, eval_expr(), Mesh::faceIndices, Mesh::fN, Mesh::FN, Mesh::FO, Mesh::gALLfield, gather_non_conforming(), Mesh::gNCells, mul(), DG::NP, and DG::NPF.
gradf()
template<bool strong = form_strong, typename T1 > auto gradf (const MeshField< T1, CELL > & p, bool perunit_volume = false)
Explicit gradient operator
Definition at line 3281 of file field.h.
References cds(), Mesh::cV, fillBCs(), MeshField< type, entity >::fIndex, forEachLgl, forEachLglX, forEachLglY, forEachLglZ, Mesh::gBCS, GRADD, INDEX4, DG::Jinv, and DG::NPMAT.
Referenced by div_flux_implicit(), Turbulence_Model::getExplicitStresses(), EddyViscosity_Model::getExplicitStresses(), MixingLength_Model::getK(), EddyViscosity_Model::getReynoldsStress(), Turbulence_Model::getViscousStress(), and lap().
lap()
template<bool strong = form_strong, class type > auto lap (MeshField< type, CELL > & cF, const ScalarCellField & muc, const bool penalty = false)
Implicit laplacian operator
Definition at line 3511 of file field.h.
References MeshMatrix< T1, T2, T3 >::adg, Mesh::allFaces, MeshMatrix< T1, T2, T3 >::ann, MeshMatrix< T1, T2, T3 >::ano, MeshMatrix< T1, T2, T3 >::ap, Mesh::cC, cds(), MeshMatrix< T1, T2, T3 >::cF, dot(), Mesh::faceIndices, Mesh::fD, MeshMatrix< T1, T2, T3 >::flags, Mesh::fN, Mesh::FN, Mesh::FO, forEach, forEachLgl, forEachLglX, forEachLglY, forEachLglZ, Mesh::gALLfield, Mesh::gBCS, Mesh::gNCells, gradf(), INDEX4, DG::Jinv, LAPD, mag(), NONE, Controls::nonortho_scheme, DG::NP, DG::NPF, DG::NPMAT, Scalar, MeshMatrix< T1, T2, T3 >::Su, sum(), and MeshMatrix< T1, T2, T3 >::SYMMETRIC.
Referenced by diffusion(), and transport().
mul()
template<class T1 , class T2 , class T3 > auto mul (const MeshMatrix< T1, T2, T3 > & p, const MeshField< T1, CELL > & q, const bool sync = false)
matrix - vector product = A * x
Definition at line 2325 of file field.h.
References MeshMatrix< T1, T2, T3 >::ap, MeshMatrix< T1, T2, T3 >::DIAGONAL, MeshMatrix< T1, T2, T3 >::flags, Mesh::gBCS, Mesh::gHasBoundary, MUL, DG::NPMAT, ASYNC_COMM< T >::recv(), ASYNC_COMM< T >::send(), and TensorProduct.
Referenced by addTemporal(), REALIZABLE_KE_Model::calcEddyViscosity(), ddt(), div(), grad_flux(), DG::init_geom(), rusanov(), and SolveT().
mult()
template<class T1 , class T2 , class T3 > auto mult (const MeshMatrix< T1, T2, T3 > & p, const MeshField< T1, CELL > & q, const bool sync = false)
matrix transopose - vector product = A^T * x
Definition at line 2386 of file field.h.
References MeshMatrix< T1, T2, T3 >::ap, MeshMatrix< T1, T2, T3 >::DIAGONAL, MeshMatrix< T1, T2, T3 >::flags, Mesh::gBCS, Mesh::gHasBoundary, MUL, DG::NPMAT, ASYNC_COMM< T >::recv(), ASYNC_COMM< T >::send(), and TensorProductT.
Referenced by SolveT().
rusanov()
template<typename T1 , typename T2 > auto rusanov (const MeshField< T1, CELL > & F, const MeshField< T2, CELL > & q, const ScalarFacetField & lambdaMax)
rusanov flux
Definition at line 2883 of file field.h.
References cds(), Mesh::fN, forEach, mul(), and scatter_non_conforming().
Referenced by div_flux_implicit(), and divf().
ScaMul() [1/2]
ScaMul (STensor , 3)
ScaMul() [2/2]
ScaMul (Vector , 1)
scatter_non_conforming()
template<class type > void scatter_non_conforming (const MeshField< type, CELL > & cF, MeshField< type, FACET > & fFO, MeshField< type, FACET > & fFN)
scatter non-conforming face values
Definition at line 2090 of file field.h.
References Mesh::cC, dot(), Mesh::FN, Mesh::FO, forEach, forEachLglXY, forEachLglXZ, forEachLglYZ, Mesh::gCells, Mesh::gFaceID, Mesh::gFC, Mesh::gFMC, Mesh::gFNC, Mesh::gFOC, Mesh::gNFacets, INDEX4, DG::NPF, DG::NPMAT, DG::NPX, DG::NPY, DG::NPZ, DG::psiRef, Scalar, and sum().
Referenced by cds(), rusanov(), and uds().
src()
template<class T1 , class T2 , class T3 > auto src (MeshField< T1, CELL > & cF, const MeshField< T3, CELL > & Su, const MeshField< T2, CELL > & Sp)
Add implicit source terms
Definition at line 3660 of file field.h.
References MeshMatrix< T1, T2, T3 >::adg, MeshMatrix< T1, T2, T3 >::ann, MeshMatrix< T1, T2, T3 >::ano, MeshMatrix< T1, T2, T3 >::ap, MeshMatrix< T1, T2, T3 >::cF, Mesh::cV, MeshMatrix< T1, T2, T3 >::DIAGONAL, MeshMatrix< T1, T2, T3 >::flags, Scalar, MeshMatrix< T1, T2, T3 >::Su, and MeshMatrix< T1, T2, T3 >::SYMMETRIC.
Referenced by convection(), diffusion(), Mesh::fixedBCs(), Mesh::scaleBCs(), and transport().
srcf()
template<class type > auto srcf (const MeshField< type, CELL > & Su)
Add explicit source term
Definition at line 3675 of file field.h.
References Mesh::cV.
sum()
template<class type > auto sum (const MeshField< type, FACET > & fF)
Definition at line 2945 of file field.h.
References Mesh::allFaces, Mesh::faceIndices, Mesh::FN, Mesh::FO, Mesh::gALLfield, gather_non_conforming(), Mesh::gNCells, DG::NP, and DG::NPF.
Referenced by gather_non_conforming(), lap(), matmul(), Mesh::pointInPolygon(), rotate(), and scatter_non_conforming().
sum_flux()
template<bool strong = form_strong, class type , class type2 > auto sum_flux (const MeshField< type, CELL > & p, const MeshField< type, FACET > & fF, const MeshField< type2, FACET > & flux)
Definition at line 2972 of file field.h.
References Mesh::allFaces, Mesh::faceIndices, Mesh::FN, Mesh::FO, Mesh::gALLfield, gather_non_conforming(), Mesh::gNCells, DG::NP, and DG::NPF.
transport() [1/2]
template<class type > auto transport (MeshField< type, CELL > & cF, const VectorCellField & Fc, const ScalarFacetField & F, const ScalarCellField & mu, Scalar cF_UR, const MeshField< type, CELL > & Su, const ScalarCellField & Sp, const ScalarFacetField * lambdaMax = 0, ScalarCellField * rho = 0, ScalarCellField * rho0 = 0)
Definition at line 3923 of file field.h.
References div(), lap(), and src().
transport() [2/2]
template<class type > auto transport (MeshField< type, CELL > & cF, const VectorCellField & Fc, const ScalarFacetField & F, const ScalarCellField & mu, Scalar cF_UR, const ScalarFacetField * lambdaMax = 0, ScalarCellField * rho = 0, ScalarCellField * rho0 = 0)
Definition at line 3913 of file field.h.
References div(), and lap().
uds()
template<class type , class T3 > auto uds (const MeshField< type, CELL > & cF, const MeshField< T3, FACET > & flux)
upwind differencing scheme
Definition at line 2859 of file field.h.
References dot(), forEach, and scatter_non_conforming().
Referenced by div_flux_implicit(), and divf().
Variable Documentation
form_strong
constexpr bool form_strong = false constexpr
Descretization type
Definition at line 61 of file field.h.
operator*,Scalar, Scalar, Scalar)
operator*, Scalar, Scalar, Scalar)
Definition at line 1294 of file field.h.