NebulaSEM: /home/daniel/storage/NebulaSEM/src/mesh/hexMesh.cpp File Reference
hexMesh.cpp File Reference
#include "hexMesh.h"
Macros
#define I0(i, j, k) (i * ny * nz + j * nz + k)
#define ADDF(w, rr, rs, i00, i01, i10, i11, ir0, ir1, i0s, i1s)
#define ADDC()
#define ADD()
#define I1(i, j, k) (i * (ny - 1) * (nz - 1) + j * (nz - 1) + k)
#define I2(i, j, k) (i * (ny - 0) * (nz - 1) + j * (nz - 1) + k + B1)
#define I3(i, j, k) (i * (ny - 1) * (nz - 0) + j * (nz - 0) + k + B1 + B2)
#define ADD(a1, a2, a3, a4)
#define NORMAL(i, j, k, l, p)
#define MAXNUM 1073741824
Functions
Vector circumcenter (const Vector &v1, const Vector &v2, const Vector &v3)
void ADDV (int w, Scalar m, Edge *edges, Vector *vd)
void hexMesh (Int *n, Scalar *s, Int *type, Vector *vp, Edge *edges, MeshObject &mo)
void remove_duplicate (Mesh::MeshObject &mo)
void merge (MeshObject &m1, MergeObject &b, MeshObject &m2)
void merge (Mesh::MeshObject &m, MergeObject &b)
Macro Definition Documentation
ADD [1/2]
#define ADD ()
Value:
    {                                     \
    ADDV(0,sc[0][i],edges,vd);                      \
    ADDV(1,sc[1][i],edges,vd);                      \
    ADDV(2,sc[2][i],edges,vd);                      \
    ADDV(3,sc[3][i],edges,vd);                      \
    ADDV(4,sc[4][j],edges,vd);                      \
    ADDV(5,sc[5][j],edges,vd);                      \
    ADDV(6,sc[6][j],edges,vd);                      \
    ADDV(7,sc[7][j],edges,vd);                      \
    ADDV(8,sc[8][k],edges,vd);                      \
    ADDV(9,sc[9][k],edges,vd);                      \
    ADDV(10,sc[10][k],edges,vd);                    \
    ADDV(11,sc[11][k],edges,vd);                    \
    rx = i / Scalar(nx - 1);                        \
    ry = j / Scalar(ny - 1);                        \
    rz = k / Scalar(nz - 1);                        \
    ADDF(0, rx,ry, 0,3,1,2, 0,1,4,5);               \
    ADDF(1, rx,ry, 4,7,5,6, 3,2,7,6);               \
    ADDF(2, rx,rz, 0,4,1,5, 0,3,8,9);               \
    ADDF(3, rx,rz, 3,7,2,6, 1,2,11,10);             \
    ADDF(4, ry,rz, 0,4,3,7, 4,7,8,11);              \
    ADDF(5, ry,rz, 1,5,2,6, 5,6,9,10);              \
    ADDC();                                         \
};
ADD [2/2]
#define ADD (a1, a2, a3, a4)
Value:
    {                          \
    Facet f;                                        \
    m = I0(i,j,k);                                  \
    f.push_back(VI[a1]);                            \
    f.push_back(VI[a2]);                            \
    f.push_back(VI[a3]);                            \
    f.push_back(VI[a4]);                            \
    mo.mFacets.push_back(f);                        \
};
ADDC
#define ADDC ()
Value:
    {                                        \
    v = Interpolate_cell(                               \
            rx,ry,rz,                                   \
            vp[0],vp[4],vp[3],vp[7],                    \
            vp[1],vp[5],vp[2],vp[6],                    \
            vd[0],vd[3],vd[1],vd[2],                    \
            vd[4],vd[7],vd[5],vd[6],                    \
            vd[8],vd[11],vd[9],vd[10],                  \
            vf[4],vf[5],vf[2],vf[3],vf[0],vf[1]);       \
}
ADDF
#define ADDF (w, rr, rs, i00, i01, i10, i11, ir0, ir1, i0s, i1s)
Value:
    { \
    vf[w] = Interpolate_face(                           \
            rr,rs,                                      \
            vp[i00],vp[i01],vp[i10],vp[i11],            \
            vd[ir0],vd[ir1],vd[i0s],vd[i1s]);           \
}
I0
#define I0 (i, j, k) (i * ny * nz + j * nz + k)
I1
#define I1 (i, j, k) (i * (ny - 1) * (nz - 1) + j * (nz - 1) + k)
I2
#define I2 (i, j, k) (i * (ny - 0) * (nz - 1) + j * (nz - 1) + k + B1)
I3
#define I3 (i, j, k) (i * (ny - 1) * (nz - 0) + j * (nz - 0) + k + B1 + B2)
MAXNUM
#define MAXNUM 1073741824
Definition at line 448 of file hexMesh.cpp.
NORMAL
#define NORMAL (i, j, k, l, p)
Value:
    {                         \
    p.N = ((vp[j] - vp[i]) ^ (vp[k] - vp[i]));      \
    p.N /= mag(p.N);                                \
    p.C = (vp[i] + vp[j] + vp[k] + vp[l]) / 4;      \
}
Function Documentation
ADDV()
void ADDV (int w, Scalar m, Edge * edges, Vector * vd)
Add a vertex following shape of a given edge
Definition at line 22 of file hexMesh.cpp.
References ARC, COSINE, Edge::N, NONE, Constants::PI, QUAD, rotate(), Edge::theta, Edge::type, and Edge::v.
circumcenter()
Vector circumcenter (const Vector & v1, const Vector & v2, const Vector & v3)
Calculate the circum-circumcenter of triangle (circumcenter of circumscribed circle) or crossing point of two perpendicular bisectors. Used for ARC edges.
Definition at line 9 of file hexMesh.cpp.
References Scalar.
Referenced by hexMesh().
hexMesh()
void hexMesh (Int * n, Scalar * s, Int * type, Vector * vp, Edge * edges, MeshObject & mo)
Generate hexahedral mesh
Definition at line 41 of file hexMesh.cpp.
References ADD, ARC, circumcenter(), COSINE, equal(), Mesh::Patch::from, I0, I1, I2, I3, mag(), Mesh::MeshObject::mBCS, Mesh::MeshObject::mCells, Mesh::MeshObject::mFacets, Mesh::MeshObject::mNF, Mesh::MeshObject::mNV, Mesh::MeshObject::mPatches, Mesh::MeshObject::mVertices, Edge::N, NORMAL, QUAD, remove_duplicate(), Scalar, Edge::theta, Mesh::Patch::to, Edge::type, Edge::v, and WALL.
merge() [1/2]
void merge (Mesh::MeshObject & m, MergeObject & b)
Merge boundary and internals
Definition at line 595 of file hexMesh.cpp.
References MergeObject::fb, forEach, MAXNUM, Mesh::MeshObject::mBCS, Mesh::MeshObject::mCells, Mesh::MeshObject::mFacets, Mesh::MeshObject::mNF, Mesh::MeshObject::mNV, Mesh::MeshObject::mVertices, and MergeObject::vb.
merge() [2/2]
void merge (MeshObject & m1, MergeObject & b, MeshObject & m2)
Merge mesh m2 onto m1 (internal) and b (boundary) meshes
Definition at line 453 of file hexMesh.cpp.
References Mesh::Patch::C, equal(), equalSet(), MergeObject::fb, forEach, MAXNUM, Mesh::MeshObject::mCells, Mesh::MeshObject::mFacets, Mesh::MeshObject::mNF, Mesh::MeshObject::mNV, Mesh::MeshObject::mPatches, Mesh::MeshObject::mVertices, and MergeObject::vb.
remove_duplicate()
void remove_duplicate (Mesh::MeshObject & mo)
Remove duplicate vertices,faces and cells
Definition at line 357 of file hexMesh.cpp.
References equal(), forEach, forEachS, Mesh::Patch::from, Mesh::MeshObject::mCells, Mesh::MeshObject::mFacets, Mesh::MeshObject::mNF, Mesh::MeshObject::mNV, Mesh::MeshObject::mPatches, Mesh::MeshObject::mVertices, and Mesh::Patch::to.
Referenced by hexMesh().