NebulaSEM: /home/daniel/storage/NebulaSEM/src/mesh/hexMesh.h File Reference
hexMesh.h File Reference
#include "mesh.h"
Classes
struct Edge
struct MergeObject
Enumerations
enum { LINEAR , GEOMETRIC , WALL , MIXED }
enum { NONE = 0 , ARC , COSINE , QUAD }
Functions
void hexMesh (Int *n, Scalar *s, Int *type, Vector *vp, Edge *edges, Mesh::MeshObject &mo)
void merge (Mesh::MeshObject &, MergeObject &, Mesh::MeshObject &)
void remove_duplicate (Mesh::MeshObject &)
void merge (Mesh::MeshObject &, MergeObject &)
Enumeration Type Documentation
anonymous enum
anonymous enum
Element edges refinement options
Enumerator
LINEAR
Uniform spacing
GEOMETRIC
Geometrically varying spacing
WALL
Larger spacing at the center
MIXED
Mixed mode for different edges of the element
Definition at line 7 of file hexMesh.h.
anonymous enum
anonymous enum
Edge shapes
Enumerator
NONE
Straight edge
ARC
Circular arc
COSINE
Cosine shaped edge
QUAD
Quadratic shaped edge
Definition at line 15 of file hexMesh.h.
Function Documentation
hexMesh()
void hexMesh (Int * n, Scalar * s, Int * type, Vector * vp, Edge * edges, MeshObject & mo)
Generate hexahedral mesh
Definition at line 41 of file hexMesh.cpp.
References ADD, ARC, circumcenter(), COSINE, equal(), Mesh::Patch::from, I0, I1, I2, I3, mag(), Mesh::MeshObject::mBCS, Mesh::MeshObject::mCells, Mesh::MeshObject::mFacets, Mesh::MeshObject::mNF, Mesh::MeshObject::mNV, Mesh::MeshObject::mPatches, Mesh::MeshObject::mVertices, Edge::N, NORMAL, QUAD, remove_duplicate(), Scalar, Edge::theta, Mesh::Patch::to, Edge::type, Edge::v, and WALL.
merge() [1/2]
void merge (Mesh::MeshObject & m, MergeObject & b)
Merge boundary and internals
Definition at line 595 of file hexMesh.cpp.
References MergeObject::fb, forEach, MAXNUM, Mesh::MeshObject::mBCS, Mesh::MeshObject::mCells, Mesh::MeshObject::mFacets, Mesh::MeshObject::mNF, Mesh::MeshObject::mNV, Mesh::MeshObject::mVertices, and MergeObject::vb.
merge() [2/2]
void merge (MeshObject & m1, MergeObject & b, MeshObject & m2)
Merge mesh m2 onto m1 (internal) and b (boundary) meshes
Definition at line 453 of file hexMesh.cpp.
References Mesh::Patch::C, equal(), equalSet(), MergeObject::fb, forEach, MAXNUM, Mesh::MeshObject::mCells, Mesh::MeshObject::mFacets, Mesh::MeshObject::mNF, Mesh::MeshObject::mNV, Mesh::MeshObject::mPatches, Mesh::MeshObject::mVertices, and MergeObject::vb.
remove_duplicate()
void remove_duplicate (Mesh::MeshObject & mo)
Remove duplicate vertices,faces and cells
Definition at line 357 of file hexMesh.cpp.
References equal(), forEach, forEachS, Mesh::Patch::from, Mesh::MeshObject::mCells, Mesh::MeshObject::mFacets, Mesh::MeshObject::mNF, Mesh::MeshObject::mNV, Mesh::MeshObject::mPatches, Mesh::MeshObject::mVertices, and Mesh::Patch::to.
Referenced by hexMesh().