NebulaSEM: Constants Namespace Reference
Constants Namespace Reference
Enumerations
enum {
XX , YY , ZZ , XY ,
YZ , XZ , YX , ZY ,
ZX
}
Functions
const Vector I_V (1, 1, 1)
const Tensor I_T (1, 1, 1)
const STensor I_ST (1, 1, 1)
Variables
const Int MAX_INT = Int(1 << 31)
const Scalar PI = Scalar(3.14159265358979323846264)
const Scalar E = Scalar(2.71828182845904523536028)
const Scalar MachineEpsilon = Scalar(1e-7)
const Scalar EqualEpsilon = Scalar(1e-3)
Detailed Description
Mathematical constants
Enumeration Type Documentation
anonymous enum
anonymous enum
Names for the 9 indices of a tensor (2-rank)
Enumerator
XX
YY
ZZ
XY
YZ
XZ
YX
ZY
ZX
Definition at line 452 of file tensor.h.
Function Documentation
I_ST()
const STensor Constants::I_ST (1 , 1 , 1)
Referenced by EddyViscosity_Model::getReynoldsStress(), and sym().
I_T()
const Tensor Constants::I_T (1 , 1 , 1)
Referenced by sym().
I_V()
const Vector Constants::I_V (1 , 1 , 1)
Variable Documentation
E
const Scalar Constants::E = Scalar(2.71828182845904523536028)
Definition at line 457 of file tensor.h.
EqualEpsilon
const Scalar Constants::EqualEpsilon = Scalar(1e-3)
Definition at line 463 of file tensor.h.
Referenced by Iteration::Iteration().
MachineEpsilon
const Scalar Constants::MachineEpsilon = Scalar(1e-7)
Definition at line 462 of file tensor.h.
Referenced by cds(), KE_Model::solve(), KW_Model::solve(), REALIZABLE_KE_Model::solve(), and RNG_KE_Model::solve().
MAX_INT
const Int Constants::MAX_INT = Int(1 << 31)
Definition at line 455 of file tensor.h.
Referenced by Mesh::MeshObject::addBoundaryCells(), Prepare::decomposeMesh(), Mesh::MeshObject::initFaceInfo(), Mesh::MeshObject::readMshMesh(), Mesh::MeshObject::refineCell(), Mesh::MeshObject::refineFacet(), MeshField< type, entity >::refineField(), Mesh::MeshObject::refineMesh(), and Mesh::MeshObject::removeBoundary().
PI
const Scalar Constants::PI = Scalar(3.14159265358979323846264)
Definition at line 456 of file tensor.h.
Referenced by ADDV(), Mesh::MeshObject::getHexCorners(), DG::legendre_gauss_lobatto(), and Mesh::pointInPolygon().