NebulaSEM: Prepare Namespace Reference
Prepare Namespace Reference
Functions
void decomposeIndex (Int total, IntVector &blockIndex)
void decomposeXYZ (Int *n, Scalar *nq, IntVector &blockIndex)
void decomposeMetis (int total, IntVector &blockIndex)
void createFields (std::vector< std::string > &fields, Int step)
void readFields (std::vector< std::string > &fields, Int step)
void refineMesh (Int step)
void calcQOI (ScalarCellField &)
int decomposeMesh (Int)
int mergeFields (Int)
int writeCoords (Int)
void convertVTK (std::vector< std::string > &, Int, Int)
void probe (std::vector< std::string > &, Int, Int)
Function Documentation
calcQOI()
void Prepare::calcQOI (ScalarCellField & qoi)
Calculate quantity of interest (QOI)
Definition at line 608 of file field.cpp.
References Mesh::cV, BaseField::findField(), BaseField::norm(), Controls::refine_params, and Scalar.
convertVTK()
void Prepare::convertVTK (std::vector< std::string > & fields, Int start_index, Int stop_index)
Convert to VTK format
Definition at line 9 of file prepare.cpp.
References createFields(), Mesh::LoadMesh(), readFields(), and Vtk::write_vtk().
createFields()
void Prepare::createFields (std::vector< std::string > & fields, Int step)
Create fields
Definition at line 558 of file field.cpp.
References BaseField::destroyFields(), System::exists(), BaseField::fName, forEach, and READWRITE.
Referenced by convertVTK(), decomposeMesh(), probe(), and refineMesh().
decomposeIndex()
void Prepare::decomposeIndex (Int total, IntVector & blockIndex)
Decompose by cell ID
Definition at line 949 of file field.cpp.
References Mesh::gBCS.
Referenced by decomposeMesh().
decomposeMesh()
int Prepare::decomposeMesh (Int step)
Decompose
Definition at line 1043 of file field.cpp.
References DecomposeParams::axis, MP::barrier(), System::cd(), createFields(), Controls::decompose_params, decomposeIndex(), decomposeMetis(), decomposeXYZ(), BaseField::destroyFields(), System::exists(), BaseField::fieldNames, BaseField::findField(), forEach, forEachIt, Mesh::gBCS, Mesh::gCells, Mesh::gFacets, Mesh::gFNC, Mesh::gFOC, Mesh::gMesh, Mesh::gMeshName, Mesh::gVertices, MP::host_id, Mesh::LoadMesh(), Constants::MAX_INT, Mesh::MeshObject::mBCS, Mesh::MeshObject::mBoundaries, Mesh::MeshObject::mCells, Mesh::MeshObject::mFacets, System::mkdir(), Mesh::MeshObject::mVertices, DecomposeParams::n, MP::n_hosts, DG::NP, readFields(), Controls::TEXT, DecomposeParams::type, BaseField::write(), and Controls::write_format.
Referenced by AmrIteration::AmrIteration(), and AmrIteration::next().
decomposeMetis()
void Prepare::decomposeMetis (int total, IntVector & blockIndex)
Decompose using METIS 5.0
Definition at line 992 of file field.cpp.
References forEach, Mesh::gBCS, Mesh::gCells, Mesh::gFNC, and Mesh::gFOC.
Referenced by decomposeMesh().
decomposeXYZ()
void Prepare::decomposeXYZ (Int * n, Scalar * nq, IntVector & blockIndex)
Decompose in cartesian directions
Definition at line 958 of file field.cpp.
References forEach, Mesh::gBCS, Mesh::gCC, Mesh::gVertices, rotate(), and Scalar.
Referenced by decomposeMesh().
mergeFields()
int Prepare::mergeFields (Int step)
Reverse decomposition
Definition at line 1352 of file field.cpp.
References BaseField::fieldNames, and MP::n_hosts.
Referenced by AmrIteration::next().
probe()
void Prepare::probe (std::vector< std::string > & fields, Int start_index, Int stop_index)
Probe values at specified locations
Definition at line 21 of file prepare.cpp.
References createFields(), Mesh::fC, Mesh::fN, Mesh::FN, Mesh::FO, forEach, forEachCellField, Mesh::getProbeFaces(), Mesh::LoadMesh(), Mesh::probePoints, readFields(), Scalar, and WRITE.
readFields()
void Prepare::readFields (std::vector< std::string > & fields, Int step)
Read fields
Definition at line 596 of file field.cpp.
References Mesh::read_fields().
Referenced by convertVTK(), decomposeMesh(), probe(), and refineMesh().
refineMesh()
void Prepare::refineMesh (Int step)
Refine grid
Definition at line 627 of file field.cpp.
References Mesh::amr_direction, createFields(), RefineParams::dir, BaseField::fieldNames, Mesh::gBCS, Mesh::gCC, Mesh::gCells, Mesh::gCV, Mesh::is_spherical, Mesh::LoadMesh(), readFields(), and Controls::refine_params.
Referenced by AmrIteration::next().
writeCoords()
int Prepare::writeCoords (Int step)
Write spherical grid in lat-lon coordinate
Definition at line 1405 of file field.cpp.