NebulaSEM: Vtk Namespace Reference
Vtk Namespace Reference
Functions
void write_vtk (Int)
Variables
bool write_polyhedral = false
bool write_cell_value = true
Function Documentation
write_vtk()
void Vtk::write_vtk (Int step)
Write ASCII vtk file at time step
Definition at line 41 of file vtk.cpp.
References Mesh::cC, MeshField< Scalar, CELL >::count_writable(), MeshField< type, entity >::count_writable(), forEach, forEachCellField, Mesh::gBCS, Mesh::gBCSfield, Mesh::gCells, Mesh::gFacets, Mesh::gMeshName, Mesh::gVertices, INDEX4, DG::NPMAT, DG::NPX, DG::NPY, DG::NPZ, write_cell_value, and write_polyhedral.
Referenced by Prepare::convertVTK().
Variable Documentation
write_cell_value
bool Vtk::write_cell_value = true extern
Write cell centered values besides vertices
Definition at line 9 of file vtk.cpp.
Referenced by write_vtk().
write_polyhedral
bool Vtk::write_polyhedral = false extern
Write in polyhedral vtk format
Definition at line 7 of file vtk.cpp.
Referenced by write_vtk().