NebulaSEM: System Namespace Reference
System Namespace Reference
Functions
int get_pid ()
int cd (std::string path)
int mkdir (std::string path)
int rmdir (std::string path)
int pwd (char *path, int len)
int exists (std::string path)
int get_time ()
Detailed Description
System dependent collection of functions
Function Documentation
cd()
int System::cd (std::string path) inline
Change directory
Definition at line 30 of file system.h.
Referenced by Prepare::decomposeMesh(), and AmrIteration::next().
exists()
int System::exists (std::string path) inline
Check if file exists
Definition at line 62 of file system.h.
Referenced by Prepare::createFields(), Prepare::decomposeMesh(), and MeshField< type, entity >::read().
get_pid()
int System::get_pid () inline
Gets processor id
Definition at line 22 of file system.h.
Referenced by MP::MP().
get_time()
int System::get_time () inline
Gets time in milli-seconds
Definition at line 70 of file system.h.
Referenced by MP::cleanup(), MP::hasElapsed(), MP::MP(), and MP::printH().
mkdir()
int System::mkdir (std::string path) inline
Makes new directory
Definition at line 38 of file system.h.
Referenced by Prepare::decomposeMesh().
pwd()
int System::pwd (char * path, int len) inline
Gets present working directory
Definition at line 54 of file system.h.
Referenced by MP::MP().
rmdir()
int System::rmdir (std::string path) inline
Removes directory
Definition at line 46 of file system.h.