NebulaSEM: Mesh Namespace Reference
Mesh Namespace Reference
Classes
struct interBoundary
struct Patch
struct Node
struct MeshObject
Typedefs
typedef std::vector< interBoundary > InterBoundVector
typedef std::vector< Patch > PatchVector
typedef std::vector< Node > NodeVector
Functions
void enroll (Util::ParamList &params)
void clearBC ()
bool LoadMesh (Int=0, bool=true, bool extrude=true)
void initGeomMeshFields (bool)
void write_fields (Int)
void read_fields (Int)
void remove_fields ()
Int findNearestCell (const Vector &v)
Int findNearestFace (const Vector &v)
void getProbeCells (IntVector &)
void getProbeFaces (IntVector &)
Vector calc_courant (const VectorCellField &U, Scalar dt)
Typedef common matrix types
template<class type >
void scaleBCs (const MeshField< type, CELL > &, MeshField< type, CELL > &, Scalar)
template<class type >
void fixedBCs (const MeshField< type, CELL > &, MeshField< type, CELL > &)
template<class type >
void setNeumannBCs (MeshField< type, CELL > &)
Variables
VectorVertexField vC (false)
VectorFacetField fC (false)
VectorCellField cC (false)
VectorFacetField fN (false)
ScalarCellField cV (false)
ScalarFacetField fI (false)
ScalarFacetField fD (false)
ScalarCellField yWall (false)
IntFacetField FO (false)
IntFacetField FN (false)
Int * allFaces
Int ** faceIndices
IntVector probeCells
Int gBCSfield
Int gBFSfield
Int gALLfield
Vertices probePoints
vector< BasicBCondition * > AllBConditions
const Int DIRICHLET = Util::hash_function("DIRICHLET")
const Int NEUMANN = Util::hash_function("NEUMANN")
const Int ROBIN = Util::hash_function("ROBIN")
const Int SYMMETRY = Util::hash_function("SYMMETRY")
const Int CYCLIC = Util::hash_function("CYCLIC")
const Int GHOST = Util::hash_function("GHOST")
const Int POWER = Util::hash_function("POWER")
const Int LOG = Util::hash_function("LOG")
const Int PARABOLIC = Util::hash_function("PARABOLIC")
const Int INVERSE = Util::hash_function("INVERSE")
const Int ROUGHWALL = Util::hash_function("ROUGHWALL")
const Int CALC_DIRICHLET = Util::hash_function("CALC_DIRICHLET")
const Int CALC_NEUMANN = Util::hash_function("CALC_NEUMANN")
Global mesh object with its members
Int gNCells
Int gNFacets
Int gNVertices
MeshObject gMesh
string & gMeshName = gMesh.name
Vertices & gVertices = gMesh.mVertices
Facets & gFacets = gMesh.mFacets
Cells & gCells = gMesh.mCells
Boundaries & gBoundaries = gMesh.mBoundaries
IntVector & gFOC = gMesh.mFOC
IntVector & gFNC = gMesh.mFNC
IntVector & gFMC = gMesh.mFMC
BoolVector & gHasBoundary = gMesh.mHasBoundary
Int & gBCS = gMesh.mBCS
Cells & gFaceID = gMesh.mFaceID
InterBoundVector & gInterMesh = gMesh.mInterMesh
NodeVector & gAmrTree = gMesh.mAmrTree
VectorVector & gFC = gMesh.mFC
VectorVector & gCC = gMesh.mCC
VectorVector & gFN = gMesh.mFN
ScalarVector & gCV = gMesh.mCV
Vector amr_direction (0, 0, 0)
Int is_spherical = 0
Scalar sphere_radius = 6371220.0
Scalar sphere_height = 10000.0
bool pointInLine (const Vector &, const Vector &, const Vector &)
bool pointInPolygon (const VectorVector &, const IntVector &, const Vector &)
Detailed Description
Define some geometric fields
Boundary condition types
References to global mesh
Mesh data structure
Typedef Documentation
InterBoundVector
typedef std::vector<interBoundary> Mesh::InterBoundVector
Definition at line 71 of file mesh.h.
NodeVector
typedef std::vector<Node> Mesh::NodeVector
Definition at line 73 of file mesh.h.
PatchVector
typedef std::vector<Patch> Mesh::PatchVector
Definition at line 72 of file mesh.h.
Function Documentation
calc_courant()
Vector Mesh::calc_courant (const VectorCellField & U, Scalar dt)
Calculate global courant number
Definition at line 435 of file field.cpp.
References MP::allreduce(), cV, Controls::dt, mag(), MP::n_hosts, MP::OP_MAX, MP::OP_MIN, MP::OP_SUM, Scalar, and MeshField< type, entity >::size().
clearBC()
void Mesh::clearBC () inline
Clear list of BCs
Definition at line 272 of file field.h.
References AllBConditions, and forEach.
enroll()
void Mesh::enroll (Util::ParamList & params)
Enroll solver control parameters
Definition at line 498 of file field.cpp.
References Controls::amr_step, Controls::blend_factor, Controls::convection_scheme, Controls::dt, Controls::end_step, Controls::gravity, is_spherical, Controls::max_iterations, Controls::n_deferred, Controls::nonortho_scheme, DG::Nop, Controls::parallel_method, Controls::Preconditioner, Controls::print_time, probePoints, Controls::save_average, Controls::Solver, Controls::SOR_omega, sphere_height, sphere_radius, Controls::start_step, Controls::state, Controls::time_scheme, Controls::tolerance, Controls::TVDbruner, Controls::write_format, and Controls::write_interval.
findNearestCell()
Int Mesh::findNearestCell (const Vector & v)
Find nearest cell
Definition at line 383 of file field.cpp.
References cC, gBCSfield, and Scalar.
Referenced by getProbeCells().
findNearestFace()
Int Mesh::findNearestFace (const Vector & v)
Find nearest face
Definition at line 399 of file field.cpp.
References fC, forEach, and Scalar.
Referenced by getProbeFaces().
fixedBCs()
template<class type > void Mesh::fixedBCs (const MeshField< type, CELL > & src, MeshField< type, CELL > & dest)
Calculated dirichlet boundary condition
Definition at line 2735 of file field.h.
References AllBConditions, CALC_DIRICHLET, BasicBCondition::cIndex, BasicBCondition::cname, BasicBCondition::fIndex, MeshField< type, entity >::fIndex, BCondition< type >::fixed, BaseField::fName, forEach, and src().
getProbeCells()
void Mesh::getProbeCells (IntVector & probes)
Find nearest cells of probes
Definition at line 415 of file field.cpp.
References findNearestCell(), forEach, and probePoints.
Referenced by Iteration::Iteration().
getProbeFaces()
void Mesh::getProbeFaces (IntVector & probes)
Find nearest faces of probes
Definition at line 425 of file field.cpp.
References findNearestFace(), forEach, and probePoints.
Referenced by Prepare::probe().
initGeomMeshFields()
void Mesh::initGeomMeshFields (bool remove_empty)
Initialize geometric mesh fields
Definition at line 169 of file field.cpp.
References AllBConditions, allFaces, MeshField< type, entity >::allocate(), applyExplicitBCs(), BasicBCondition::bname, cC, cds(), BasicBCondition::cname, MeshField< type, entity >::construct(), cV, MeshField< type, entity >::deallocate(), dot(), DG::expand(), Mesh::interBoundary::f, faceIndices, fC, fD, fI, fN, FN, BaseField::fName, FO, forEach, forEachIt, forEachLglBoundX, forEachLglBoundY, forEachLglBoundZ, forEachLglX, forEachLglXY, forEachLglXZ, forEachLglY, forEachLglYZ, forEachLglZ, gALLfield, gBCS, gBCSfield, gBoundaries, gCC, gCells, gCV, gFacets, gFC, gFN, gFNC, gFOC, gInterMesh, gNCells, gNFacets, gNVertices, gVertices, INDEX4, DG::init_basis(), DG::init_geom(), BCondition< type >::init_indices(), mag(), Controls::MINIMUM, Controls::nonortho_scheme, DG::NP, DG::NPF, DG::NPMAT, DG::NPX, DG::NPY, DG::NPZ, Controls::OVER_RELAXED, PSID, ASYNC_COMM< T >::recv(), Scalar, ASYNC_COMM< T >::send(), BCondition< type >::value, vC, and yWall.
LoadMesh()
bool Mesh::LoadMesh (Int step_ = 0, bool remove_empty = true, bool extrude = true)
Load mesh
Definition at line 93 of file field.cpp.
Referenced by AmrIteration::AmrIteration(), Prepare::convertVTK(), Prepare::decomposeMesh(), AmrIteration::next(), Prepare::probe(), and Prepare::refineMesh().
pointInLine()
bool Mesh::pointInLine (const Vector & v, const Vector & v1, const Vector & v2)
Is point inside line segment ?
Definition at line 764 of file mesh.cpp.
References dot(), equal(), Scalar, Constants::XX, Constants::YY, and Constants::ZZ.
Referenced by Mesh::MeshObject::addVerticesToEdge(), Mesh::MeshObject::breakEdges(), Mesh::MeshObject::calcUnitNormal(), Mesh::MeshObject::mergeFacets(), Mesh::MeshObject::removeUnusedVertices(), and Mesh::MeshObject::straightenEdges().
pointInPolygon()
bool Mesh::pointInPolygon (const VectorVector & points, const IntVector & f, const Vector & C)
Is point inside convex polygon (face) ?
Definition at line 789 of file mesh.cpp.
References dot(), Controls::dt, equal(), forEach, mag(), Constants::PI, Scalar, and sum().
Referenced by Mesh::MeshObject::refineCell().
read_fields()
void Mesh::read_fields (Int step)
Read all fields
Definition at line 460 of file field.cpp.
References forEachCellField.
Referenced by Iteration::Iteration(), and Prepare::readFields().
remove_fields()
void Mesh::remove_fields ()
Remove all fields
Definition at line 466 of file field.cpp.
References BaseField::allFields, forEachCellField, forEachCellMatField, forEachFacetField, and forEachVertexField.
scaleBCs()
template<class type > void Mesh::scaleBCs (const MeshField< type, CELL > & src, MeshField< type, CELL > & dest, Scalar psi)
Scale boundary condition by a constant
Definition at line 2754 of file field.h.
References AllBConditions, CALC_DIRICHLET, BasicBCondition::cIndex, BasicBCondition::cname, CYCLIC, BasicBCondition::fIndex, MeshField< type, entity >::fIndex, BCondition< type >::fixed, BaseField::fName, forEach, NEUMANN, DG::psi, ROBIN, src(), SYMMETRY, BCondition< type >::tvalue, and BCondition< type >::value.
setNeumannBCs()
template<class type > void Mesh::setNeumannBCs (MeshField< type, CELL > & p)
Set NEUMANN boundary condition for all
Definition at line 2785 of file field.h.
References AllBConditions, BasicBCondition::cIndex, BasicBCondition::cname, BasicBCondition::fIndex, BaseField::fName, forEachIt, gBoundaries, Util::hash_function(), and NEUMANN.
write_fields()
void Mesh::write_fields (Int step)
Write all fields
Definition at line 454 of file field.cpp.
References forEachCellField.
Referenced by Iteration::end(), and Iteration::next().
Variable Documentation
AllBConditions
std::vector< BasicBCondition * > Mesh::AllBConditions
List of all boundary conditions
Definition at line 32 of file field.cpp.
Referenced by applyExplicitBCs(), applyImplicitBCs(), clearBC(), fillBCs(), fixedBCs(), EddyViscosity_Model::FixNearWallValues(), initGeomMeshFields(), scaleBCs(), setNeumannBCs(), and EddyViscosity_Model::setWallEddyMu().
allFaces
Int * Mesh::allFaces
Definition at line 21 of file field.cpp.
Referenced by div_flux(), div_flux_implicit(), fillBCs(), grad_flux(), initGeomMeshFields(), lap(), SolveT(), sum(), and sum_flux().
amr_direction
Vector Mesh::amr_direction (0 , 0 , 0)
Direction of AMR
Definition at line 243 of file mesh.h.
Referenced by Mesh::MeshObject::refineFacet(), and Prepare::refineMesh().
CALC_DIRICHLET
const Int Mesh::CALC_DIRICHLET = Util::hash_function("CALC_DIRICHLET")
Definition at line 136 of file field.h.
Referenced by applyExplicitBCs(), fixedBCs(), and scaleBCs().
CALC_NEUMANN
const Int Mesh::CALC_NEUMANN = Util::hash_function("CALC_NEUMANN")
Definition at line 137 of file field.h.
cC
VectorCellField Mesh::cC (false)
Coordinates of cell centers
Definition at line 1326 of file field.h.
Referenced by applyExplicitBCs(), MixingLength_Model::applyWallFunction(), KX_Model::applyWallFunction(), div_flux_implicit(), findNearestCell(), gather_non_conforming(), DG::init_geom(), initGeomMeshFields(), lap(), MeshField< type, entity >::refineField(), scatter_non_conforming(), and Vtk::write_vtk().
cV
ScalarCellField Mesh::cV (false)
Cell volumes
Definition at line 1328 of file field.h.
Referenced by calc_courant(), LES_Model::calcLengthScale(), Prepare::calcQOI(), ddt(), ddt2(), div(), divf(), gradf(), DG::init_geom(), initGeomMeshFields(), src(), and srcf().
CYCLIC
const Int Mesh::CYCLIC = Util::hash_function("CYCLIC")
Definition at line 129 of file field.h.
Referenced by applyExplicitBCs(), applyImplicitBCs(), and scaleBCs().
DIRICHLET
const Int Mesh::DIRICHLET = Util::hash_function("DIRICHLET")
Definition at line 125 of file field.h.
Referenced by applyExplicitBCs().
faceIndices
Int ** Mesh::faceIndices
Definition at line 22 of file field.cpp.
Referenced by div_flux(), div_flux_implicit(), fillBCs(), grad_flux(), initGeomMeshFields(), lap(), SolveT(), sum(), and sum_flux().
fC
VectorFacetField Mesh::fC (false)
Coordinates of face centers
Definition at line 1325 of file field.h.
Referenced by cds(), div_flux_implicit(), findNearestFace(), initGeomMeshFields(), and Prepare::probe().
fD
ScalarFacetField Mesh::fD (false)
Diffusivity coefficient
Definition at line 1330 of file field.h.
Referenced by div_flux_implicit(), initGeomMeshFields(), and lap().
fI
ScalarFacetField Mesh::fI (false)
Facet interpolation factors
Definition at line 1329 of file field.h.
Referenced by cds(), div_flux_implicit(), and initGeomMeshFields().
fN
VectorFacetField Mesh::fN (false)
Facet normals
Definition at line 1327 of file field.h.
Referenced by applyExplicitBCs(), MixingLength_Model::applyWallFunction(), KX_Model::applyWallFunction(), div_flux(), flx(), grad_flux(), initGeomMeshFields(), lap(), Prepare::probe(), and rusanov().
FN
IntFacetField Mesh::FN (false)
Facet neighbors
Definition at line 1333 of file field.h.
Referenced by applyExplicitBCs(), applyImplicitBCs(), MixingLength_Model::applyWallFunction(), KX_Model::applyWallFunction(), cds(), div_flux(), div_flux_implicit(), fillBCs(), grad_flux(), DG::init_geom(), initGeomMeshFields(), lap(), Prepare::probe(), ASYNC_COMM< T >::recv(), scatter_non_conforming(), SolveT(), sum(), and sum_flux().
FO
IntFacetField Mesh::FO (false)
Facet owners
Definition at line 1332 of file field.h.
Referenced by applyExplicitBCs(), applyImplicitBCs(), MixingLength_Model::applyWallFunction(), KX_Model::applyWallFunction(), div_flux(), div_flux_implicit(), fillBCs(), EddyViscosity_Model::FixNearWallValues(), grad_flux(), DG::init_geom(), initGeomMeshFields(), lap(), Prepare::probe(), scatter_non_conforming(), ASYNC_COMM< T >::send(), SolveT(), sum(), and sum_flux().
gALLfield
Int Mesh::gALLfield
Total number of nodes
Definition at line 26 of file field.cpp.
Referenced by applyExplicitBCs(), applyImplicitBCs(), cds(), div_flux(), div_flux_implicit(), fillBCs(), grad_flux(), DG::init_geom(), initGeomMeshFields(), lap(), sum(), and sum_flux().
gAmrTree
NodeVector & Mesh::gAmrTree = gMesh.mAmrTree
Definition at line 24 of file mesh.cpp.
gBCS
Int & Mesh::gBCS = gMesh.mBCS
Definition at line 21 of file mesh.cpp.
Referenced by Prepare::decomposeIndex(), Prepare::decomposeMesh(), Prepare::decomposeMetis(), Prepare::decomposeXYZ(), div(), divf(), fillBCs(), getRHS(), gradf(), DG::init_geom(), initGeomMeshFields(), lap(), mul(), mult(), Prepare::refineMesh(), SolveT(), and Vtk::write_vtk().
gBCSfield
Int Mesh::gBCSfield
Total number of nodes excluding boundary cells
Definition at line 24 of file field.cpp.
Referenced by cds(), findNearestCell(), getResidual(), initGeomMeshFields(), MeshField< type, entity >::refineField(), SolveT(), Vtk::write_vtk(), and MeshField< type, entity >::writeVtkCellAll().
gBFSfield
Int Mesh::gBFSfield
Definition at line 25 of file field.cpp.
gBoundaries
Boundaries & Mesh::gBoundaries = gMesh.mBoundaries
Definition at line 16 of file mesh.cpp.
Referenced by applyExplicitBCs(), BCondition< type >::init_indices(), initGeomMeshFields(), and setNeumannBCs().
gCC
VectorVector & Mesh::gCC = gMesh.mCC
Definition at line 26 of file mesh.cpp.
Referenced by Prepare::decomposeXYZ(), initGeomMeshFields(), and Prepare::refineMesh().
gCells
Cells & Mesh::gCells = gMesh.mCells
Definition at line 15 of file mesh.cpp.
Referenced by MeshField< type, entity >::allocate(), MeshField< type, entity >::construct(), Prepare::decomposeMesh(), Prepare::decomposeMetis(), gather_non_conforming(), DG::init_geom(), initGeomMeshFields(), Prepare::refineMesh(), scatter_non_conforming(), and Vtk::write_vtk().
gCV
ScalarVector & Mesh::gCV = gMesh.mCV
Definition at line 28 of file mesh.cpp.
Referenced by initGeomMeshFields(), MeshField< type, entity >::refineField(), and Prepare::refineMesh().
gFaceID
Cells & Mesh::gFaceID = gMesh.mFaceID
Definition at line 22 of file mesh.cpp.
Referenced by gather_non_conforming(), DG::init_geom(), and scatter_non_conforming().
gFacets
Facets & Mesh::gFacets = gMesh.mFacets
Definition at line 14 of file mesh.cpp.
Referenced by MeshField< type, entity >::allocate(), applyExplicitBCs(), cds(), Prepare::decomposeMesh(), DG::init_geom(), initGeomMeshFields(), Mesh::MeshObject::refineMesh(), and Vtk::write_vtk().
gFC
VectorVector & Mesh::gFC = gMesh.mFC
Definition at line 25 of file mesh.cpp.
Referenced by gather_non_conforming(), initGeomMeshFields(), and scatter_non_conforming().
gFMC
IntVector & Mesh::gFMC = gMesh.mFMC
Definition at line 19 of file mesh.cpp.
Referenced by gather_non_conforming(), DG::init_geom(), and scatter_non_conforming().
gFN
VectorVector & Mesh::gFN = gMesh.mFN
Definition at line 27 of file mesh.cpp.
Referenced by initGeomMeshFields().
gFNC
IntVector & Mesh::gFNC = gMesh.mFNC
Definition at line 18 of file mesh.cpp.
Referenced by Prepare::decomposeMesh(), Prepare::decomposeMetis(), gather_non_conforming(), DG::init_geom(), initGeomMeshFields(), and scatter_non_conforming().
gFOC
IntVector & Mesh::gFOC = gMesh.mFOC
Definition at line 17 of file mesh.cpp.
Referenced by Prepare::decomposeMesh(), Prepare::decomposeMetis(), gather_non_conforming(), initGeomMeshFields(), and scatter_non_conforming().
gHasBoundary
BoolVector & Mesh::gHasBoundary = gMesh.mHasBoundary
Definition at line 20 of file mesh.cpp.
Referenced by getRHS(), mul(), and mult().
GHOST
const Int Mesh::GHOST = Util::hash_function("GHOST")
Definition at line 130 of file field.h.
Referenced by applyExplicitBCs(), and applyImplicitBCs().
gInterMesh
InterBoundVector & Mesh::gInterMesh = gMesh.mInterMesh
Definition at line 23 of file mesh.cpp.
Referenced by applyExplicitBCs(), fillBCs(), initGeomMeshFields(), ASYNC_COMM< T >::recv(), ASYNC_COMM< T >::send(), and SolveT().
gMesh
MeshObject Mesh::gMesh
Definition at line 11 of file mesh.cpp.
Referenced by Prepare::decomposeMesh(), and DG::init_geom().
gMeshName
std::string & Mesh::gMeshName = gMesh.name
Definition at line 12 of file mesh.cpp.
Referenced by Prepare::decomposeMesh(), and Vtk::write_vtk().
gNCells
Int Mesh::gNCells
Definition at line 27 of file field.cpp.
Referenced by div_flux(), div_flux_implicit(), fillBCs(), grad_flux(), initGeomMeshFields(), lap(), sum(), and sum_flux().
gNFacets
Int Mesh::gNFacets
Definition at line 28 of file field.cpp.
Referenced by div_flux_implicit(), gather_non_conforming(), initGeomMeshFields(), and scatter_non_conforming().
gNVertices
Int Mesh::gNVertices
Definition at line 29 of file field.cpp.
Referenced by initGeomMeshFields().
gVertices
Vertices & Mesh::gVertices = gMesh.mVertices
Definition at line 13 of file mesh.cpp.
Referenced by MeshField< type, entity >::allocate(), cds(), Prepare::decomposeMesh(), Prepare::decomposeXYZ(), DG::init_geom(), initGeomMeshFields(), Mesh::MeshObject::refineMesh(), and Vtk::write_vtk().
INVERSE
const Int Mesh::INVERSE = Util::hash_function("INVERSE")
Definition at line 134 of file field.h.
Referenced by applyExplicitBCs().
is_spherical
Int Mesh::is_spherical = 0
Mesh is spherical
Definition at line 31 of file mesh.cpp.
Referenced by Mesh::MeshObject::calcGeometry(), enroll(), Mesh::MeshObject::ExtrudeMesh(), Mesh::MeshObject::refineFacet(), and Prepare::refineMesh().
LOG
const Int Mesh::LOG = Util::hash_function("LOG")
Definition at line 132 of file field.h.
Referenced by applyExplicitBCs().
NEUMANN
const Int Mesh::NEUMANN = Util::hash_function("NEUMANN")
Definition at line 126 of file field.h.
Referenced by applyExplicitBCs(), applyImplicitBCs(), fillBCs(), scaleBCs(), and setNeumannBCs().
PARABOLIC
const Int Mesh::PARABOLIC = Util::hash_function("PARABOLIC")
Definition at line 133 of file field.h.
Referenced by applyExplicitBCs().
POWER
const Int Mesh::POWER = Util::hash_function("POWER")
Definition at line 131 of file field.h.
Referenced by applyExplicitBCs().
probeCells
IntVector Mesh::probeCells
List of cell IDs for probing values
Definition at line 23 of file field.cpp.
Referenced by MeshField< type, entity >::initTimeSeries(), Iteration::Iteration(), and MeshField< type, entity >::updateTimeSeries().
probePoints
Vertices Mesh::probePoints
List of probing points
Definition at line 31 of file field.cpp.
Referenced by enroll(), getProbeCells(), getProbeFaces(), and Prepare::probe().
ROBIN
const Int Mesh::ROBIN = Util::hash_function("ROBIN")
Definition at line 127 of file field.h.
Referenced by applyExplicitBCs(), applyImplicitBCs(), and scaleBCs().
ROUGHWALL
const Int Mesh::ROUGHWALL = Util::hash_function("ROUGHWALL")
Definition at line 135 of file field.h.
Referenced by applyExplicitBCs(), EddyViscosity_Model::FixNearWallValues(), and EddyViscosity_Model::setWallEddyMu().
sphere_height
Scalar Mesh::sphere_height = 10000.0
Height of the sphere
Definition at line 33 of file mesh.cpp.
Referenced by enroll(), and Mesh::MeshObject::ExtrudeMesh().
sphere_radius
Scalar Mesh::sphere_radius = 6371220.0
Radius of the sphere
Definition at line 32 of file mesh.cpp.
Referenced by enroll(), and Mesh::MeshObject::ExtrudeMesh().
SYMMETRY
const Int Mesh::SYMMETRY = Util::hash_function("SYMMETRY")
Definition at line 128 of file field.h.
Referenced by applyExplicitBCs(), fillBCs(), and scaleBCs().
vC
VectorVertexField Mesh::vC (false)
Coordinates of vertices
Definition at line 1324 of file field.h.
Referenced by applyExplicitBCs(), and initGeomMeshFields().
yWall
ScalarCellField Mesh::yWall (false)
Wall distance
Definition at line 1331 of file field.h.
Referenced by MixingLength_Model::calcEddyViscosity(), and initGeomMeshFields().