NebulaSEM: Util Namespace Reference
Util Namespace Reference
Classes
class ofstream_bin
class ifstream_bin
struct compare_pair_second
struct Option
struct BoolOption
class Parameters
struct ParamList
Functions
template<class T1 , class T2 , typename Ts >
Ts & operator<< (Ts &os, const std::pair< T1, T2 > &p)
template<class T1 , class T2 , typename Ts >
Ts & operator>> (Ts &is, std::pair< T1, T2 > &p)
template<class T , typename Ts >
Ts & operator<< (Ts &os, const std::vector< T > &p)
template<class T , typename Ts >
Ts & operator>> (Ts &is, std::vector< T > &p)
template<typename Ts >
Ts & operator<< (Ts &os, const std::vector< Int > &p)
template<class T1 , class T2 , typename Ts >
Ts & operator<< (Ts &os, const std::map< T1, T2 > &p)
template<class T1 , class T2 , typename Ts >
Ts & operator>> (Ts &is, std::map< T1, T2 > &p)
Int hash_function (std::string s)
int nextc (std::istream &)
int compare (std::string &s1, std::string s2)
void read_params (std::istream &, bool print, std::string block="")
Function Documentation
compare()
int Util::compare (std::string & s1, std::string s2) inline
Compare two strings case-insensitive
Definition at line 240 of file util.h.
Referenced by BaseField::findField(), Util::Option::getID(), and read_params().
hash_function()
Int Util::hash_function (std::string s)
String hash function
Definition at line 10 of file util.cpp.
Referenced by MeshField< type, entity >::construct(), BCondition< type >::init_indices(), and Mesh::setNeumannBCs().
nextc()
int Util::nextc (std::istream & is)
Read next character
Definition at line 18 of file util.cpp.
Referenced by read_params(), and Mesh::MeshObject::readMshMesh().
operator<<() [1/4]
template<class T1 , class T2 , typename Ts > Ts& Util::operator<< (Ts & os, const std::map< T1, T2 > & p)
std::map reader
Definition at line 144 of file util.h.
References forEachIt.
operator<<() [2/4]
template<class T1 , class T2 , typename Ts > Ts& Util::operator<< (Ts & os, const std::pair< T1, T2 > & p)
std::pair reader
Definition at line 90 of file util.h.
operator<<() [3/4]
template<typename Ts > Ts& Util::operator<< (Ts & os, const std::vector< Int > & p)
std::vector writer for integers
Definition at line 127 of file util.h.
operator<<() [4/4]
template<class T , typename Ts > Ts& Util::operator<< (Ts & os, const std::vector< T > & p)
std::vector reader
Definition at line 104 of file util.h.
References forEach.
operator>>() [1/3]
template<class T1 , class T2 , typename Ts > Ts& Util::operator>> (Ts & is, std::map< T1, T2 > & p)
std::map writer
Definition at line 154 of file util.h.
References forEachIt.
operator>>() [2/3]
template<class T1 , class T2 , typename Ts > Ts& Util::operator>> (Ts & is, std::pair< T1, T2 > & p)
std::pair writer
Definition at line 97 of file util.h.
operator>>() [3/3]
template<class T , typename Ts > Ts& Util::operator>> (Ts & is, std::vector< T > & p)
std::vector writer
Definition at line 114 of file util.h.
References forEach.
read_params()
void Util::read_params (std::istream & is, bool output, std::string block = "")
Reads parameters
Definition at line 32 of file util.cpp.
References compare(), nextc(), READ, and Util::ParamList::read().
Referenced by Util::ParamList::read().