NebulaSEM: /home/daniel/storage/NebulaSEM/src/solvers/solve.h File Reference
solve.h File Reference
#include "field.h"
Functions
void Solve (const MeshMatrix< Scalar > &)
void Solve (const MeshMatrix< Vector > &)
void Solve (const MeshMatrix< STensor > &)
void Solve (const MeshMatrix< Tensor > &)
Function Documentation
Solve() [1/4]
void Solve (const MeshMatrix< Scalar > & A)
Definition at line 582 of file solve.cpp.
References SOLVE.
Referenced by KE_Model::solve(), KW_Model::solve(), REALIZABLE_KE_Model::solve(), and RNG_KE_Model::solve().
Solve() [2/4]
void Solve (const MeshMatrix< STensor > & A)
Definition at line 588 of file solve.cpp.
References SOLVE.
Solve() [3/4]
void Solve (const MeshMatrix< Tensor > & A)
Definition at line 591 of file solve.cpp.
References SOLVE.
Solve() [4/4]
void Solve (const MeshMatrix< Vector > & A)
Definition at line 585 of file solve.cpp.
References SOLVE.