NebulaSEM: /home/daniel/storage/NebulaSEM/src/solvers/solve.cpp File Reference
solve.cpp File Reference
#include "solve.h"
Macros
#define JacobiSweep()
#define Sweep_(X, B, ci)
#define ForwardSweep(X, B)
#define Substitute_(X, B, ci, forw, tr)
#define ForwardSub(X, B, TR)
#define BackwardSub(X, B, TR)
#define DiagSub(X, B)
#define precondition_(R, Z, TR)
#define precondition(R, Z) precondition_(R,Z,0)
#define preconditionT(R, Z) precondition_(R,Z,1)
#define Taxpy(Y, I, X, alpha_)
#define Tdot(X, Y, sumt)
#define REDUCE(typ, var)
#define CALC_RESID()
#define SOLVE()
Functions
template<class type , ENTITY entity>
Scalar getResidual (const MeshField< type, entity > &r, const MeshField< type, entity > &cF, bool sync)
template<class T1 , class T2 , class T3 >
void SolveT (const MeshMatrix< T1, T2, T3 > &M)
template<class T1 , class T2 , class T3 >
void SolveTexplicit (const MeshMatrix< T1, T2, T3 > &M)
void Solve (const MeshMatrix< Scalar > &A)
void Solve (const MeshMatrix< Vector > &A)
void Solve (const MeshMatrix< STensor > &A)
void Solve (const MeshMatrix< Tensor > &A)
Macro Definition Documentation
BackwardSub
#define BackwardSub (X, B, TR)
Value:
    {                                                   \
    _Pragma("acc loop seq")                                                     \
    for(int ci = gBCS - 1; ci >= 0; ci--)    {                                  \
        forEachLglR(ii,jj,kk)                                                   \
            Substitute_(X,B,ci,false,TR);                                       \
    }                                                                           \
}
CALC_RESID
#define CALC_RESID ()
Value:
    {                                                          \
    r = M.Su - mul(M,cF);                                                       \
    _Pragma("omp parallel for")                                                 \
    _Pragma("acc parallel loop")                                                \
    forEachS(r,k,gBCSfield)                                                     \
        r[k] = T3(0);                                                           \
    precondition(r,AP);                                                         \
    _Pragma("omp parallel for")                                                 \
    _Pragma("acc parallel loop")                                                \
    forEachS(AP,k,gBCSfield)                                                    \
        AP[k] = T3(0);                                                          \
    res = getResidual(AP,cF,sync);                                              \
    if(Controls::Solver == Controls::PCG) {                                     \
        Tdot(r,AP,o_rr);                                                        \
        REDUCE(T1,o_rr);                                                        \
        p = AP;                                                                 \
        if(!(M.flags & M.SYMMETRIC)) {                                          \
            r1 = r;                                                             \
            p1 = p;                                                             \
        }                                                                       \
    }                                                                           \
}
DiagSub
#define DiagSub (X, B)
Value:
    {                                                          \
    _Pragma("omp parallel for")                                                 \
    _Pragma("acc parallel loop")                                                \
    for(Int i = 0;i < gBCSfield;i++)                                            \
        X[i] = B[i] * iD[i];                                                    \
}
ForwardSub
#define ForwardSub (X, B, TR)
Value:
    {                                                    \
    _Pragma("acc loop seq")                                                     \
    for(Int ci = 0;ci < gBCS;ci++)  {                                           \
        forEachLgl(ii,jj,kk)                                                    \
            Substitute_(X,B,ci,true,TR);                                        \
    }                                                                           \
}
ForwardSweep
#define ForwardSweep (X, B)
Value:
    {                                                     \
    ASYNC_COMM<T1> comm(&X[0]);                                                 \
    comm.send();                                                                \
    _Pragma("omp parallel for")                                                 \
    _Pragma("acc parallel loop copyin(gBCS,gHasBoundary,M)")                    \
    for(Int ci = 0;ci < gBCS;ci++) {                                            \
        if(!gHasBoundary[ci]) Sweep_(X,B,ci);                                   \
    }                                                                           \
    comm.recv();                                                                \
    _Pragma("omp parallel for")                                                 \
    _Pragma("acc parallel loop copyin(gBCS,gHasBoundary,M)")                    \
    for(Int ci = 0;ci < gBCS;ci++) {                                            \
        if(gHasBoundary[ci]) Sweep_(X,B,ci);                                    \
    }                                                                           \
}
JacobiSweep
#define JacobiSweep ()
Value:
    {                                                         \
    cF = iD * getRHS(M,*(M.cF),sync);                                           \
}
precondition
#define precondition (R, Z) precondition_(R,Z,0)
precondition_
#define precondition_ (R, Z, TR)
Value:
    {                                                 \
    using namespace Controls;                                                   \
    if(Preconditioner == Controls::NOPR) {                                      \
        Z = R;                                                                  \
    } else if(Preconditioner == Controls::DIAG) {                               \
        DiagSub(Z,R);                                                           \
    } else {                                                                    \
        if(Controls::Solver == Controls::PCG) {                                 \
            ForwardSub(Z,R,TR);                                                 \
            Z = Z * D;                                                          \
            BackwardSub(Z,Z,TR);                                                \
        }                                                                       \
    }                                                                           \
}
preconditionT
#define preconditionT (R, Z) precondition_(R,Z,1)
REDUCE
#define REDUCE (typ, var)
Value:
    if(sync) {                                              \
    typ t;                                                                      \
    MP::allreduce(&var,&t,1,MP::OP_SUM);                                        \
    var = t;                                                                    \
}
SOLVE
#define SOLVE ()
Value:
    {                           \
    applyImplicitBCs(A);                    \
    if(A.flags & A.DIAGONAL)                \
        SolveTexplicit(A);                  \
    else                                    \
        SolveT(A);                          \
    applyExplicitBCs(*A.cF,true);           \
}
Definition at line 574 of file solve.cpp.
Substitute_
#define Substitute_ (X, B, ci, forw, tr)
Sweep_
#define Sweep_ (X, B, ci)
Taxpy
#define Taxpy (Y, I, X, alpha_)
Value:
    {                                                   \
    _Pragma("omp parallel for")                                                 \
    _Pragma("acc parallel loop copyin(cF)")                                     \
    for(Int i = 0;i < gBCSfield;i++)                                            \
        Y[i] = I[i] + X[i] * alpha_;                                            \
}
Tdot
#define Tdot (X, Y, sumt)
Value:
    {                                                        \
    T3 sum = T3(0);                                                             \
    Scalar* CP = addr(sum);                                                     \
    constexpr Int TYPE_SIZE = sizeof(T3) / sizeof(Scalar);                      \
    (void)TYPE_SIZE;                                                            \
    _Pragma("omp parallel for reduction(+:sum)")                                \
    _Pragma("acc parallel loop reduction(+:CP[0:TYPE_SIZE])")                   \
    for(Int i = 0;i < gBCSfield;i++)                                            \
        sum += X[i] * Y[i];                                                     \
    sumt = sum;                                                                 \
}
Function Documentation
getResidual()
template<class type , ENTITY entity> Scalar getResidual (const MeshField< type, entity > & r, const MeshField< type, entity > & cF, bool sync)
Calculate global residual
Definition at line 11 of file solve.cpp.
References addr(), MP::allreduce(), Mesh::gBCSfield, mag(), MP::OP_SUM, Scalar, and sdiv().
Referenced by SolveT().
Solve() [1/4]
void Solve (const MeshMatrix< Scalar > & A)
Definition at line 582 of file solve.cpp.
References SOLVE.
Referenced by KE_Model::solve(), KW_Model::solve(), REALIZABLE_KE_Model::solve(), and RNG_KE_Model::solve().
Solve() [2/4]
void Solve (const MeshMatrix< STensor > & A)
Definition at line 588 of file solve.cpp.
References SOLVE.
Solve() [3/4]
void Solve (const MeshMatrix< Tensor > & A)
Definition at line 591 of file solve.cpp.
References SOLVE.
Solve() [4/4]
void Solve (const MeshMatrix< Vector > & A)
Definition at line 585 of file solve.cpp.
References SOLVE.
SolveT()
template<class T1 , class T2 , class T3 > void SolveT (const MeshMatrix< T1, T2, T3 > & M)
Solve a system of linear equations Ax=B
Definition at line 39 of file solve.cpp.
References MeshMatrix< T1, T2, T3 >::adg, Mesh::allFaces, MeshField< type, entity >::allocate(), MeshMatrix< T1, T2, T3 >::ann, MeshMatrix< T1, T2, T3 >::ano, MeshMatrix< T1, T2, T3 >::ap, Controls::BLOCKED, CALC_RESID, MeshMatrix< T1, T2, T3 >::cF, Controls::DIAG, MeshMatrix< T1, T2, T3 >::DIAGONAL, Controls::DILU, MP::END, Mesh::interBoundary::f, Mesh::faceIndices, MP::FIELD, MeshMatrix< T1, T2, T3 >::flags, Mesh::FN, Mesh::FO, forEach, forEachLgl, forEachLglX, forEachLglY, forEachLglZ, ForwardSweep, Mesh::interBoundary::from, Mesh::gBCS, Mesh::gBCSfield, getResidual(), Mesh::gInterMesh, INDEX4, INDEX_TX, INDEX_TY, INDEX_TZ, INDEX_X, INDEX_Y, INDEX_Z, MP::iprobe(), isBoundary, Controls::JACOBI, JacobiSweep, Controls::max_iterations, mul(), mult(), Controls::NOPR, DG::NPF, DG::NPMAT, Controls::parallel_method, Controls::PCG, precondition, Controls::Preconditioner, preconditionT, MP::printH(), MP::printOn, MP::recieve(), REDUCE, Scalar, sdiv(), MP::send(), Controls::Solver, Controls::SOR, Controls::SOR_omega, Controls::SSOR, MeshMatrix< T1, T2, T3 >::Su, MeshMatrix< T1, T2, T3 >::SYMMETRIC, Taxpy, Tdot, Mesh::interBoundary::to, and Controls::tolerance.
SolveTexplicit()
template<class T1 , class T2 , class T3 > void SolveTexplicit (const MeshMatrix< T1, T2, T3 > & M)
Solve a diagonal system
Definition at line 563 of file solve.cpp.
References MeshMatrix< T1, T2, T3 >::ap, MeshMatrix< T1, T2, T3 >::cF, MP::print(), MP::printH(), MP::printOn, and MeshMatrix< T1, T2, T3 >::Su.