NebulaSEM: LawOfWall Struct Reference
LawOfWall Struct Reference
#include <field.h>
Public Member Functions
LawOfWall ()
void init ()
Scalar getUstar (Scalar nu, Scalar U, Scalar y)
Scalar getUp (Scalar ustar, Scalar nu, Scalar yp)
Public Attributes
Scalar E
Scalar kappa
Scalar ks
Scalar cks
Scalar yLog
Detailed Description
Model for flow close to the wall (Law of the wall).
1 -> Viscous layer
2 -> Buffer layer
3 -> Log-law layer
The wall function model is modified for rough surfaces
using Cebecci and Bradshaw formulae.
Definition at line 76 of file field.h.
Constructor & Destructor Documentation
LawOfWall()
LawOfWall::LawOfWall () inline
Definition at line 84 of file field.h.
References init().
Member Function Documentation
getUp()
Scalar LawOfWall::getUp (Scalar ustar, Scalar nu, Scalar yp) inline
Definition at line 105 of file field.h.
References cks, E, kappa, ks, Scalar, and yLog.
Referenced by MixingLength_Model::applyWallFunction(), and KX_Model::applyWallFunction().
getUstar()
Scalar LawOfWall::getUstar (Scalar nu, Scalar U, Scalar y) inline
Definition at line 97 of file field.h.
References E, kappa, and Scalar.
Referenced by MixingLength_Model::applyWallFunction(), and KX_Model::applyWallFunction().
init()
void LawOfWall::init () inline
Definition at line 92 of file field.h.
References E, kappa, and yLog.
Referenced by LawOfWall().
Member Data Documentation
cks
Scalar LawOfWall::cks
Constant multiply the dimensionless ks+
Definition at line 80 of file field.h.
Referenced by getUp().
E
Scalar LawOfWall::E
Constant multiplying the dimensionless wall distance y+
Definition at line 77 of file field.h.
Referenced by getUp(), getUstar(), and init().
kappa
Scalar LawOfWall::kappa
Von karman constant
Definition at line 78 of file field.h.
Referenced by KX_Model::applyWallFunction(), getUp(), getUstar(), and init().
ks
Scalar LawOfWall::ks
Sand grain roughness, 0 for smooth wall
Definition at line 79 of file field.h.
Referenced by getUp().
yLog
Scalar LawOfWall::yLog
Definition at line 82 of file field.h.
Referenced by getUp(), and init().
The documentation for this struct was generated from the following file:
/home/daniel/storage/NebulaSEM/src/field/field.h