NebulaSEM: EddyViscosity_Model Struct Reference
EddyViscosity_Model Struct Reference abstract
#include <turbulence.h>
Public Types
enum Model { SMAGORNSKY , BALDWIN , KATO }
enum WallModel { NONE , STANDARD , LAUNDER }
Public Member Functions
EddyViscosity_Model (VectorCellField &tU, VectorCellField &tFc, ScalarFacetField &tF, ScalarCellField &trho, ScalarCellField &tmu)
virtual void enroll ()
virtual void calcEddyViscosity (const TensorCellField &gradU)=0
virtual ScalarCellField getTurbVisc ()
virtual VectorCellField getExplicitStresses ()
virtual STensorCellField getReynoldsStress ()
ScalarCellField getS2 (const TensorCellField &gradU)
void FixNearWallValues (ScalarCellMatrix &M)
void setWallEddyMu ()
virtual void applyWallFunction (Int f, LawOfWall &low)=0
Public Member Functions inherited from Turbulence_Model
Turbulence_Model (VectorCellField &tU, VectorCellField &tFc, ScalarFacetField &tF, ScalarCellField &trho, ScalarCellField &tmu)
virtual ~Turbulence_Model ()
virtual void solve ()
STensorCellField getViscousStress ()
virtual ScalarCellField getK ()
Public Attributes
ScalarCellField eddy_mu
Model modelType
WallModel wallModel
Public Attributes inherited from Turbulence_Model
VectorCellField & U
VectorCellField & Fc
ScalarFacetField & F
ScalarCellField & rho
ScalarCellField & mu
Util::ParamList params
bool writeStress
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_Model
static bool needWallDist ()
static void RegisterTable (Util::ParamList &params)
static Turbulence_Model * Select (VectorCellField &U, VectorCellField &Fc, ScalarFacetField &F, ScalarCellField &rho, ScalarCellField &mu)
Static Public Attributes inherited from Turbulence_Model
static Int turb_model = 2
static bool bneedWallDist = false
Detailed Description
Eddy viscosity models based on Boussinesq's assumption that the action of Reynolds and Viscous stress are similar.
Definition at line 122 of file turbulence.h.
Member Enumeration Documentation
Model
enum EddyViscosity_Model::Model
Enumerator
SMAGORNSKY
BALDWIN
KATO
Definition at line 124 of file turbulence.h.
WallModel
enum EddyViscosity_Model::WallModel
Enumerator
NONE
STANDARD
LAUNDER
Definition at line 127 of file turbulence.h.
Constructor & Destructor Documentation
EddyViscosity_Model()
EddyViscosity_Model::EddyViscosity_Model (VectorCellField & tU, VectorCellField & tFc, ScalarFacetField & tF, ScalarCellField & trho, ScalarCellField & tmu) inline
Eddy viscosity model constructor
Definition at line 134 of file turbulence.h.
Member Function Documentation
applyWallFunction()
virtual void EddyViscosity_Model::applyWallFunction (Int f, LawOfWall & low) pure virtual
Apply wall function
Implemented in KX_Model, and MixingLength_Model.
calcEddyViscosity()
virtual void EddyViscosity_Model::calcEddyViscosity (const TensorCellField & gradU) pure virtual
Calculate eddy viscosity
Implemented in KX_Model, RNG_KE_Model, REALIZABLE_KE_Model, and MixingLength_Model.
enroll()
virtual void EddyViscosity_Model::enroll () inline virtual
Enroll options
Reimplemented from Turbulence_Model.
Reimplemented in KX_Model, RNG_KE_Model, REALIZABLE_KE_Model, MixingLength_Model, LES_Model, KW_Model, and KE_Model.
Definition at line 142 of file turbulence.h.
References Turbulence_Model::enroll(), and Turbulence_Model::params.
Referenced by MixingLength_Model::enroll(), and KX_Model::enroll().
FixNearWallValues()
void EddyViscosity_Model::FixNearWallValues (ScalarCellMatrix & M) inline
Fix near wall cell values
Definition at line 187 of file turbulence.h.
References Mesh::AllBConditions, BasicBCondition::bdry, MeshMatrix< T1, T2, T3 >::cF, BasicBCondition::cIndex, BasicBCondition::fIndex, MeshField< type, entity >::fIndex, Mesh::FO, forEach, and Mesh::ROUGHWALL.
Referenced by KE_Model::solve(), KW_Model::solve(), REALIZABLE_KE_Model::solve(), and RNG_KE_Model::solve().
getExplicitStresses()
virtual VectorCellField EddyViscosity_Model::getExplicitStresses () inline virtual
Calculate explicit stresses V + R
Reimplemented from Turbulence_Model.
Definition at line 156 of file turbulence.h.
References divf(), fillBCs(), gradf(), Turbulence_Model::mu, trn(), and Turbulence_Model::U.
getReynoldsStress()
virtual STensorCellField EddyViscosity_Model::getReynoldsStress () inline virtual
Calculate Reynolds stress
Reimplemented from Turbulence_Model.
Definition at line 165 of file turbulence.h.
References Turbulence_Model::getK(), gradf(), Constants::I_ST(), Turbulence_Model::rho, sym(), and Turbulence_Model::U.
getS2()
ScalarCellField EddyViscosity_Model::getS2 (const TensorCellField & gradU) inline
Calculate S2
Definition at line 171 of file turbulence.h.
References skw(), and sym().
Referenced by MixingLength_Model::calcEddyViscosity(), RNG_KE_Model::calcEddyViscosity(), and MixingLength_Model::getK().
getTurbVisc()
virtual ScalarCellField EddyViscosity_Model::getTurbVisc () inline virtual
Calculate turbulent viscosity
Reimplemented from Turbulence_Model.
Definition at line 152 of file turbulence.h.
setWallEddyMu()
void EddyViscosity_Model::setWallEddyMu () inline
Set eddy viscosity at walls
Definition at line 206 of file turbulence.h.
References Mesh::AllBConditions, BasicBCondition::bdry, BasicBCondition::cIndex, BasicBCondition::fIndex, MeshField< type, entity >::fIndex, forEach, BasicBCondition::low, and Mesh::ROUGHWALL.
Member Data Documentation
eddy_mu
ScalarCellField EddyViscosity_Model::eddy_mu
Eddy viscosity
Definition at line 123 of file turbulence.h.
Referenced by MixingLength_Model::applyWallFunction(), KE_Model::calcEddyMu(), KW_Model::calcEddyMu(), REALIZABLE_KE_Model::calcEddyMu(), MixingLength_Model::calcEddyViscosity(), KE_Model::solve(), KW_Model::solve(), REALIZABLE_KE_Model::solve(), and RNG_KE_Model::solve().
modelType
Model EddyViscosity_Model::modelType
Type of model
Definition at line 130 of file turbulence.h.
wallModel
WallModel EddyViscosity_Model::wallModel
Type of wall model
Definition at line 131 of file turbulence.h.
Referenced by MixingLength_Model::applyWallFunction(), KE_Model::solve(), KW_Model::solve(), REALIZABLE_KE_Model::solve(), and RNG_KE_Model::solve().
The documentation for this struct was generated from the following file:
/home/daniel/storage/NebulaSEM/src/turbulence/turbulence.h