NebulaSEM: MixingLength_Model Struct Reference
MixingLength_Model Struct Reference
#include <mixing_length.h>
Public Member Functions
MixingLength_Model (VectorCellField &, VectorCellField &, ScalarFacetField &, ScalarCellField &, ScalarCellField &)
virtual void enroll ()
virtual void calcEddyViscosity (const TensorCellField &gradU)
virtual void applyWallFunction (Int f, LawOfWall &low)
virtual ScalarCellField getK ()
virtual void calcLengthScale ()
Public Member Functions inherited from EddyViscosity_Model
EddyViscosity_Model (VectorCellField &tU, VectorCellField &tFc, ScalarFacetField &tF, ScalarCellField &trho, ScalarCellField &tmu)
virtual ScalarCellField getTurbVisc ()
virtual VectorCellField getExplicitStresses ()
virtual STensorCellField getReynoldsStress ()
ScalarCellField getS2 (const TensorCellField &gradU)
void FixNearWallValues (ScalarCellMatrix &M)
void setWallEddyMu ()
Public Member Functions inherited from Turbulence_Model
Turbulence_Model (VectorCellField &tU, VectorCellField &tFc, ScalarFacetField &tF, ScalarCellField &trho, ScalarCellField &tmu)
virtual ~Turbulence_Model ()
virtual void solve ()
STensorCellField getViscousStress ()
Public Attributes
Scalar mixingLength
Scalar C
Int wallDamping
ScalarCellField lm
Scalar kappa
Public Attributes inherited from EddyViscosity_Model
ScalarCellField eddy_mu
Model modelType
WallModel wallModel
Public Attributes inherited from Turbulence_Model
VectorCellField & U
VectorCellField & Fc
ScalarFacetField & F
ScalarCellField & rho
ScalarCellField & mu
Util::ParamList params
bool writeStress
Additional Inherited Members
Public Types inherited from EddyViscosity_Model
enum Model { SMAGORNSKY , BALDWIN , KATO }
enum WallModel { NONE , STANDARD , LAUNDER }
Static Public Member Functions inherited from Turbulence_Model
static bool needWallDist ()
static void RegisterTable (Util::ParamList &params)
static Turbulence_Model * Select (VectorCellField &U, VectorCellField &Fc, ScalarFacetField &F, ScalarCellField &rho, ScalarCellField &mu)
Static Public Attributes inherited from Turbulence_Model
static Int turb_model = 2
static bool bneedWallDist = false
Detailed Description
Definition at line 6 of file mixing_length.h.
Constructor & Destructor Documentation
MixingLength_Model()
MixingLength_Model::MixingLength_Model (VectorCellField & tU, VectorCellField & tFc, ScalarFacetField & tF, ScalarCellField & trho, ScalarCellField & tmu)
References:
    Book by Pope pg. 369
Description:
    Velocity and time scales are modelled as:
        l* = lm
        u* = lm * |S|
        eddy_nu = u*l*
                = (lm^2) * |S|
    Generalization of the mixing length model for 3D flows:
       by Smagorinsky (1963).
          eddy_nu = (lm^2) * sqrt(2 * (S & S))
       by Baldwin & Lomax (1978)
          eddy_nu = (lm^2) * sqrt(2 * (O & O))
    The turbulent kinetic energy k can be approximated by equating turbulent
    viscosity eddy_nu with the one from Prandtl/Smagorinsky one equation models.
        u* = C * k^1/2
        eddy_nu = C * k^1/2 * lm
    Equating with the above eqn yields
        k = (lm / C)^2 * (2 * (S & S))
    For high-Re flows, the mixing length close to the wall is set :
        lm = kappa * y_wall
    Thus for Smagornsky LES model
        lm = min(Cs * Delta, kappa * y_wall)
Definition at line 30 of file mixing_length.cpp.
Member Function Documentation
applyWallFunction()
void MixingLength_Model::applyWallFunction (Int f, LawOfWall & low) virtual
Apply wall function
Implements EddyViscosity_Model.
Definition at line 60 of file mixing_length.cpp.
References Mesh::cC, EddyViscosity_Model::eddy_mu, Mesh::fN, Mesh::FN, Mesh::FO, LawOfWall::getUp(), LawOfWall::getUstar(), mag(), Turbulence_Model::mu, Turbulence_Model::rho, Scalar, EddyViscosity_Model::STANDARD, Turbulence_Model::U, and EddyViscosity_Model::wallModel.
calcEddyViscosity()
void MixingLength_Model::calcEddyViscosity (const TensorCellField & gradU) virtual
Calculate eddy viscosity
Implements EddyViscosity_Model.
Definition at line 53 of file mixing_length.cpp.
References calcLengthScale(), EddyViscosity_Model::eddy_mu, EddyViscosity_Model::getS2(), kappa, lm, min(), Turbulence_Model::rho, Scalar, wallDamping, and Mesh::yWall.
calcLengthScale()
virtual void MixingLength_Model::calcLengthScale () inline virtual
Reimplemented in LES_Model.
Definition at line 24 of file mixing_length.h.
References lm, and mixingLength.
Referenced by calcEddyViscosity().
enroll()
void MixingLength_Model::enroll () virtual
Enroll parameters
Reimplemented from EddyViscosity_Model.
Reimplemented in LES_Model.
Definition at line 39 of file mixing_length.cpp.
References C, EddyViscosity_Model::enroll(), kappa, mixingLength, Turbulence_Model::params, and wallDamping.
Referenced by LES_Model::enroll().
getK()
ScalarCellField MixingLength_Model::getK () virtual
Calculate turbulent kinetic energy
Reimplemented from Turbulence_Model.
Definition at line 49 of file mixing_length.cpp.
References C, EddyViscosity_Model::getS2(), gradf(), lm, and Turbulence_Model::U.
Member Data Documentation
C
Scalar MixingLength_Model::C
Definition at line 9 of file mixing_length.h.
Referenced by enroll(), and getK().
kappa
Scalar MixingLength_Model::kappa
Definition at line 14 of file mixing_length.h.
Referenced by calcEddyViscosity(), and enroll().
lm
ScalarCellField MixingLength_Model::lm
Definition at line 13 of file mixing_length.h.
Referenced by calcEddyViscosity(), LES_Model::calcLengthScale(), calcLengthScale(), and getK().
mixingLength
Scalar MixingLength_Model::mixingLength
Definition at line 8 of file mixing_length.h.
Referenced by calcLengthScale(), and enroll().
wallDamping
Int MixingLength_Model::wallDamping
Definition at line 10 of file mixing_length.h.
Referenced by calcEddyViscosity(), and enroll().
The documentation for this struct was generated from the following files:
/home/daniel/storage/NebulaSEM/src/turbulence/mixing_length/mixing_length.h
/home/daniel/storage/NebulaSEM/src/turbulence/mixing_length/mixing_length.cpp