NebulaSEM: Mesh::MeshObject Struct Reference
Mesh::MeshObject Struct Reference
#include <mesh.h>
Public Member Functions
void clear ()
void writeMshMesh (std::ostream &)
void readMshMesh (std::istream &)
void addBoundaryCells ()
void getHexCorners (const Facet &, const Facet &, IntVector &vp)
void fixHexCells ()
void calcGeometry ()
void removeBoundary (const IntVector &)
Int removeUnusedVertices (Int=0)
void breakEdges (Int)
void ExtrudeMesh ()
void straightenEdges (const Facet &, Facet &, Facet &)
bool coplanarFaces (const Facet &, const Facet &)
bool mergeFacets (const Facet &, const Facet &, Facet &)
void mergeFacetsGroup (const IntVector &, Facet &, const Cell *=0)
void mergeCells (Cell &, const Cell &, IntVector &)
void addVerticesToEdge (const int, Facet &, const Facet &)
void calcFaceCenter (const Facet &, Vector &)
void calcCellCenter (const Cell &, Vector &)
void calcUnitNormal (const Facet &, Vector &)
void initFaceInfo (IntVector &, Cells &, const IntVector &, const Cells &)
void refineFacet (const Facet &, Facets &, Int, Int)
void refineFacets (const IntVector &, IntVector &, const IntVector &, IntVector &, IntVector &, Int)
void refineCell (const Cell &, IntVector &, Int, IntVector &, IntVector &, IntVector &, Cells &, IntVector &, Int)
void refineMesh (const IntVector &, const IntVector &, const IntVector &, const IntVector &, IntVector &, IntVector &, IntVector &)
template<typename Ts >
bool readTextMesh (Ts &is)
template<typename Ts >
void writeTextMesh (Ts &os) const
Public Attributes
Vertices mVertices
Facets mFacets
Cells mCells
std::string name
Boundaries mBoundaries
IntVector mFOC
IntVector mFNC
IntVector mFMC
BoolVector mHasBoundary
Int mNV
Int mNF
Int mBCS
PatchVector mPatches
InterBoundVector mInterMesh
Cells mFaceID
VectorVector mFC
VectorVector mCC
VectorVector mFN
ScalarVector mCV
BoolVector mReversed
NodeVector mAmrTree
Vertices mVerticesNoExtrude
Friends
template<typename Ts >
Ts & operator<< (Ts &os, const MeshObject &p)
template<typename Ts >
Ts & operator>> (Ts &is, MeshObject &p)
Detailed Description
Mesh object
Definition at line 76 of file mesh.h.
Member Function Documentation
addBoundaryCells()
void Mesh::MeshObject::addBoundaryCells ()
Add boundary cells around mesh
Definition at line 55 of file mesh.cpp.
References forEach, forEachIt, and Constants::MAX_INT.
addVerticesToEdge()
void Mesh::MeshObject::addVerticesToEdge (const int va, Facet & f, const Facet & fp)
Add vertices to edges of a face
Definition at line 1022 of file mesh.cpp.
References forEach, and Mesh::pointInLine().
breakEdges()
void Mesh::MeshObject::breakEdges (Int ivBegin)
Break edges of faces that are not set for refinement but has a neighboring refined face
Definition at line 729 of file mesh.cpp.
References dot(), forEach, Mesh::pointInLine(), and Scalar.
calcCellCenter()
void Mesh::MeshObject::calcCellCenter (const Cell & c, Vector & cCj)
Calculate cell center
Definition at line 1060 of file mesh.cpp.
References forEach, mag(), and Scalar.
calcFaceCenter()
void Mesh::MeshObject::calcFaceCenter (const Facet & f, Vector & fCj)
Calculate face center
Definition at line 1034 of file mesh.cpp.
References forEach, mag(), and Scalar.
calcGeometry()
void Mesh::MeshObject::calcGeometry ()
Calculate geometric information
Definition at line 423 of file mesh.cpp.
References cart_to_sphere(), equal(), forEach, forEachS, geodesic_distance(), Mesh::is_spherical, mag(), Scalar, and spherical_triangle_area().
calcUnitNormal()
void Mesh::MeshObject::calcUnitNormal (const Facet & f, Vector & N)
Calculate unit-normal of face
Definition at line 813 of file mesh.cpp.
References Mesh::pointInLine().
clear()
void Mesh::MeshObject::clear ()
Clear mesh object
Definition at line 38 of file mesh.cpp.
Referenced by readTextMesh().
coplanarFaces()
bool Mesh::MeshObject::coplanarFaces (const Facet & f1, const Facet & f2)
Check if faces are co-planar
Definition at line 845 of file mesh.cpp.
References dot(), equal(), and Scalar.
ExtrudeMesh()
void Mesh::MeshObject::ExtrudeMesh ()
Extrude mesh
Definition at line 696 of file mesh.cpp.
References forEach, Mesh::is_spherical, max(), Scalar, Mesh::sphere_height, and Mesh::sphere_radius.
fixHexCells()
void Mesh::MeshObject::fixHexCells ()
Fix hexahedral cells for the sake of DG
Definition at line 160 of file mesh.cpp.
References dot(), equalSet(), erase_indices(), forEach, forEachS, rotate(), and Scalar.
getHexCorners()
void Mesh::MeshObject::getHexCorners (const Facet & f1, const Facet & f2, IntVector & vp)
Find the eight vertices of a hexahedron
Definition at line 112 of file mesh.cpp.
References dot(), Controls::dt, mag(), Constants::PI, and Scalar.
Referenced by DG::init_geom().
initFaceInfo()
void Mesh::MeshObject::initFaceInfo (IntVector & refineF, Cells & crefineF, const IntVector & rCells, const Cells & newCells)
Initialize facet refinement information
Definition at line 1696 of file mesh.cpp.
References forEach, forEachS, and Constants::MAX_INT.
mergeCells()
void Mesh::MeshObject::mergeCells (Cell & c1, const Cell & c2, IntVector & delFacets)
Merge two cells
Definition at line 1008 of file mesh.cpp.
References forEach.
mergeFacets()
bool Mesh::MeshObject::mergeFacets (const Facet & f1_, const Facet & f2_, Facet & f)
Union of non-overlaping polygons
Definition at line 861 of file mesh.cpp.
References dot(), forEach, Mesh::pointInLine(), and rotate().
Referenced by DG::init_geom().
mergeFacetsGroup()
void Mesh::MeshObject::mergeFacetsGroup (const IntVector & shared1, Facet & fn, const Cell * c1 = 0)
Merge facets of cell
Definition at line 955 of file mesh.cpp.
References erase_indices(), and forEach.
readMshMesh()
void Mesh::MeshObject::readMshMesh (std::istream & is)
Read ANSYS ascii mesh (.msh format)
Definition at line 8 of file mshMesh.cpp.
References forEach, forEachIt, Constants::MAX_INT, and Util::nextc().
readTextMesh()
template<typename Ts > bool Mesh::MeshObject::readTextMesh (Ts & is) inline
Read mesh from file in text format
Definition at line 154 of file mesh.h.
References Mesh::interBoundary::buffer_index, clear(), Mesh::interBoundary::f, forEach, Mesh::interBoundary::from, mBoundaries, mCells, mFacets, mInterMesh, mVertices, and Mesh::interBoundary::to.
refineCell()
void Mesh::MeshObject::refineCell (const Cell & c, IntVector & cr, Int rDir, IntVector & refineF, IntVector & startF, IntVector & endF, Cells & newc, IntVector & delFacets, Int ivBegin)
Refine a given cell
Definition at line 1294 of file mesh.cpp.
References dot(), equalSet(), erase_indices(), forEach, forEachIt, forEachR, forEachS, Constants::MAX_INT, Mesh::pointInPolygon(), and Scalar.
refineFacet()
void Mesh::MeshObject::refineFacet (const Facet & f_, Facets & newf, Int dir, Int ivBegin)
Refine facet
Definition at line 1116 of file mesh.cpp.
References Mesh::amr_direction, equal(), forEach, forEachS, Mesh::is_spherical, mag(), Constants::MAX_INT, RDIR, rotate(), Scalar, and TEST.
refineFacets()
void Mesh::MeshObject::refineFacets (const IntVector & rFacets, IntVector & refineF, const IntVector & rfDirs, IntVector & startF, IntVector & endF, Int ivBegin)
Refine list of facets
Definition at line 1271 of file mesh.cpp.
References forEach.
refineMesh()
void Mesh::MeshObject::refineMesh (const IntVector & cCells, const IntVector & rCells, const IntVector & rLevel, const IntVector & rDirs, IntVector & refineMap, IntVector & coarseMap, IntVector & cellMap)
Refine mesh
Definition at line 1736 of file mesh.cpp.
References Mesh::Node::cid, dot(), erase_indices(), ERASEADD, eraseValue, forEach, forEachIt, forEachS, Mesh::gFacets, Mesh::gVertices, Mesh::Node::id, Mesh::Node::level, Constants::MAX_INT, Mesh::Node::nchildren, and Scalar.
removeBoundary()
void Mesh::MeshObject::removeBoundary (const IntVector & fs)
Remove empty boundary (for 2D domain)
Definition at line 554 of file mesh.cpp.
References erase_indices(), forEach, forEachIt, and Constants::MAX_INT.
removeUnusedVertices()
Int Mesh::MeshObject::removeUnusedVertices (Int ivBegin = 0)
Remove unused vertices
Definition at line 646 of file mesh.cpp.
References erase_indices(), forEach, and Mesh::pointInLine().
straightenEdges()
void Mesh::MeshObject::straightenEdges (const Facet & f, Facet & r, Facet & removed)
Straighten edges of faces
Definition at line 829 of file mesh.cpp.
References Mesh::pointInLine().
writeMshMesh()
void Mesh::MeshObject::writeMshMesh (std::ostream & os)
Write ANSYS ascii mesh (.msh format)
Definition at line 152 of file mshMesh.cpp.
References forEach, and forEachIt.
writeTextMesh()
template<typename Ts > void Mesh::MeshObject::writeTextMesh (Ts & os) const inline
Write mesh to file in text format
Definition at line 198 of file mesh.h.
References mBCS, mBoundaries, mCells, mFacets, mVertices, and mVerticesNoExtrude.
Friends And Related Function Documentation
operator<<
template<typename Ts > Ts& operator<< (Ts & os, const MeshObject & p) friend
Definition at line 141 of file mesh.h.
operator>>
template<typename Ts > Ts& operator>> (Ts & is, MeshObject & p) friend
Definition at line 146 of file mesh.h.
Member Data Documentation
mAmrTree
NodeVector Mesh::MeshObject::mAmrTree
AMR tree
Definition at line 106 of file mesh.h.
mBCS
Int Mesh::MeshObject::mBCS
Number of internal cells
Definition at line 93 of file mesh.h.
Referenced by Prepare::decomposeMesh(), hexMesh(), merge(), and writeTextMesh().
mBoundaries
Boundaries Mesh::MeshObject::mBoundaries
List of boundary patches
Definition at line 82 of file mesh.h.
Referenced by Prepare::decomposeMesh(), readTextMesh(), and writeTextMesh().
mCC
VectorVector Mesh::MeshObject::mCC
Cell centers
Definition at line 101 of file mesh.h.
mCells
Cells Mesh::MeshObject::mCells
Cells
Definition at line 79 of file mesh.h.
Referenced by Prepare::decomposeMesh(), hexMesh(), merge(), readTextMesh(), remove_duplicate(), and writeTextMesh().
mCV
ScalarVector Mesh::MeshObject::mCV
Cell volumes
Definition at line 103 of file mesh.h.
mFaceID
Cells Mesh::MeshObject::mFaceID
Original face orientation
Definition at line 98 of file mesh.h.
mFacets
Facets Mesh::MeshObject::mFacets
facets
Definition at line 78 of file mesh.h.
Referenced by Prepare::decomposeMesh(), hexMesh(), merge(), readTextMesh(), remove_duplicate(), and writeTextMesh().
mFC
VectorVector Mesh::MeshObject::mFC
Facet centers
Definition at line 100 of file mesh.h.
mFMC
IntVector Mesh::MeshObject::mFMC
Facet mortar flags 0=conforming, 1=facet owner is mortar, 2=facet neighbor is mortar
Definition at line 85 of file mesh.h.
mFN
VectorVector Mesh::MeshObject::mFN
Facet normals
Definition at line 102 of file mesh.h.
mFNC
IntVector Mesh::MeshObject::mFNC
Facet neighbor cells
Definition at line 84 of file mesh.h.
mFOC
IntVector Mesh::MeshObject::mFOC
Facet owner cells
Definition at line 83 of file mesh.h.
mHasBoundary
BoolVector Mesh::MeshObject::mHasBoundary
True if a cell has boundary face
Definition at line 89 of file mesh.h.
mInterMesh
InterBoundVector Mesh::MeshObject::mInterMesh
List of inter-processor boundaries
Definition at line 96 of file mesh.h.
Referenced by readTextMesh().
mNF
Int Mesh::MeshObject::mNF
Number of internal faces
Definition at line 92 of file mesh.h.
Referenced by hexMesh(), merge(), and remove_duplicate().
mNV
Int Mesh::MeshObject::mNV
Number of internal vertices
Definition at line 91 of file mesh.h.
Referenced by hexMesh(), merge(), and remove_duplicate().
mPatches
PatchVector Mesh::MeshObject::mPatches
List of patches
Definition at line 95 of file mesh.h.
Referenced by hexMesh(), merge(), and remove_duplicate().
mReversed
BoolVector Mesh::MeshObject::mReversed
Is normal reversed?
Definition at line 104 of file mesh.h.
mVertices
Vertices Mesh::MeshObject::mVertices
vertices
Definition at line 77 of file mesh.h.
Referenced by Prepare::decomposeMesh(), hexMesh(), merge(), readTextMesh(), remove_duplicate(), and writeTextMesh().
mVerticesNoExtrude
Vertices Mesh::MeshObject::mVerticesNoExtrude
Vertices before extruded on sphere
Definition at line 108 of file mesh.h.
Referenced by writeTextMesh().
name
std::string Mesh::MeshObject::name
File name
Definition at line 81 of file mesh.h.
The documentation for this struct was generated from the following files:
/home/daniel/storage/NebulaSEM/src/mesh/mesh.h
/home/daniel/storage/NebulaSEM/src/mesh/mesh.cpp
/home/daniel/storage/NebulaSEM/src/mesh/mshMesh.cpp