NebulaSEM: RNG_KE_Model Struct Reference
RNG_KE_Model Struct Reference
#include <rngke.h>
Public Member Functions
RNG_KE_Model (VectorCellField &, VectorCellField &, ScalarFacetField &, ScalarCellField &, ScalarCellField &)
virtual void enroll ()
virtual void solve ()
virtual void calcEddyViscosity (const TensorCellField &gradU)
Public Member Functions inherited from KE_Model
KE_Model (VectorCellField &, VectorCellField &, ScalarFacetField &, ScalarCellField &, ScalarCellField &)
virtual void calcEddyMu ()
virtual Scalar calcX (Scalar ustar, Scalar kappa, Scalar y)
Public Member Functions inherited from KX_Model
KX_Model (VectorCellField &tU, VectorCellField &tFc, ScalarFacetField &tF, ScalarCellField &trho, ScalarCellField &tmu, const char *xname)
virtual ScalarCellField getK ()
virtual Scalar getCmu (Int i)
virtual void applyWallFunction (Int f, LawOfWall &low)
Public Member Functions inherited from EddyViscosity_Model
EddyViscosity_Model (VectorCellField &tU, VectorCellField &tFc, ScalarFacetField &tF, ScalarCellField &trho, ScalarCellField &tmu)
virtual ScalarCellField getTurbVisc ()
virtual VectorCellField getExplicitStresses ()
virtual STensorCellField getReynoldsStress ()
ScalarCellField getS2 (const TensorCellField &gradU)
void FixNearWallValues (ScalarCellMatrix &M)
void setWallEddyMu ()
Public Member Functions inherited from Turbulence_Model
Turbulence_Model (VectorCellField &tU, VectorCellField &tFc, ScalarFacetField &tF, ScalarCellField &trho, ScalarCellField &tmu)
virtual ~Turbulence_Model ()
STensorCellField getViscousStress ()
Public Attributes
Scalar eta0
Scalar beta
ScalarCellField C2eStar
Public Attributes inherited from KX_Model
Scalar Cmu
Scalar SigmaK
Scalar SigmaX
Scalar C1x
Scalar C2x
Scalar k_UR
Scalar x_UR
ScalarCellField k
ScalarCellField x
ScalarCellField Pk
Public Attributes inherited from EddyViscosity_Model
ScalarCellField eddy_mu
Model modelType
WallModel wallModel
Public Attributes inherited from Turbulence_Model
VectorCellField & U
VectorCellField & Fc
ScalarFacetField & F
ScalarCellField & rho
ScalarCellField & mu
Util::ParamList params
bool writeStress
Additional Inherited Members
Public Types inherited from EddyViscosity_Model
enum Model { SMAGORNSKY , BALDWIN , KATO }
enum WallModel { NONE , STANDARD , LAUNDER }
Static Public Member Functions inherited from Turbulence_Model
static bool needWallDist ()
static void RegisterTable (Util::ParamList &params)
static Turbulence_Model * Select (VectorCellField &U, VectorCellField &Fc, ScalarFacetField &F, ScalarCellField &rho, ScalarCellField &mu)
Static Public Attributes inherited from Turbulence_Model
static Int turb_model = 2
static bool bneedWallDist = false
Detailed Description
Definition at line 6 of file rngke.h.
Constructor & Destructor Documentation
RNG_KE_Model()
RNG_KE_Model::RNG_KE_Model (VectorCellField & tU, VectorCellField & tFc, ScalarFacetField & tF, ScalarCellField & trho, ScalarCellField & tmu)
RNG-KE turbulence model constructor References: http://www.cfd-online.com/Wiki/RNG_k-epsilon_model
Definition at line 7 of file rngke.cpp.
References KX_Model::C1x, KX_Model::C2x, KX_Model::Cmu, KX_Model::SigmaK, and KX_Model::SigmaX.
Member Function Documentation
calcEddyViscosity()
void RNG_KE_Model::calcEddyViscosity (const TensorCellField & gradU) virtual
Calculate eddy viscosity
Reimplemented from KX_Model.
Definition at line 26 of file rngke.cpp.
References beta, C2eStar, KX_Model::C2x, KX_Model::calcEddyViscosity(), KX_Model::Cmu, eta0, EddyViscosity_Model::getS2(), KX_Model::k, max(), Scalar, and KX_Model::x.
enroll()
void RNG_KE_Model::enroll () virtual
Enroll parameters
Reimplemented from KE_Model.
Definition at line 19 of file rngke.cpp.
References beta, KE_Model::enroll(), eta0, and Turbulence_Model::params.
solve()
void RNG_KE_Model::solve () virtual
Solver transport of turbulent dissipation and kinetic energy
Reimplemented from KE_Model.
Definition at line 38 of file rngke.cpp.
References KX_Model::C1x, C2eStar, EddyViscosity_Model::eddy_mu, Turbulence_Model::F, Turbulence_Model::Fc, EddyViscosity_Model::FixNearWallValues(), KX_Model::k, KX_Model::k_UR, Constants::MachineEpsilon, max(), Turbulence_Model::mu, KX_Model::Pk, Turbulence_Model::rho, KX_Model::SigmaK, KX_Model::SigmaX, Solve(), EddyViscosity_Model::STANDARD, EddyViscosity_Model::wallModel, KX_Model::x, and KX_Model::x_UR.
Member Data Documentation
beta
Scalar RNG_KE_Model::beta
Definition at line 9 of file rngke.h.
Referenced by calcEddyViscosity(), and enroll().
C2eStar
ScalarCellField RNG_KE_Model::C2eStar
Definition at line 11 of file rngke.h.
Referenced by calcEddyViscosity(), and solve().
eta0
Scalar RNG_KE_Model::eta0
Definition at line 8 of file rngke.h.
Referenced by calcEddyViscosity(), and enroll().
The documentation for this struct was generated from the following files:
/home/daniel/storage/NebulaSEM/src/turbulence/rngke/rngke.h
/home/daniel/storage/NebulaSEM/src/turbulence/rngke/rngke.cpp