NebulaSEM: /home/daniel/storage/NebulaSEM/src/tensor/tensor.h File Reference
tensor.h File Reference
#include <iostream>
#include <cmath>
#include "types.h"
Classes
struct Unroll< N >
struct Unroll< 0 >
class TTensor< SIZE >
Namespaces
Constants
Macros
#define Scalar float
#define AddOperator(T,)
#define Op(name,)
#define SOp(name,)
#define Fp(name,)
#define Fp1(name,)
#define Fp2(name,)
#define Op(name) static FORCEINLINE void name(Scalar* p,const Scalar* q) {}
#define SOp(name) static FORCEINLINE void name(Scalar* p,const Scalar q) {}
#define Fp(name) static FORCEINLINE void name(Scalar* r,const Scalar* p,const Scalar* q) {}
#define Fp1(name) static FORCEINLINE void name(Scalar* r,const Scalar* p,const Scalar q) {}
#define Fp2(name) static FORCEINLINE void name(Scalar* r,const Scalar* p) {}
#define Op(name,)
#define SOp(name,)
#define Fp(name)
#define Fp1(name)
#define Fp2(name)
General scalar operators
#define AddRightScalarOperator(T,)
#define AddLeftScalarOperator1(T,)
#define AddLeftScalarOperator2(T,)
#define AddOperators(T)
#define AddScalarOperators(T)
Enumerations
enum {
Constants::XX , Constants::YY , Constants::ZZ , Constants::XY ,
Constants::YZ , Constants::XZ , Constants::YX , Constants::ZY ,
Constants::ZX
}
Functions
const Vector Constants::I_V (1, 1, 1)
const Tensor Constants::I_T (1, 1, 1)
const STensor Constants::I_ST (1, 1, 1)
Other operations on scalars
FORCEINLINE Scalar * addr (Int &p)
FORCEINLINE Scalar * addr (Scalar &p)
FORCEINLINE Scalar mag (const Scalar &p)
FORCEINLINE Scalar sdiv (const Scalar &p, const Scalar &q)
FORCEINLINE Scalar max (const Scalar &p, const Scalar &q)
FORCEINLINE Scalar min (const Scalar &p, const Scalar &q)
FORCEINLINE Scalar dot (const Scalar &p, const Scalar &q)
Symmetry boundary condition
FORCEINLINE Scalar sym (const Scalar &p, const Vector &n)
FORCEINLINE Vector sym (const Vector &p, const Vector &n)
FORCEINLINE STensor sym (const STensor &p, const Vector &n)
FORCEINLINE Tensor sym (const Tensor &p, const Vector &n)
void matinv (Scalar *A, Scalar *X, Int N)
void matmul (Scalar *A, Scalar *B, Scalar *X, Int N)
void mattrn (Scalar *A, Scalar *X, Int N)
template<class T >
T Interpolate_face (Scalar r, Scalar s, T x00, T x01, T x10, T x11, T xr0, T xr1, T x0s, T x1s)
template<class T >
T Interpolate_cell (Scalar r, Scalar s, Scalar t, T x000, T x001, T x010, T x011, T x100, T x101, T x110, T x111, T xr00, T xr01, T xr10, T xr11, T x0s0, T x0s1, T x1s0, T x1s1, T x00t, T x01t, T x10t, T x11t, T x0st, T x1st, T xr0t, T xr1t, T xrs0, T xrs1)
Define basic spherical coordinate manipulation functions.
(radius, latitude, longitude) where latitude = [-pi/2,pi/2] longitude = [-pi,pi] radius = radius of the earth
FORCEINLINE Vector sphere_to_cart (const Vector &s)
FORCEINLINE Vector cart_to_sphere (const Vector &c)
FORCEINLINE Scalar geodesic_distance (const Vector &s1, const Vector &s2)
FORCEINLINE Vector wind_field (Scalar u, Scalar v, Scalar lat, Scalar lon)
FORCEINLINE Scalar spherical_triangle_area (Scalar radius, const Vector &v0, const Vector &v1, const Vector &v2)
Variables
const Int Constants::MAX_INT = Int(1 << 31)
const Scalar Constants::PI = Scalar(3.14159265358979323846264)
const Scalar Constants::E = Scalar(2.71828182845904523536028)
const Scalar Constants::MachineEpsilon = Scalar(1e-7)
const Scalar Constants::EqualEpsilon = Scalar(1e-3)
Define basic tensors of order 3,6, and 9
typedef TTensor< 3 > Vector
typedef TTensor< 6 > STensor
typedef TTensor< 9 > Tensor
Vector operator^ (const Vector &p, const Vector &q)
STensor mul (const Vector &p)
Tensor mul (const Vector &p, const Vector &q)
Tensor mul (const Tensor &p, const Tensor &q)
STensor mul (const STensor &p, const STensor &q)
Vector dot (const Tensor &, const Vector &)
Vector dot (const STensor &, const Vector &)
STensor sym (const Tensor &p)
Tensor skw (const Tensor &p)
Tensor trn (const Tensor &p)
Scalar det (const Tensor &p)
Tensor inv (const Tensor &p)
Vector rotate (const Vector &v, const Vector &N, const Scalar &theta)
FORCEINLINE bool equal (const Scalar &p, const Scalar &q, const Scalar tol=Constants::EqualEpsilon)
FORCEINLINE bool equal (const Vector &p, const Vector &q, const Scalar tol=Constants::EqualEpsilon)
Macro Definition Documentation
AddLeftScalarOperator1
#define AddLeftScalarOperator1 (T)
Value:
    friend FORCEINLINE T operator $ (const Scalar& p,const T& q) {  \
        T r = q;                                                    \
        r $##= p;                                                   \
        return r;                                                   \
    }
Definition at line 33 of file tensor.h.
AddLeftScalarOperator2
#define AddLeftScalarOperator2 (T)
Value:
    friend FORCEINLINE T operator $ (const Scalar& p,const T& q) {  \
        T r(p);                                                     \
        r $##= q;                                                   \
        return r;                                                   \
    }
Definition at line 39 of file tensor.h.
AddOperator
#define AddOperator (T)
Value:
    friend FORCEINLINE T operator $ (const T& p,const T& q) {       \
        T r = p;                                                    \
        r $##= q;                                                   \
        return r;                                                   \
    }
Adds general arthimetic operators defined via compound assignment
Definition at line 19 of file tensor.h.
AddOperators
#define AddOperators (T)
Value:
    AddOperator(T,+)\
    AddOperator(T,-)\
    AddOperator(T,*)\
    AddOperator(T,/)
Definition at line 47 of file tensor.h.
AddRightScalarOperator
#define AddRightScalarOperator (T)
Value:
    friend FORCEINLINE T operator $ (const T& p,const Scalar& q) {  \
        T r = p;                                                    \
        r $##= q;                                                   \
        return r;                                                   \
    }
Definition at line 27 of file tensor.h.
AddScalarOperators
#define AddScalarOperators (T)
Value:
    AddRightScalarOperator(T,+)\
    AddRightScalarOperator(T,-)\
    AddRightScalarOperator(T,*)\
    AddRightScalarOperator(T,/)\
    AddLeftScalarOperator1(T,+)\
    AddLeftScalarOperator1(T,*)\
    AddLeftScalarOperator2(T,-)\
    AddLeftScalarOperator2(T,/)
Definition at line 53 of file tensor.h.
Fp [1/3]
#define Fp (name) static FORCEINLINE void name(Scalar* r,const Scalar* p,const Scalar* q) {}
Definition at line 288 of file tensor.h.
Fp [2/3]
#define Fp (name)
Value:
    FORCEINLINE friend TTensor name(const TTensor& p,const TTensor& s) { \
        TTensor r;                                                  \
        Unroll<SIZE>::name(r.P,p.P,s.P);                            \
        return r;                                                   \
    }
Definition at line 288 of file tensor.h.
Fp [3/3]
#define Fp (name)
Value:
    static FORCEINLINE void name(Scalar* r,const Scalar* p,const Scalar* q) {   \
        *r = ::$(*p,*q);                                                        \
        Unroll<N - 1>::name(r + 1,p + 1,q + 1);                                 \
    }
Definition at line 288 of file tensor.h.
Fp1 [1/3]
#define Fp1 (name) static FORCEINLINE void name(Scalar* r,const Scalar* p,const Scalar q) {}
Definition at line 294 of file tensor.h.
Fp1 [2/3]
#define Fp1 (name)
Value:
    FORCEINLINE friend TTensor name(const TTensor& p,const Scalar& s) { \
        TTensor r;                                                  \
        Unroll<SIZE>::name(r.P,p.P,s);                              \
        return r;                                                   \
    }
Definition at line 294 of file tensor.h.
Fp1 [3/3]
#define Fp1 (name)
Value:
    static FORCEINLINE void name(Scalar* r,const Scalar* p,const Scalar q) {    \
        *r = ::$(*p,q);                                                         \
        Unroll<N - 1>::name(r + 1,p + 1,q);                                     \
    }
Definition at line 294 of file tensor.h.
Fp2 [1/3]
#define Fp2 (name) static FORCEINLINE void name(Scalar* r,const Scalar* p) {}
Definition at line 300 of file tensor.h.
Fp2 [2/3]
#define Fp2 (name)
Value:
    FORCEINLINE friend TTensor name(const TTensor& p) {             \
        TTensor r;                                                  \
        Unroll<SIZE>::name(r.P,p.P);                                \
        return r;                                                   \
    }
Definition at line 300 of file tensor.h.
Fp2 [3/3]
#define Fp2 (name)
Value:
    static FORCEINLINE void name(Scalar* r,const Scalar* p) {                   \
        *r = ::$(*p);                                                           \
        Unroll<N - 1>::name(r + 1,p + 1);                                       \
    }
Definition at line 300 of file tensor.h.
Op [1/3]
#define Op (name) static FORCEINLINE void name(Scalar* p,const Scalar* q) {}
Definition at line 278 of file tensor.h.
Op [2/3]
#define Op (name)
Value:
    static FORCEINLINE void name(Scalar* p,const Scalar* q) {                   \
        *p $ *q;                                                                \
        Unroll<N - 1>::name(p + 1,q + 1);                                       \
    }
Definition at line 278 of file tensor.h.
Op [3/3]
#define Op (name)
Value:
    FORCEINLINE TTensor& operator $(const TTensor& q) {             \
        Unroll<SIZE>::name(P,q.P);                                  \
        return *this;                                               \
    }
Definition at line 278 of file tensor.h.
Scalar
#define Scalar float
Definition at line 15 of file tensor.h.
SOp [1/3]
#define SOp (name) static FORCEINLINE void name(Scalar* p,const Scalar q) {}
Definition at line 283 of file tensor.h.
SOp [2/3]
#define SOp (name)
Value:
    static FORCEINLINE void name(Scalar* p,const Scalar q) {                    \
        *p $ q;                                                                 \
        Unroll<N - 1>::name(p + 1,q);                                           \
    }
Definition at line 283 of file tensor.h.
SOp [3/3]
#define SOp (name)
Value:
    FORCEINLINE TTensor& operator $(const Scalar& q) {              \
        Unroll<SIZE>::name(P,q);                                    \
        return *this;                                               \
    }
Definition at line 283 of file tensor.h.
Typedef Documentation
STensor
typedef TTensor<6> STensor
Definition at line 402 of file tensor.h.
Tensor
typedef TTensor<9> Tensor
Definition at line 403 of file tensor.h.
Vector
typedef TTensor<3> Vector
Definition at line 401 of file tensor.h.
Function Documentation
addr() [1/2]
FORCEINLINE Scalar* addr (Int & p)
Definition at line 65 of file tensor.h.
References Scalar.
Referenced by Util::Parameters< T >::enroll(), and getResidual().
addr() [2/2]
FORCEINLINE Scalar* addr (Scalar & p)
Definition at line 68 of file tensor.h.
cart_to_sphere()
FORCEINLINE Vector cart_to_sphere (const Vector & c)
Convert cartesian to spherical coordinates
Definition at line 599 of file tensor.h.
References mag(), and Scalar.
Referenced by Mesh::MeshObject::calcGeometry().
det()
Scalar det (const Tensor & p)
Determinant of a tensor
Definition at line 144 of file tensor.cpp.
References Scalar, Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
dot() [1/3]
FORCEINLINE Scalar dot (const Scalar & p, const Scalar & q)
Definition at line 83 of file tensor.h.
Referenced by spherical_triangle_area(), and sym().
dot() [2/3]
Vector dot (const STensor & q, const Vector & p)
Inner product of a symmetric tensor and a vector
Definition at line 80 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YY, Constants::YZ, and Constants::ZZ.
dot() [3/3]
Vector dot (const Tensor & q, const Vector & p)
Inner product of a tensor and a vector
Definition at line 72 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
Referenced by Mesh::MeshObject::breakEdges(), Mesh::MeshObject::coplanarFaces(), div_flux(), div_flux_implicit(), Mesh::MeshObject::fixHexCells(), flx(), gather_non_conforming(), Mesh::MeshObject::getHexCorners(), Mesh::initGeomMeshFields(), lap(), Mesh::MeshObject::mergeFacets(), Mesh::pointInLine(), Mesh::pointInPolygon(), Mesh::MeshObject::refineCell(), MeshField< type, entity >::refineField(), Mesh::MeshObject::refineMesh(), scatter_non_conforming(), and uds().
equal() [1/2]
FORCEINLINE bool equal (const Scalar & p, const Scalar & q, const Scalar tol = Constants::EqualEpsilon)
Checks if two scalars are equal within machine epsilon
Definition at line 471 of file tensor.h.
References mag(), and Scalar.
Referenced by applyExplicitBCs(), Mesh::MeshObject::calcGeometry(), Mesh::MeshObject::coplanarFaces(), div_flux_implicit(), equal(), hexMesh(), merge(), Mesh::pointInLine(), Mesh::pointInPolygon(), Mesh::MeshObject::refineFacet(), remove_duplicate(), and sym().
equal() [2/2]
FORCEINLINE bool equal (const Vector & p, const Vector & q, const Scalar tol = Constants::EqualEpsilon)
Checks if two vectors are equal within machine epsilon
Definition at line 478 of file tensor.h.
References equal().
geodesic_distance()
FORCEINLINE Scalar geodesic_distance (const Vector & s1, const Vector & s2)
Compute geodesic distance between two spherical coordinates
Definition at line 608 of file tensor.h.
References Scalar.
Referenced by Mesh::MeshObject::calcGeometry().
Interpolate_cell()
template<class T > T Interpolate_cell (Scalar r, Scalar s, Scalar t, T x000, T x001, T x010, T x011, T x100, T x101, T x110, T x111, T xr00, T xr01, T xr10, T xr11, T x0s0, T x0s1, T x1s0, T x1s1, T x00t, T x01t, T x10t, T x11t, T x0st, T x1st, T xr0t, T xr1t, T xrs0, T xrs1)
Transfinite interpolation on cell (3D)
Definition at line 542 of file tensor.h.
Interpolate_face()
template<class T > T Interpolate_face (Scalar r, Scalar s, T x00, T x01, T x10, T x11, T xr0, T xr1, T x0s, T x1s)
Transfinite interpolation on face (2D)
Definition at line 523 of file tensor.h.
inv()
Tensor inv (const Tensor & p)
Inverse of a tensor
Definition at line 152 of file tensor.cpp.
References Scalar, Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
Referenced by DG::init_geom().
mag()
FORCEINLINE Scalar mag (const Scalar & p)
Definition at line 71 of file tensor.h.
Referenced by applyExplicitBCs(), MixingLength_Model::applyWallFunction(), KX_Model::applyWallFunction(), Mesh::calc_courant(), Mesh::MeshObject::calcCellCenter(), Mesh::MeshObject::calcFaceCenter(), Mesh::MeshObject::calcGeometry(), cart_to_sphere(), cds(), equal(), Mesh::MeshObject::getHexCorners(), getResidual(), hexMesh(), Mesh::initGeomMeshFields(), lap(), MeshField< type, entity >::norm(), Mesh::pointInPolygon(), Mesh::MeshObject::refineFacet(), MeshField< type, entity >::refineField(), and sym().
matinv()
void matinv (Scalar * A_, Scalar * X, Int N)
Inverse of matrix using Gauss-Jordan elimination
Definition at line 170 of file tensor.cpp.
References A, Scalar, and X.
Referenced by DG::init_basis().
matmul()
void matmul (Scalar * A, Scalar * B, Scalar * X, Int N)
Multiply two square matrices
Definition at line 225 of file tensor.cpp.
References A, Scalar, sum(), and X.
Referenced by DG::init_basis().
mattrn()
void mattrn (Scalar * A, Scalar * X, Int N)
Transpose square matrix
Definition at line 237 of file tensor.cpp.
References A, and X.
Referenced by DG::init_basis().
max()
FORCEINLINE Scalar max (const Scalar & p, const Scalar & q)
Definition at line 77 of file tensor.h.
Referenced by REALIZABLE_KE_Model::calcEddyViscosity(), RNG_KE_Model::calcEddyViscosity(), div_flux_implicit(), Mesh::MeshObject::ExtrudeMesh(), KE_Model::solve(), KW_Model::solve(), REALIZABLE_KE_Model::solve(), and RNG_KE_Model::solve().
min()
FORCEINLINE Scalar min (const Scalar & p, const Scalar & q)
Definition at line 80 of file tensor.h.
Referenced by MixingLength_Model::calcEddyViscosity(), REALIZABLE_KE_Model::calcEddyViscosity(), and div_flux_implicit().
mul() [1/4]
STensor mul (const STensor & p, const STensor & q)
Product of two symmetric tensors
Definition at line 59 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YY, Constants::YZ, and Constants::ZZ.
mul() [2/4]
Tensor mul (const Tensor & p, const Tensor & q)
Product of two tensors
Definition at line 42 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
mul() [3/4]
STensor mul (const Vector & p)
Outer product of a vector with itself
Definition at line 30 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YY, Constants::YZ, and Constants::ZZ.
Referenced by sym().
mul() [4/4]
Tensor mul (const Vector & p, const Vector & q)
Outer product of two vectors
Definition at line 14 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
operator^()
Vector operator^ (const Vector & p, const Vector & q)
OpenMP sum reductions
Cross product of two vectors
Definition at line 6 of file tensor.cpp.
References Constants::XX, Constants::YY, and Constants::ZZ.
rotate()
Vector rotate (const Vector & v, const Vector & N, const Scalar & theta)
Rotate a vector by an angle about a given axis The rotation is clock-wise in right-handed system.
Definition at line 134 of file tensor.cpp.
References Scalar, sum(), Constants::XX, Constants::YY, and Constants::ZZ.
Referenced by ADDV(), Prepare::decomposeXYZ(), Mesh::MeshObject::fixHexCells(), Mesh::MeshObject::mergeFacets(), and Mesh::MeshObject::refineFacet().
sdiv()
FORCEINLINE Scalar sdiv (const Scalar & p, const Scalar & q)
Definition at line 74 of file tensor.h.
Referenced by getResidual(), MeshField< type, entity >::refineField(), and SolveT().
skw()
Tensor skw (const Tensor & p)
Skew-symmetric part of a tensor
Definition at line 100 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
Referenced by REALIZABLE_KE_Model::calcEddyViscosity(), and EddyViscosity_Model::getS2().
sphere_to_cart()
FORCEINLINE Vector sphere_to_cart (const Vector & s)
Convert spherical to cartesian coordinates
Definition at line 590 of file tensor.h.
spherical_triangle_area()
FORCEINLINE Scalar spherical_triangle_area (Scalar radius, const Vector & v0, const Vector & v1, const Vector & v2)
Compute area of spherical triangle give cartesian coordinates
Definition at line 624 of file tensor.h.
References dot(), and Scalar.
Referenced by Mesh::MeshObject::calcGeometry().
sym() [1/5]
FORCEINLINE Scalar sym (const Scalar & p, const Vector & n)
Definition at line 483 of file tensor.h.
sym() [2/5]
FORCEINLINE STensor sym (const STensor & p, const Vector & n)
Definition at line 495 of file tensor.h.
References A, equal(), Constants::I_ST(), mag(), mul(), and Scalar.
sym() [3/5]
STensor sym (const Tensor & p)
Symmetric part of a tensor
Definition at line 88 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
Referenced by applyExplicitBCs(), REALIZABLE_KE_Model::calcEddyViscosity(), EddyViscosity_Model::getReynoldsStress(), EddyViscosity_Model::getS2(), and Turbulence_Model::getViscousStress().
sym() [4/5]
FORCEINLINE Tensor sym (const Tensor & p, const Vector & n)
Definition at line 504 of file tensor.h.
References A, equal(), Constants::I_T(), mag(), mul(), and Scalar.
sym() [5/5]
FORCEINLINE Vector sym (const Vector & p, const Vector & n)
Definition at line 486 of file tensor.h.
References A, dot(), equal(), Constants::I_ST(), mag(), mul(), and Scalar.
trn()
Tensor trn (const Tensor & p)
Transpose of a tensor
Definition at line 116 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
Referenced by Turbulence_Model::getExplicitStresses(), EddyViscosity_Model::getExplicitStresses(), and DG::init_geom().
wind_field()
FORCEINLINE Vector wind_field (Scalar u, Scalar v, Scalar lat, Scalar lon)
Given tangential wind fields, compute cartesian equivalent
Definition at line 615 of file tensor.h.