NebulaSEM: /home/daniel/storage/NebulaSEM/src/tensor/tensor.cpp File Reference
tensor.cpp File Reference
#include "tensor.h"
Macros
#define A(ii, jj) A[(ii)*N+(jj)]
#define X(ii, jj) X[(ii)*N+(jj)]
Functions
Vector operator^ (const Vector &p, const Vector &q)
Tensor mul (const Vector &p, const Vector &q)
STensor mul (const Vector &p)
Tensor mul (const Tensor &p, const Tensor &q)
STensor mul (const STensor &p, const STensor &q)
Vector dot (const Tensor &q, const Vector &p)
Vector dot (const STensor &q, const Vector &p)
STensor sym (const Tensor &p)
Tensor skw (const Tensor &p)
Tensor trn (const Tensor &p)
Vector rotate (const Vector &v, const Vector &N, const Scalar &theta)
Scalar det (const Tensor &p)
Tensor inv (const Tensor &p)
void matinv (Scalar *A_, Scalar *X, Int N)
void matmul (Scalar *A, Scalar *B, Scalar *X, Int N)
void mattrn (Scalar *A, Scalar *X, Int N)
Macro Definition Documentation
A
#define A (ii, jj) A[(ii)*N+(jj)]
X
#define X (ii, jj) X[(ii)*N+(jj)]
Function Documentation
det()
Scalar det (const Tensor & p)
Determinant of a tensor
Definition at line 144 of file tensor.cpp.
References Scalar, Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
dot() [1/2]
Vector dot (const STensor & q, const Vector & p)
Inner product of a symmetric tensor and a vector
Definition at line 80 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YY, Constants::YZ, and Constants::ZZ.
dot() [2/2]
Vector dot (const Tensor & q, const Vector & p)
Inner product of a tensor and a vector
Definition at line 72 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
Referenced by Mesh::MeshObject::breakEdges(), Mesh::MeshObject::coplanarFaces(), div_flux(), div_flux_implicit(), Mesh::MeshObject::fixHexCells(), flx(), gather_non_conforming(), Mesh::MeshObject::getHexCorners(), Mesh::initGeomMeshFields(), lap(), Mesh::MeshObject::mergeFacets(), Mesh::pointInLine(), Mesh::pointInPolygon(), Mesh::MeshObject::refineCell(), MeshField< type, entity >::refineField(), Mesh::MeshObject::refineMesh(), scatter_non_conforming(), and uds().
inv()
Tensor inv (const Tensor & p)
Inverse of a tensor
Definition at line 152 of file tensor.cpp.
References Scalar, Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
Referenced by DG::init_geom().
matinv()
void matinv (Scalar * A_, Scalar * X, Int N)
Inverse of matrix using Gauss-Jordan elimination
Definition at line 170 of file tensor.cpp.
References A, Scalar, and X.
Referenced by DG::init_basis().
matmul()
void matmul (Scalar * A, Scalar * B, Scalar * X, Int N)
Multiply two square matrices
Definition at line 225 of file tensor.cpp.
References A, Scalar, sum(), and X.
Referenced by DG::init_basis().
mattrn()
void mattrn (Scalar * A, Scalar * X, Int N)
Transpose square matrix
Definition at line 237 of file tensor.cpp.
References A, and X.
Referenced by DG::init_basis().
mul() [1/4]
STensor mul (const STensor & p, const STensor & q)
Product of two symmetric tensors
Definition at line 59 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YY, Constants::YZ, and Constants::ZZ.
mul() [2/4]
Tensor mul (const Tensor & p, const Tensor & q)
Product of two tensors
Definition at line 42 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
mul() [3/4]
STensor mul (const Vector & p)
Outer product of a vector with itself
Definition at line 30 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YY, Constants::YZ, and Constants::ZZ.
Referenced by sym().
mul() [4/4]
Tensor mul (const Vector & p, const Vector & q)
Outer product of two vectors
Definition at line 14 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
operator^()
Vector operator^ (const Vector & p, const Vector & q)
Cross product of two vectors
Definition at line 6 of file tensor.cpp.
References Constants::XX, Constants::YY, and Constants::ZZ.
rotate()
Vector rotate (const Vector & v, const Vector & N, const Scalar & theta)
Rotate a vector by an angle about a given axis The rotation is clock-wise in right-handed system.
Definition at line 134 of file tensor.cpp.
References Scalar, sum(), Constants::XX, Constants::YY, and Constants::ZZ.
Referenced by ADDV(), Prepare::decomposeXYZ(), Mesh::MeshObject::fixHexCells(), Mesh::MeshObject::mergeFacets(), and Mesh::MeshObject::refineFacet().
skw()
Tensor skw (const Tensor & p)
Skew-symmetric part of a tensor
Definition at line 100 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
Referenced by REALIZABLE_KE_Model::calcEddyViscosity(), and EddyViscosity_Model::getS2().
sym()
STensor sym (const Tensor & p)
Symmetric part of a tensor
Definition at line 88 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
Referenced by applyExplicitBCs(), REALIZABLE_KE_Model::calcEddyViscosity(), EddyViscosity_Model::getReynoldsStress(), EddyViscosity_Model::getS2(), and Turbulence_Model::getViscousStress().
trn()
Tensor trn (const Tensor & p)
Transpose of a tensor
Definition at line 116 of file tensor.cpp.
References Constants::XX, Constants::XY, Constants::XZ, Constants::YX, Constants::YY, Constants::YZ, Constants::ZX, Constants::ZY, and Constants::ZZ.
Referenced by Turbulence_Model::getExplicitStresses(), EddyViscosity_Model::getExplicitStresses(), and DG::init_geom().