NebulaSEM: /home/daniel/storage/NebulaSEM/src/util/util.h File Reference
util.h File Reference
#include "tensor.h"
#include <cstring>
#include <fstream>
#include <sstream>
#include <vector>
#include <list>
#include <map>
#include <algorithm>
#include <cstdarg>
#include <cctype>
Classes
class Util::ofstream_bin
class Util::ifstream_bin
struct Util::compare_pair_second< P >
struct Util::Option
struct Util::BoolOption
class Util::Parameters< T >
struct Util::ParamList
Namespaces
Util
Macros
#define AddB(T)
#define AddB(T)
#define addParam(T, N)
#define readp(N) params_##N.read(str,is,out)
Functions
template<class T1 , class T2 , typename Ts >
Ts & Util::operator<< (Ts &os, const std::pair< T1, T2 > &p)
template<class T1 , class T2 , typename Ts >
Ts & Util::operator>> (Ts &is, std::pair< T1, T2 > &p)
template<class T , typename Ts >
Ts & Util::operator<< (Ts &os, const std::vector< T > &p)
template<class T , typename Ts >
Ts & Util::operator>> (Ts &is, std::vector< T > &p)
template<typename Ts >
Ts & Util::operator<< (Ts &os, const std::vector< Int > &p)
template<class T1 , class T2 , typename Ts >
Ts & Util::operator<< (Ts &os, const std::map< T1, T2 > &p)
template<class T1 , class T2 , typename Ts >
Ts & Util::operator>> (Ts &is, std::map< T1, T2 > &p)
Int Util::hash_function (std::string s)
int Util::nextc (std::istream &)
int Util::compare (std::string &s1, std::string s2)
void Util::read_params (std::istream &, bool print, std::string block="")
Container iterators
#define forEach(field, i) for(Int i = 0;i < (field).size();i++)
#define forEachR(field, i) for(Int i = (field).size();i-- > 0;)
#define forEachS(field, i, strt) for(Int i = strt;i < (field).size();i++)
#define forEachSR(field, i, strt) for(Int i = (field).size();i-- > strt;)
#define forEachIt(field, it) for(auto it = (field).begin(); it != (field).end(); ++it)
#define copyColl(src, trg) std::copy(std::begin(src),std::end(src),std::back_inserter(trg));
#define eraseValue(field, val) (field).erase(std::remove((field).begin(),(field).end(),val),(field).end());
template<typename T >
void erase_indices (std::vector< T > &data, const std::vector< Int > &indicesToDelete)
template<bool subset = false>
bool equalSet (std::vector< Int > &v1, std::vector< Int > &v2)
Macro Definition Documentation
AddB [1/2]
#define AddB (T)
Value:
            friend Util::ofstream_bin& operator << (Util::ofstream_bin& os, const T& p) {   \
                os.mos.write((char*)&p, sizeof(p));                                         \
                return os;                                                                  \
            }
Definition at line 212 of file util.h.
AddB [2/2]
#define AddB (T)
Value:
            friend Util::ifstream_bin& operator >> (Util::ifstream_bin& is, T& p) {         \
                is.mos.read((char*)&p, sizeof(p));                                          \
                return is;                                                                  \
            }
Definition at line 212 of file util.h.
addParam
#define addParam (T, N)
Value:
    Parameters<T> params_##N;                       \
    void enroll(std::string str,T* addr) {          \
        params_##N.enroll(str,addr);                \
    }
Definition at line 329 of file util.h.
copyColl
#define copyColl (src, trg) std::copy(std::begin(src),std::end(src),std::back_inserter(trg));
Copy collection
Definition at line 35 of file util.h.
eraseValue
#define eraseValue (field, val) (field).erase(std::remove((field).begin(),(field).end(),val),(field).end());
Erase by value
Definition at line 39 of file util.h.
forEach
#define forEach (field, i) for(Int i = 0;i < (field).size();i++)
Definition at line 18 of file util.h.
forEachIt
#define forEachIt (field, it) for(auto it = (field).begin(); it != (field).end(); ++it)
Definition at line 30 of file util.h.
forEachR
#define forEachR (field, i) for(Int i = (field).size();i-- > 0;)
Definition at line 21 of file util.h.
forEachS
#define forEachS (field, i, strt) for(Int i = strt;i < (field).size();i++)
Definition at line 24 of file util.h.
forEachSR
#define forEachSR (field, i, strt) for(Int i = (field).size();i-- > strt;)
Definition at line 27 of file util.h.
readp
#define readp (N) params_##N.read(str,is,out)
Function Documentation
equalSet()
template<bool subset = false> bool equalSet (std::vector< Int > & v1, std::vector< Int > & v2)
Test if two Int vectors are equal. O(n^2) complexity but arrays are small since it is used for edges/faces/cells
Definition at line 68 of file util.h.
References forEach.
Referenced by Mesh::MeshObject::fixHexCells(), merge(), and Mesh::MeshObject::refineCell().
erase_indices()
template<typename T > void erase_indices (std::vector< T > & data, const std::vector< Int > & indicesToDelete)
Erase indices from a vector. It assumes the indices are already sorted
Definition at line 44 of file util.h.
References forEachIt.
Referenced by Mesh::MeshObject::fixHexCells(), Mesh::MeshObject::mergeFacetsGroup(), Mesh::MeshObject::refineCell(), Mesh::MeshObject::refineMesh(), Mesh::MeshObject::removeBoundary(), and Mesh::MeshObject::removeUnusedVertices().